/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreatePhoneNumberPortInRequestRequirementsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePhoneNumberPortInRequestRequirementsInner{}

// CreatePhoneNumberPortInRequestRequirementsInner struct for CreatePhoneNumberPortInRequestRequirementsInner
type CreatePhoneNumberPortInRequestRequirementsInner struct {
	// The requirement's id, from the requirements endpoint.
	RequirementTypeId string `json:"requirementTypeId"`
	// Text value, ISO datetime, or a documentId from POST /v1/phone-numbers/port-in/documents, per the requirement's kind.
	FieldValue string `json:"fieldValue"`
}

type _CreatePhoneNumberPortInRequestRequirementsInner CreatePhoneNumberPortInRequestRequirementsInner

// NewCreatePhoneNumberPortInRequestRequirementsInner instantiates a new CreatePhoneNumberPortInRequestRequirementsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePhoneNumberPortInRequestRequirementsInner(requirementTypeId string, fieldValue string) *CreatePhoneNumberPortInRequestRequirementsInner {
	this := CreatePhoneNumberPortInRequestRequirementsInner{}
	this.RequirementTypeId = requirementTypeId
	this.FieldValue = fieldValue
	return &this
}

// NewCreatePhoneNumberPortInRequestRequirementsInnerWithDefaults instantiates a new CreatePhoneNumberPortInRequestRequirementsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePhoneNumberPortInRequestRequirementsInnerWithDefaults() *CreatePhoneNumberPortInRequestRequirementsInner {
	this := CreatePhoneNumberPortInRequestRequirementsInner{}
	return &this
}

// GetRequirementTypeId returns the RequirementTypeId field value
func (o *CreatePhoneNumberPortInRequestRequirementsInner) GetRequirementTypeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequirementTypeId
}

// GetRequirementTypeIdOk returns a tuple with the RequirementTypeId field value
// and a boolean to check if the value has been set.
func (o *CreatePhoneNumberPortInRequestRequirementsInner) GetRequirementTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequirementTypeId, true
}

// SetRequirementTypeId sets field value
func (o *CreatePhoneNumberPortInRequestRequirementsInner) SetRequirementTypeId(v string) {
	o.RequirementTypeId = v
}

// GetFieldValue returns the FieldValue field value
func (o *CreatePhoneNumberPortInRequestRequirementsInner) GetFieldValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldValue
}

// GetFieldValueOk returns a tuple with the FieldValue field value
// and a boolean to check if the value has been set.
func (o *CreatePhoneNumberPortInRequestRequirementsInner) GetFieldValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldValue, true
}

// SetFieldValue sets field value
func (o *CreatePhoneNumberPortInRequestRequirementsInner) SetFieldValue(v string) {
	o.FieldValue = v
}

func (o CreatePhoneNumberPortInRequestRequirementsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePhoneNumberPortInRequestRequirementsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requirementTypeId"] = o.RequirementTypeId
	toSerialize["fieldValue"] = o.FieldValue
	return toSerialize, nil
}

func (o *CreatePhoneNumberPortInRequestRequirementsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requirementTypeId",
		"fieldValue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePhoneNumberPortInRequestRequirementsInner := _CreatePhoneNumberPortInRequestRequirementsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePhoneNumberPortInRequestRequirementsInner)

	if err != nil {
		return err
	}

	*o = CreatePhoneNumberPortInRequestRequirementsInner(varCreatePhoneNumberPortInRequestRequirementsInner)

	return err
}

type NullableCreatePhoneNumberPortInRequestRequirementsInner struct {
	value *CreatePhoneNumberPortInRequestRequirementsInner
	isSet bool
}

func (v NullableCreatePhoneNumberPortInRequestRequirementsInner) Get() *CreatePhoneNumberPortInRequestRequirementsInner {
	return v.value
}

func (v *NullableCreatePhoneNumberPortInRequestRequirementsInner) Set(val *CreatePhoneNumberPortInRequestRequirementsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePhoneNumberPortInRequestRequirementsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePhoneNumberPortInRequestRequirementsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePhoneNumberPortInRequestRequirementsInner(val *CreatePhoneNumberPortInRequestRequirementsInner) *NullableCreatePhoneNumberPortInRequestRequirementsInner {
	return &NullableCreatePhoneNumberPortInRequestRequirementsInner{value: val, isSet: true}
}

func (v NullableCreatePhoneNumberPortInRequestRequirementsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePhoneNumberPortInRequestRequirementsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
