/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InboxWebhookAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InboxWebhookAccount{}

// InboxWebhookAccount The account context included in inbox webhook payloads.
type InboxWebhookAccount struct {
	// Social account ID
	Id          string  `json:"id"`
	Platform    string  `json:"platform"`
	Username    string  `json:"username"`
	DisplayName *string `json:"displayName,omitempty"`
}

type _InboxWebhookAccount InboxWebhookAccount

// NewInboxWebhookAccount instantiates a new InboxWebhookAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInboxWebhookAccount(id string, platform string, username string) *InboxWebhookAccount {
	this := InboxWebhookAccount{}
	this.Id = id
	this.Platform = platform
	this.Username = username
	return &this
}

// NewInboxWebhookAccountWithDefaults instantiates a new InboxWebhookAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInboxWebhookAccountWithDefaults() *InboxWebhookAccount {
	this := InboxWebhookAccount{}
	return &this
}

// GetId returns the Id field value
func (o *InboxWebhookAccount) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InboxWebhookAccount) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InboxWebhookAccount) SetId(v string) {
	o.Id = v
}

// GetPlatform returns the Platform field value
func (o *InboxWebhookAccount) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *InboxWebhookAccount) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *InboxWebhookAccount) SetPlatform(v string) {
	o.Platform = v
}

// GetUsername returns the Username field value
func (o *InboxWebhookAccount) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *InboxWebhookAccount) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *InboxWebhookAccount) SetUsername(v string) {
	o.Username = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *InboxWebhookAccount) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboxWebhookAccount) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *InboxWebhookAccount) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *InboxWebhookAccount) SetDisplayName(v string) {
	o.DisplayName = &v
}

func (o InboxWebhookAccount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InboxWebhookAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["platform"] = o.Platform
	toSerialize["username"] = o.Username
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	return toSerialize, nil
}

func (o *InboxWebhookAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"platform",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInboxWebhookAccount := _InboxWebhookAccount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInboxWebhookAccount)

	if err != nil {
		return err
	}

	*o = InboxWebhookAccount(varInboxWebhookAccount)

	return err
}

type NullableInboxWebhookAccount struct {
	value *InboxWebhookAccount
	isSet bool
}

func (v NullableInboxWebhookAccount) Get() *InboxWebhookAccount {
	return v.value
}

func (v *NullableInboxWebhookAccount) Set(val *InboxWebhookAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableInboxWebhookAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableInboxWebhookAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInboxWebhookAccount(val *InboxWebhookAccount) *NullableInboxWebhookAccount {
	return &NullableInboxWebhookAccount{value: val, isSet: true}
}

func (v NullableInboxWebhookAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInboxWebhookAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
