/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.69.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
	"time"
)

// checks if the SearchTweets200ResponseTweetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchTweets200ResponseTweetsInner{}

// SearchTweets200ResponseTweetsInner struct for SearchTweets200ResponseTweetsInner
type SearchTweets200ResponseTweetsInner struct {
	Id             *string    `json:"id,omitempty"`
	Text           *string    `json:"text,omitempty"`
	Created        *time.Time `json:"created,omitempty"`
	ConversationId *string    `json:"conversationId,omitempty"`
	// Parent tweet ID when the result is itself a reply
	InReplyToTweetId NullableString                            `json:"inReplyToTweetId,omitempty"`
	Lang             *string                                   `json:"lang,omitempty"`
	Author           *SearchTweets200ResponseTweetsInnerAuthor `json:"author,omitempty"`
	LikeCount        *int32                                    `json:"likeCount,omitempty"`
	ReplyCount       *int32                                    `json:"replyCount,omitempty"`
	RetweetCount     *int32                                    `json:"retweetCount,omitempty"`
	QuoteCount       *int32                                    `json:"quoteCount,omitempty"`
	Platform         *string                                   `json:"platform,omitempty"`
}

// NewSearchTweets200ResponseTweetsInner instantiates a new SearchTweets200ResponseTweetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchTweets200ResponseTweetsInner() *SearchTweets200ResponseTweetsInner {
	this := SearchTweets200ResponseTweetsInner{}
	return &this
}

// NewSearchTweets200ResponseTweetsInnerWithDefaults instantiates a new SearchTweets200ResponseTweetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchTweets200ResponseTweetsInnerWithDefaults() *SearchTweets200ResponseTweetsInner {
	this := SearchTweets200ResponseTweetsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SearchTweets200ResponseTweetsInner) SetId(v string) {
	o.Id = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *SearchTweets200ResponseTweetsInner) SetText(v string) {
	o.Text = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *SearchTweets200ResponseTweetsInner) SetCreated(v time.Time) {
	o.Created = &v
}

// GetConversationId returns the ConversationId field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetConversationId() string {
	if o == nil || IsNil(o.ConversationId) {
		var ret string
		return ret
	}
	return *o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetConversationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConversationId) {
		return nil, false
	}
	return o.ConversationId, true
}

// HasConversationId returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasConversationId() bool {
	if o != nil && !IsNil(o.ConversationId) {
		return true
	}

	return false
}

// SetConversationId gets a reference to the given string and assigns it to the ConversationId field.
func (o *SearchTweets200ResponseTweetsInner) SetConversationId(v string) {
	o.ConversationId = &v
}

// GetInReplyToTweetId returns the InReplyToTweetId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchTweets200ResponseTweetsInner) GetInReplyToTweetId() string {
	if o == nil || IsNil(o.InReplyToTweetId.Get()) {
		var ret string
		return ret
	}
	return *o.InReplyToTweetId.Get()
}

// GetInReplyToTweetIdOk returns a tuple with the InReplyToTweetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchTweets200ResponseTweetsInner) GetInReplyToTweetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InReplyToTweetId.Get(), o.InReplyToTweetId.IsSet()
}

// HasInReplyToTweetId returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasInReplyToTweetId() bool {
	if o != nil && o.InReplyToTweetId.IsSet() {
		return true
	}

	return false
}

// SetInReplyToTweetId gets a reference to the given NullableString and assigns it to the InReplyToTweetId field.
func (o *SearchTweets200ResponseTweetsInner) SetInReplyToTweetId(v string) {
	o.InReplyToTweetId.Set(&v)
}

// SetInReplyToTweetIdNil sets the value for InReplyToTweetId to be an explicit nil
func (o *SearchTweets200ResponseTweetsInner) SetInReplyToTweetIdNil() {
	o.InReplyToTweetId.Set(nil)
}

// UnsetInReplyToTweetId ensures that no value is present for InReplyToTweetId, not even an explicit nil
func (o *SearchTweets200ResponseTweetsInner) UnsetInReplyToTweetId() {
	o.InReplyToTweetId.Unset()
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetLang() string {
	if o == nil || IsNil(o.Lang) {
		var ret string
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetLangOk() (*string, bool) {
	if o == nil || IsNil(o.Lang) {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasLang() bool {
	if o != nil && !IsNil(o.Lang) {
		return true
	}

	return false
}

// SetLang gets a reference to the given string and assigns it to the Lang field.
func (o *SearchTweets200ResponseTweetsInner) SetLang(v string) {
	o.Lang = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetAuthor() SearchTweets200ResponseTweetsInnerAuthor {
	if o == nil || IsNil(o.Author) {
		var ret SearchTweets200ResponseTweetsInnerAuthor
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetAuthorOk() (*SearchTweets200ResponseTweetsInnerAuthor, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given SearchTweets200ResponseTweetsInnerAuthor and assigns it to the Author field.
func (o *SearchTweets200ResponseTweetsInner) SetAuthor(v SearchTweets200ResponseTweetsInnerAuthor) {
	o.Author = &v
}

// GetLikeCount returns the LikeCount field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetLikeCount() int32 {
	if o == nil || IsNil(o.LikeCount) {
		var ret int32
		return ret
	}
	return *o.LikeCount
}

// GetLikeCountOk returns a tuple with the LikeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetLikeCountOk() (*int32, bool) {
	if o == nil || IsNil(o.LikeCount) {
		return nil, false
	}
	return o.LikeCount, true
}

// HasLikeCount returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasLikeCount() bool {
	if o != nil && !IsNil(o.LikeCount) {
		return true
	}

	return false
}

// SetLikeCount gets a reference to the given int32 and assigns it to the LikeCount field.
func (o *SearchTweets200ResponseTweetsInner) SetLikeCount(v int32) {
	o.LikeCount = &v
}

// GetReplyCount returns the ReplyCount field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetReplyCount() int32 {
	if o == nil || IsNil(o.ReplyCount) {
		var ret int32
		return ret
	}
	return *o.ReplyCount
}

// GetReplyCountOk returns a tuple with the ReplyCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetReplyCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ReplyCount) {
		return nil, false
	}
	return o.ReplyCount, true
}

// HasReplyCount returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasReplyCount() bool {
	if o != nil && !IsNil(o.ReplyCount) {
		return true
	}

	return false
}

// SetReplyCount gets a reference to the given int32 and assigns it to the ReplyCount field.
func (o *SearchTweets200ResponseTweetsInner) SetReplyCount(v int32) {
	o.ReplyCount = &v
}

// GetRetweetCount returns the RetweetCount field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetRetweetCount() int32 {
	if o == nil || IsNil(o.RetweetCount) {
		var ret int32
		return ret
	}
	return *o.RetweetCount
}

// GetRetweetCountOk returns a tuple with the RetweetCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetRetweetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RetweetCount) {
		return nil, false
	}
	return o.RetweetCount, true
}

// HasRetweetCount returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasRetweetCount() bool {
	if o != nil && !IsNil(o.RetweetCount) {
		return true
	}

	return false
}

// SetRetweetCount gets a reference to the given int32 and assigns it to the RetweetCount field.
func (o *SearchTweets200ResponseTweetsInner) SetRetweetCount(v int32) {
	o.RetweetCount = &v
}

// GetQuoteCount returns the QuoteCount field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetQuoteCount() int32 {
	if o == nil || IsNil(o.QuoteCount) {
		var ret int32
		return ret
	}
	return *o.QuoteCount
}

// GetQuoteCountOk returns a tuple with the QuoteCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetQuoteCountOk() (*int32, bool) {
	if o == nil || IsNil(o.QuoteCount) {
		return nil, false
	}
	return o.QuoteCount, true
}

// HasQuoteCount returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasQuoteCount() bool {
	if o != nil && !IsNil(o.QuoteCount) {
		return true
	}

	return false
}

// SetQuoteCount gets a reference to the given int32 and assigns it to the QuoteCount field.
func (o *SearchTweets200ResponseTweetsInner) SetQuoteCount(v int32) {
	o.QuoteCount = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *SearchTweets200ResponseTweetsInner) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTweets200ResponseTweetsInner) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *SearchTweets200ResponseTweetsInner) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *SearchTweets200ResponseTweetsInner) SetPlatform(v string) {
	o.Platform = &v
}

func (o SearchTweets200ResponseTweetsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchTweets200ResponseTweetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.ConversationId) {
		toSerialize["conversationId"] = o.ConversationId
	}
	if o.InReplyToTweetId.IsSet() {
		toSerialize["inReplyToTweetId"] = o.InReplyToTweetId.Get()
	}
	if !IsNil(o.Lang) {
		toSerialize["lang"] = o.Lang
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.LikeCount) {
		toSerialize["likeCount"] = o.LikeCount
	}
	if !IsNil(o.ReplyCount) {
		toSerialize["replyCount"] = o.ReplyCount
	}
	if !IsNil(o.RetweetCount) {
		toSerialize["retweetCount"] = o.RetweetCount
	}
	if !IsNil(o.QuoteCount) {
		toSerialize["quoteCount"] = o.QuoteCount
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	return toSerialize, nil
}

type NullableSearchTweets200ResponseTweetsInner struct {
	value *SearchTweets200ResponseTweetsInner
	isSet bool
}

func (v NullableSearchTweets200ResponseTweetsInner) Get() *SearchTweets200ResponseTweetsInner {
	return v.value
}

func (v *NullableSearchTweets200ResponseTweetsInner) Set(val *SearchTweets200ResponseTweetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchTweets200ResponseTweetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchTweets200ResponseTweetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchTweets200ResponseTweetsInner(val *SearchTweets200ResponseTweetsInner) *NullableSearchTweets200ResponseTweetsInner {
	return &NullableSearchTweets200ResponseTweetsInner{value: val, isSet: true}
}

func (v NullableSearchTweets200ResponseTweetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchTweets200ResponseTweetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
