/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.174.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TrackingTagEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrackingTagEvent{}

// TrackingTagEvent A conversion event tied to a tracking tag (Google conversion action, LinkedIn conversion rule, X web event tag, OpenAI event setting, TikTok pixel event, Meta custom conversion).
type TrackingTagEvent struct {
	// Platform-native event id, the `{eventId}` of the per-event routes.
	Id   string `json:"id"`
	Name string `json:"name"`
	// Platform event type or category.
	Type *string `json:"type,omitempty"`
	// The neutral site event this conversion is fired for, when it maps to one.
	SiteEvent *string `json:"siteEvent,omitempty"`
	// What the site sends to fire this event (Google conversion label, LinkedIn conversion rule id, X `tw-` event id).
	SiteEventId     *string  `json:"siteEventId,omitempty"`
	Status          *string  `json:"status,omitempty"`
	DefaultValue    *float32 `json:"defaultValue,omitempty"`
	Currency        *string  `json:"currency,omitempty"`
	ClickWindowDays *int32   `json:"clickWindowDays,omitempty"`
	ViewWindowDays  *int32   `json:"viewWindowDays,omitempty"`
	// Fires only on pages whose URL contains this text (case-insensitive).
	UrlContains *string `json:"urlContains,omitempty"`
	// `defaultValue` is recorded even when the conversion sends its own value.
	AlwaysUseDefaultValue *bool `json:"alwaysUseDefaultValue,omitempty"`
	// Primary conversions count toward bidding and the Conversions column; secondary ones are observation only (Google `primary_for_goal`).
	Primary *bool `json:"primary,omitempty"`
	// `one` counts at most one conversion per ad interaction (leads), `every` counts each (purchases).
	CountingType *string `json:"countingType,omitempty"`
}

type _TrackingTagEvent TrackingTagEvent

// NewTrackingTagEvent instantiates a new TrackingTagEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrackingTagEvent(id string, name string) *TrackingTagEvent {
	this := TrackingTagEvent{}
	this.Id = id
	this.Name = name
	return &this
}

// NewTrackingTagEventWithDefaults instantiates a new TrackingTagEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrackingTagEventWithDefaults() *TrackingTagEvent {
	this := TrackingTagEvent{}
	return &this
}

// GetId returns the Id field value
func (o *TrackingTagEvent) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TrackingTagEvent) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TrackingTagEvent) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TrackingTagEvent) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TrackingTagEvent) SetType(v string) {
	o.Type = &v
}

// GetSiteEvent returns the SiteEvent field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetSiteEvent() string {
	if o == nil || IsNil(o.SiteEvent) {
		var ret string
		return ret
	}
	return *o.SiteEvent
}

// GetSiteEventOk returns a tuple with the SiteEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetSiteEventOk() (*string, bool) {
	if o == nil || IsNil(o.SiteEvent) {
		return nil, false
	}
	return o.SiteEvent, true
}

// HasSiteEvent returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasSiteEvent() bool {
	if o != nil && !IsNil(o.SiteEvent) {
		return true
	}

	return false
}

// SetSiteEvent gets a reference to the given string and assigns it to the SiteEvent field.
func (o *TrackingTagEvent) SetSiteEvent(v string) {
	o.SiteEvent = &v
}

// GetSiteEventId returns the SiteEventId field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetSiteEventId() string {
	if o == nil || IsNil(o.SiteEventId) {
		var ret string
		return ret
	}
	return *o.SiteEventId
}

// GetSiteEventIdOk returns a tuple with the SiteEventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetSiteEventIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteEventId) {
		return nil, false
	}
	return o.SiteEventId, true
}

// HasSiteEventId returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasSiteEventId() bool {
	if o != nil && !IsNil(o.SiteEventId) {
		return true
	}

	return false
}

// SetSiteEventId gets a reference to the given string and assigns it to the SiteEventId field.
func (o *TrackingTagEvent) SetSiteEventId(v string) {
	o.SiteEventId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TrackingTagEvent) SetStatus(v string) {
	o.Status = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetDefaultValue() float32 {
	if o == nil || IsNil(o.DefaultValue) {
		var ret float32
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetDefaultValueOk() (*float32, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given float32 and assigns it to the DefaultValue field.
func (o *TrackingTagEvent) SetDefaultValue(v float32) {
	o.DefaultValue = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *TrackingTagEvent) SetCurrency(v string) {
	o.Currency = &v
}

// GetClickWindowDays returns the ClickWindowDays field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetClickWindowDays() int32 {
	if o == nil || IsNil(o.ClickWindowDays) {
		var ret int32
		return ret
	}
	return *o.ClickWindowDays
}

// GetClickWindowDaysOk returns a tuple with the ClickWindowDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetClickWindowDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.ClickWindowDays) {
		return nil, false
	}
	return o.ClickWindowDays, true
}

// HasClickWindowDays returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasClickWindowDays() bool {
	if o != nil && !IsNil(o.ClickWindowDays) {
		return true
	}

	return false
}

// SetClickWindowDays gets a reference to the given int32 and assigns it to the ClickWindowDays field.
func (o *TrackingTagEvent) SetClickWindowDays(v int32) {
	o.ClickWindowDays = &v
}

// GetViewWindowDays returns the ViewWindowDays field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetViewWindowDays() int32 {
	if o == nil || IsNil(o.ViewWindowDays) {
		var ret int32
		return ret
	}
	return *o.ViewWindowDays
}

// GetViewWindowDaysOk returns a tuple with the ViewWindowDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetViewWindowDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.ViewWindowDays) {
		return nil, false
	}
	return o.ViewWindowDays, true
}

// HasViewWindowDays returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasViewWindowDays() bool {
	if o != nil && !IsNil(o.ViewWindowDays) {
		return true
	}

	return false
}

// SetViewWindowDays gets a reference to the given int32 and assigns it to the ViewWindowDays field.
func (o *TrackingTagEvent) SetViewWindowDays(v int32) {
	o.ViewWindowDays = &v
}

// GetUrlContains returns the UrlContains field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetUrlContains() string {
	if o == nil || IsNil(o.UrlContains) {
		var ret string
		return ret
	}
	return *o.UrlContains
}

// GetUrlContainsOk returns a tuple with the UrlContains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetUrlContainsOk() (*string, bool) {
	if o == nil || IsNil(o.UrlContains) {
		return nil, false
	}
	return o.UrlContains, true
}

// HasUrlContains returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasUrlContains() bool {
	if o != nil && !IsNil(o.UrlContains) {
		return true
	}

	return false
}

// SetUrlContains gets a reference to the given string and assigns it to the UrlContains field.
func (o *TrackingTagEvent) SetUrlContains(v string) {
	o.UrlContains = &v
}

// GetAlwaysUseDefaultValue returns the AlwaysUseDefaultValue field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetAlwaysUseDefaultValue() bool {
	if o == nil || IsNil(o.AlwaysUseDefaultValue) {
		var ret bool
		return ret
	}
	return *o.AlwaysUseDefaultValue
}

// GetAlwaysUseDefaultValueOk returns a tuple with the AlwaysUseDefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetAlwaysUseDefaultValueOk() (*bool, bool) {
	if o == nil || IsNil(o.AlwaysUseDefaultValue) {
		return nil, false
	}
	return o.AlwaysUseDefaultValue, true
}

// HasAlwaysUseDefaultValue returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasAlwaysUseDefaultValue() bool {
	if o != nil && !IsNil(o.AlwaysUseDefaultValue) {
		return true
	}

	return false
}

// SetAlwaysUseDefaultValue gets a reference to the given bool and assigns it to the AlwaysUseDefaultValue field.
func (o *TrackingTagEvent) SetAlwaysUseDefaultValue(v bool) {
	o.AlwaysUseDefaultValue = &v
}

// GetPrimary returns the Primary field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetPrimary() bool {
	if o == nil || IsNil(o.Primary) {
		var ret bool
		return ret
	}
	return *o.Primary
}

// GetPrimaryOk returns a tuple with the Primary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetPrimaryOk() (*bool, bool) {
	if o == nil || IsNil(o.Primary) {
		return nil, false
	}
	return o.Primary, true
}

// HasPrimary returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasPrimary() bool {
	if o != nil && !IsNil(o.Primary) {
		return true
	}

	return false
}

// SetPrimary gets a reference to the given bool and assigns it to the Primary field.
func (o *TrackingTagEvent) SetPrimary(v bool) {
	o.Primary = &v
}

// GetCountingType returns the CountingType field value if set, zero value otherwise.
func (o *TrackingTagEvent) GetCountingType() string {
	if o == nil || IsNil(o.CountingType) {
		var ret string
		return ret
	}
	return *o.CountingType
}

// GetCountingTypeOk returns a tuple with the CountingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingTagEvent) GetCountingTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CountingType) {
		return nil, false
	}
	return o.CountingType, true
}

// HasCountingType returns a boolean if a field has been set.
func (o *TrackingTagEvent) HasCountingType() bool {
	if o != nil && !IsNil(o.CountingType) {
		return true
	}

	return false
}

// SetCountingType gets a reference to the given string and assigns it to the CountingType field.
func (o *TrackingTagEvent) SetCountingType(v string) {
	o.CountingType = &v
}

func (o TrackingTagEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrackingTagEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.SiteEvent) {
		toSerialize["siteEvent"] = o.SiteEvent
	}
	if !IsNil(o.SiteEventId) {
		toSerialize["siteEventId"] = o.SiteEventId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.ClickWindowDays) {
		toSerialize["clickWindowDays"] = o.ClickWindowDays
	}
	if !IsNil(o.ViewWindowDays) {
		toSerialize["viewWindowDays"] = o.ViewWindowDays
	}
	if !IsNil(o.UrlContains) {
		toSerialize["urlContains"] = o.UrlContains
	}
	if !IsNil(o.AlwaysUseDefaultValue) {
		toSerialize["alwaysUseDefaultValue"] = o.AlwaysUseDefaultValue
	}
	if !IsNil(o.Primary) {
		toSerialize["primary"] = o.Primary
	}
	if !IsNil(o.CountingType) {
		toSerialize["countingType"] = o.CountingType
	}
	return toSerialize, nil
}

func (o *TrackingTagEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrackingTagEvent := _TrackingTagEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrackingTagEvent)

	if err != nil {
		return err
	}

	*o = TrackingTagEvent(varTrackingTagEvent)

	return err
}

type NullableTrackingTagEvent struct {
	value *TrackingTagEvent
	isSet bool
}

func (v NullableTrackingTagEvent) Get() *TrackingTagEvent {
	return v.value
}

func (v *NullableTrackingTagEvent) Set(val *TrackingTagEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackingTagEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackingTagEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackingTagEvent(val *TrackingTagEvent) *NullableTrackingTagEvent {
	return &NullableTrackingTagEvent{value: val, isSet: true}
}

func (v NullableTrackingTagEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackingTagEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
