/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the CreateWhatsAppGroupChat201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWhatsAppGroupChat201Response{}

// CreateWhatsAppGroupChat201Response struct for CreateWhatsAppGroupChat201Response
type CreateWhatsAppGroupChat201Response struct {
	Success *bool                                    `json:"success,omitempty"`
	Group   *CreateWhatsAppGroupChat201ResponseGroup `json:"group,omitempty"`
}

// NewCreateWhatsAppGroupChat201Response instantiates a new CreateWhatsAppGroupChat201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWhatsAppGroupChat201Response() *CreateWhatsAppGroupChat201Response {
	this := CreateWhatsAppGroupChat201Response{}
	return &this
}

// NewCreateWhatsAppGroupChat201ResponseWithDefaults instantiates a new CreateWhatsAppGroupChat201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWhatsAppGroupChat201ResponseWithDefaults() *CreateWhatsAppGroupChat201Response {
	this := CreateWhatsAppGroupChat201Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CreateWhatsAppGroupChat201Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWhatsAppGroupChat201Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CreateWhatsAppGroupChat201Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CreateWhatsAppGroupChat201Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *CreateWhatsAppGroupChat201Response) GetGroup() CreateWhatsAppGroupChat201ResponseGroup {
	if o == nil || IsNil(o.Group) {
		var ret CreateWhatsAppGroupChat201ResponseGroup
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWhatsAppGroupChat201Response) GetGroupOk() (*CreateWhatsAppGroupChat201ResponseGroup, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *CreateWhatsAppGroupChat201Response) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given CreateWhatsAppGroupChat201ResponseGroup and assigns it to the Group field.
func (o *CreateWhatsAppGroupChat201Response) SetGroup(v CreateWhatsAppGroupChat201ResponseGroup) {
	o.Group = &v
}

func (o CreateWhatsAppGroupChat201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWhatsAppGroupChat201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	return toSerialize, nil
}

type NullableCreateWhatsAppGroupChat201Response struct {
	value *CreateWhatsAppGroupChat201Response
	isSet bool
}

func (v NullableCreateWhatsAppGroupChat201Response) Get() *CreateWhatsAppGroupChat201Response {
	return v.value
}

func (v *NullableCreateWhatsAppGroupChat201Response) Set(val *CreateWhatsAppGroupChat201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWhatsAppGroupChat201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWhatsAppGroupChat201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWhatsAppGroupChat201Response(val *CreateWhatsAppGroupChat201Response) *NullableCreateWhatsAppGroupChat201Response {
	return &NullableCreateWhatsAppGroupChat201Response{value: val, isSet: true}
}

func (v NullableCreateWhatsAppGroupChat201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWhatsAppGroupChat201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
