/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PostUserId - struct for PostUserId
type PostUserId struct {
	User   *User
	String *string
}

// UserAsPostUserId is a convenience function that returns User wrapped in PostUserId
func UserAsPostUserId(v *User) PostUserId {
	return PostUserId{
		User: v,
	}
}

// stringAsPostUserId is a convenience function that returns string wrapped in PostUserId
func StringAsPostUserId(v *string) PostUserId {
	return PostUserId{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PostUserId) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into User
	err = newStrictDecoder(data).Decode(&dst.User)
	if err == nil {
		jsonUser, _ := json.Marshal(dst.User)
		if string(jsonUser) == "{}" { // empty struct
			dst.User = nil
		} else {
			if err = validator.Validate(dst.User); err != nil {
				dst.User = nil
			} else {
				match++
			}
		}
	} else {
		dst.User = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.User = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PostUserId)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PostUserId)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostUserId) MarshalJSON() ([]byte, error) {
	if src.User != nil {
		return json.Marshal(&src.User)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PostUserId) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.User != nil {
		return obj.User
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PostUserId) GetActualInstanceValue() interface{} {
	if obj.User != nil {
		return *obj.User
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePostUserId struct {
	value *PostUserId
	isSet bool
}

func (v NullablePostUserId) Get() *PostUserId {
	return v.value
}

func (v *NullablePostUserId) Set(val *PostUserId) {
	v.value = val
	v.isSet = true
}

func (v NullablePostUserId) IsSet() bool {
	return v.isSet
}

func (v *NullablePostUserId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostUserId(val *PostUserId) *NullablePostUserId {
	return &NullablePostUserId{value: val, isSet: true}
}

func (v NullablePostUserId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostUserId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
