/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BusinessAgentSkillInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BusinessAgentSkillInput{}

// BusinessAgentSkillInput struct for BusinessAgentSkillInput
type BusinessAgentSkillInput struct {
	// Lowercase letters, digits and hyphens, e.g. greeting-skill.
	Title *string `json:"title,omitempty" validate:"regexp=^[a-z0-9]+(?:-[a-z0-9]+)*$"`
	// When the agent should apply the skill.
	Description *string `json:"description,omitempty"`
	// The instructions themselves. Avoid two skills that both claim priority for the same situation.
	Skill string `json:"skill"`
}

type _BusinessAgentSkillInput BusinessAgentSkillInput

// NewBusinessAgentSkillInput instantiates a new BusinessAgentSkillInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBusinessAgentSkillInput(skill string) *BusinessAgentSkillInput {
	this := BusinessAgentSkillInput{}
	this.Skill = skill
	return &this
}

// NewBusinessAgentSkillInputWithDefaults instantiates a new BusinessAgentSkillInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBusinessAgentSkillInputWithDefaults() *BusinessAgentSkillInput {
	this := BusinessAgentSkillInput{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *BusinessAgentSkillInput) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessAgentSkillInput) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *BusinessAgentSkillInput) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *BusinessAgentSkillInput) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BusinessAgentSkillInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessAgentSkillInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BusinessAgentSkillInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BusinessAgentSkillInput) SetDescription(v string) {
	o.Description = &v
}

// GetSkill returns the Skill field value
func (o *BusinessAgentSkillInput) GetSkill() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Skill
}

// GetSkillOk returns a tuple with the Skill field value
// and a boolean to check if the value has been set.
func (o *BusinessAgentSkillInput) GetSkillOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Skill, true
}

// SetSkill sets field value
func (o *BusinessAgentSkillInput) SetSkill(v string) {
	o.Skill = v
}

func (o BusinessAgentSkillInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BusinessAgentSkillInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["skill"] = o.Skill
	return toSerialize, nil
}

func (o *BusinessAgentSkillInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"skill",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBusinessAgentSkillInput := _BusinessAgentSkillInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBusinessAgentSkillInput)

	if err != nil {
		return err
	}

	*o = BusinessAgentSkillInput(varBusinessAgentSkillInput)

	return err
}

type NullableBusinessAgentSkillInput struct {
	value *BusinessAgentSkillInput
	isSet bool
}

func (v NullableBusinessAgentSkillInput) Get() *BusinessAgentSkillInput {
	return v.value
}

func (v *NullableBusinessAgentSkillInput) Set(val *BusinessAgentSkillInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBusinessAgentSkillInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBusinessAgentSkillInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBusinessAgentSkillInput(val *BusinessAgentSkillInput) *NullableBusinessAgentSkillInput {
	return &NullableBusinessAgentSkillInput{value: val, isSet: true}
}

func (v NullableBusinessAgentSkillInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBusinessAgentSkillInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
