/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.206.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ChangeCommerceInventoryRequestChangesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeCommerceInventoryRequestChangesInner{}

// ChangeCommerceInventoryRequestChangesInner struct for ChangeCommerceInventoryRequestChangesInner
type ChangeCommerceInventoryRequestChangesInner struct {
	VariantId  string `json:"variantId"`
	LocationId string `json:"locationId"`
	Quantity   int32  `json:"quantity"`
}

type _ChangeCommerceInventoryRequestChangesInner ChangeCommerceInventoryRequestChangesInner

// NewChangeCommerceInventoryRequestChangesInner instantiates a new ChangeCommerceInventoryRequestChangesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeCommerceInventoryRequestChangesInner(variantId string, locationId string, quantity int32) *ChangeCommerceInventoryRequestChangesInner {
	this := ChangeCommerceInventoryRequestChangesInner{}
	this.VariantId = variantId
	this.LocationId = locationId
	this.Quantity = quantity
	return &this
}

// NewChangeCommerceInventoryRequestChangesInnerWithDefaults instantiates a new ChangeCommerceInventoryRequestChangesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeCommerceInventoryRequestChangesInnerWithDefaults() *ChangeCommerceInventoryRequestChangesInner {
	this := ChangeCommerceInventoryRequestChangesInner{}
	return &this
}

// GetVariantId returns the VariantId field value
func (o *ChangeCommerceInventoryRequestChangesInner) GetVariantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VariantId
}

// GetVariantIdOk returns a tuple with the VariantId field value
// and a boolean to check if the value has been set.
func (o *ChangeCommerceInventoryRequestChangesInner) GetVariantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VariantId, true
}

// SetVariantId sets field value
func (o *ChangeCommerceInventoryRequestChangesInner) SetVariantId(v string) {
	o.VariantId = v
}

// GetLocationId returns the LocationId field value
func (o *ChangeCommerceInventoryRequestChangesInner) GetLocationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value
// and a boolean to check if the value has been set.
func (o *ChangeCommerceInventoryRequestChangesInner) GetLocationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationId, true
}

// SetLocationId sets field value
func (o *ChangeCommerceInventoryRequestChangesInner) SetLocationId(v string) {
	o.LocationId = v
}

// GetQuantity returns the Quantity field value
func (o *ChangeCommerceInventoryRequestChangesInner) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *ChangeCommerceInventoryRequestChangesInner) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *ChangeCommerceInventoryRequestChangesInner) SetQuantity(v int32) {
	o.Quantity = v
}

func (o ChangeCommerceInventoryRequestChangesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeCommerceInventoryRequestChangesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["variantId"] = o.VariantId
	toSerialize["locationId"] = o.LocationId
	toSerialize["quantity"] = o.Quantity
	return toSerialize, nil
}

func (o *ChangeCommerceInventoryRequestChangesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"variantId",
		"locationId",
		"quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangeCommerceInventoryRequestChangesInner := _ChangeCommerceInventoryRequestChangesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChangeCommerceInventoryRequestChangesInner)

	if err != nil {
		return err
	}

	*o = ChangeCommerceInventoryRequestChangesInner(varChangeCommerceInventoryRequestChangesInner)

	return err
}

type NullableChangeCommerceInventoryRequestChangesInner struct {
	value *ChangeCommerceInventoryRequestChangesInner
	isSet bool
}

func (v NullableChangeCommerceInventoryRequestChangesInner) Get() *ChangeCommerceInventoryRequestChangesInner {
	return v.value
}

func (v *NullableChangeCommerceInventoryRequestChangesInner) Set(val *ChangeCommerceInventoryRequestChangesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeCommerceInventoryRequestChangesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeCommerceInventoryRequestChangesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeCommerceInventoryRequestChangesInner(val *ChangeCommerceInventoryRequestChangesInner) *NullableChangeCommerceInventoryRequestChangesInner {
	return &NullableChangeCommerceInventoryRequestChangesInner{value: val, isSet: true}
}

func (v NullableChangeCommerceInventoryRequestChangesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeCommerceInventoryRequestChangesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
