/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EnableWhatsAppCallingLegacyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnableWhatsAppCallingLegacyRequest{}

// EnableWhatsAppCallingLegacyRequest struct for EnableWhatsAppCallingLegacyRequest
type EnableWhatsAppCallingLegacyRequest struct {
	AccountId string `json:"accountId"`
	// tel:+E164 / sip:... / wss://... destination
	ForwardTo       string  `json:"forwardTo"`
	SipAuthUsername *string `json:"sipAuthUsername,omitempty"`
	// Stored encrypted, never returned by any endpoint.
	SipAuthPassword   *string  `json:"sipAuthPassword,omitempty"`
	RecordingEnabled  *bool    `json:"recordingEnabled,omitempty"`
	CallIconCountries []string `json:"callIconCountries,omitempty"`
}

type _EnableWhatsAppCallingLegacyRequest EnableWhatsAppCallingLegacyRequest

// NewEnableWhatsAppCallingLegacyRequest instantiates a new EnableWhatsAppCallingLegacyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnableWhatsAppCallingLegacyRequest(accountId string, forwardTo string) *EnableWhatsAppCallingLegacyRequest {
	this := EnableWhatsAppCallingLegacyRequest{}
	this.AccountId = accountId
	this.ForwardTo = forwardTo
	var recordingEnabled bool = false
	this.RecordingEnabled = &recordingEnabled
	return &this
}

// NewEnableWhatsAppCallingLegacyRequestWithDefaults instantiates a new EnableWhatsAppCallingLegacyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnableWhatsAppCallingLegacyRequestWithDefaults() *EnableWhatsAppCallingLegacyRequest {
	this := EnableWhatsAppCallingLegacyRequest{}
	var recordingEnabled bool = false
	this.RecordingEnabled = &recordingEnabled
	return &this
}

// GetAccountId returns the AccountId field value
func (o *EnableWhatsAppCallingLegacyRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *EnableWhatsAppCallingLegacyRequest) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *EnableWhatsAppCallingLegacyRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetForwardTo returns the ForwardTo field value
func (o *EnableWhatsAppCallingLegacyRequest) GetForwardTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ForwardTo
}

// GetForwardToOk returns a tuple with the ForwardTo field value
// and a boolean to check if the value has been set.
func (o *EnableWhatsAppCallingLegacyRequest) GetForwardToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ForwardTo, true
}

// SetForwardTo sets field value
func (o *EnableWhatsAppCallingLegacyRequest) SetForwardTo(v string) {
	o.ForwardTo = v
}

// GetSipAuthUsername returns the SipAuthUsername field value if set, zero value otherwise.
func (o *EnableWhatsAppCallingLegacyRequest) GetSipAuthUsername() string {
	if o == nil || IsNil(o.SipAuthUsername) {
		var ret string
		return ret
	}
	return *o.SipAuthUsername
}

// GetSipAuthUsernameOk returns a tuple with the SipAuthUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnableWhatsAppCallingLegacyRequest) GetSipAuthUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.SipAuthUsername) {
		return nil, false
	}
	return o.SipAuthUsername, true
}

// HasSipAuthUsername returns a boolean if a field has been set.
func (o *EnableWhatsAppCallingLegacyRequest) HasSipAuthUsername() bool {
	if o != nil && !IsNil(o.SipAuthUsername) {
		return true
	}

	return false
}

// SetSipAuthUsername gets a reference to the given string and assigns it to the SipAuthUsername field.
func (o *EnableWhatsAppCallingLegacyRequest) SetSipAuthUsername(v string) {
	o.SipAuthUsername = &v
}

// GetSipAuthPassword returns the SipAuthPassword field value if set, zero value otherwise.
func (o *EnableWhatsAppCallingLegacyRequest) GetSipAuthPassword() string {
	if o == nil || IsNil(o.SipAuthPassword) {
		var ret string
		return ret
	}
	return *o.SipAuthPassword
}

// GetSipAuthPasswordOk returns a tuple with the SipAuthPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnableWhatsAppCallingLegacyRequest) GetSipAuthPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.SipAuthPassword) {
		return nil, false
	}
	return o.SipAuthPassword, true
}

// HasSipAuthPassword returns a boolean if a field has been set.
func (o *EnableWhatsAppCallingLegacyRequest) HasSipAuthPassword() bool {
	if o != nil && !IsNil(o.SipAuthPassword) {
		return true
	}

	return false
}

// SetSipAuthPassword gets a reference to the given string and assigns it to the SipAuthPassword field.
func (o *EnableWhatsAppCallingLegacyRequest) SetSipAuthPassword(v string) {
	o.SipAuthPassword = &v
}

// GetRecordingEnabled returns the RecordingEnabled field value if set, zero value otherwise.
func (o *EnableWhatsAppCallingLegacyRequest) GetRecordingEnabled() bool {
	if o == nil || IsNil(o.RecordingEnabled) {
		var ret bool
		return ret
	}
	return *o.RecordingEnabled
}

// GetRecordingEnabledOk returns a tuple with the RecordingEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnableWhatsAppCallingLegacyRequest) GetRecordingEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.RecordingEnabled) {
		return nil, false
	}
	return o.RecordingEnabled, true
}

// HasRecordingEnabled returns a boolean if a field has been set.
func (o *EnableWhatsAppCallingLegacyRequest) HasRecordingEnabled() bool {
	if o != nil && !IsNil(o.RecordingEnabled) {
		return true
	}

	return false
}

// SetRecordingEnabled gets a reference to the given bool and assigns it to the RecordingEnabled field.
func (o *EnableWhatsAppCallingLegacyRequest) SetRecordingEnabled(v bool) {
	o.RecordingEnabled = &v
}

// GetCallIconCountries returns the CallIconCountries field value if set, zero value otherwise.
func (o *EnableWhatsAppCallingLegacyRequest) GetCallIconCountries() []string {
	if o == nil || IsNil(o.CallIconCountries) {
		var ret []string
		return ret
	}
	return o.CallIconCountries
}

// GetCallIconCountriesOk returns a tuple with the CallIconCountries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnableWhatsAppCallingLegacyRequest) GetCallIconCountriesOk() ([]string, bool) {
	if o == nil || IsNil(o.CallIconCountries) {
		return nil, false
	}
	return o.CallIconCountries, true
}

// HasCallIconCountries returns a boolean if a field has been set.
func (o *EnableWhatsAppCallingLegacyRequest) HasCallIconCountries() bool {
	if o != nil && !IsNil(o.CallIconCountries) {
		return true
	}

	return false
}

// SetCallIconCountries gets a reference to the given []string and assigns it to the CallIconCountries field.
func (o *EnableWhatsAppCallingLegacyRequest) SetCallIconCountries(v []string) {
	o.CallIconCountries = v
}

func (o EnableWhatsAppCallingLegacyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnableWhatsAppCallingLegacyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	toSerialize["forwardTo"] = o.ForwardTo
	if !IsNil(o.SipAuthUsername) {
		toSerialize["sipAuthUsername"] = o.SipAuthUsername
	}
	if !IsNil(o.SipAuthPassword) {
		toSerialize["sipAuthPassword"] = o.SipAuthPassword
	}
	if !IsNil(o.RecordingEnabled) {
		toSerialize["recordingEnabled"] = o.RecordingEnabled
	}
	if !IsNil(o.CallIconCountries) {
		toSerialize["callIconCountries"] = o.CallIconCountries
	}
	return toSerialize, nil
}

func (o *EnableWhatsAppCallingLegacyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
		"forwardTo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnableWhatsAppCallingLegacyRequest := _EnableWhatsAppCallingLegacyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnableWhatsAppCallingLegacyRequest)

	if err != nil {
		return err
	}

	*o = EnableWhatsAppCallingLegacyRequest(varEnableWhatsAppCallingLegacyRequest)

	return err
}

type NullableEnableWhatsAppCallingLegacyRequest struct {
	value *EnableWhatsAppCallingLegacyRequest
	isSet bool
}

func (v NullableEnableWhatsAppCallingLegacyRequest) Get() *EnableWhatsAppCallingLegacyRequest {
	return v.value
}

func (v *NullableEnableWhatsAppCallingLegacyRequest) Set(val *EnableWhatsAppCallingLegacyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnableWhatsAppCallingLegacyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnableWhatsAppCallingLegacyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnableWhatsAppCallingLegacyRequest(val *EnableWhatsAppCallingLegacyRequest) *NullableEnableWhatsAppCallingLegacyRequest {
	return &NullableEnableWhatsAppCallingLegacyRequest{value: val, isSet: true}
}

func (v NullableEnableWhatsAppCallingLegacyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnableWhatsAppCallingLegacyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
