/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.36.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
	"time"
)

// checks if the CreateSipTrunk201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSipTrunk201Response{}

// CreateSipTrunk201Response struct for CreateSipTrunk201Response
type CreateSipTrunk201Response struct {
	Id              *string                                         `json:"id,omitempty"`
	Label           *string                                         `json:"label,omitempty"`
	SipHost         *string                                         `json:"sipHost,omitempty"`
	SipPort         *int32                                          `json:"sipPort,omitempty"`
	Transport       *string                                         `json:"transport,omitempty"`
	Termination     *ListSipTrunks200ResponseTrunksInnerTermination `json:"termination,omitempty"`
	NumbersAttached *int32                                          `json:"numbersAttached,omitempty"`
	CreatedAt       NullableTime                                    `json:"createdAt,omitempty"`
	// SIP digest password, shown only in this response.
	DigestPassword *string `json:"digestPassword,omitempty"`
}

// NewCreateSipTrunk201Response instantiates a new CreateSipTrunk201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSipTrunk201Response() *CreateSipTrunk201Response {
	this := CreateSipTrunk201Response{}
	return &this
}

// NewCreateSipTrunk201ResponseWithDefaults instantiates a new CreateSipTrunk201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSipTrunk201ResponseWithDefaults() *CreateSipTrunk201Response {
	this := CreateSipTrunk201Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateSipTrunk201Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSipTrunk201Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateSipTrunk201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateSipTrunk201Response) SetId(v string) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *CreateSipTrunk201Response) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSipTrunk201Response) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *CreateSipTrunk201Response) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *CreateSipTrunk201Response) SetLabel(v string) {
	o.Label = &v
}

// GetSipHost returns the SipHost field value if set, zero value otherwise.
func (o *CreateSipTrunk201Response) GetSipHost() string {
	if o == nil || IsNil(o.SipHost) {
		var ret string
		return ret
	}
	return *o.SipHost
}

// GetSipHostOk returns a tuple with the SipHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSipTrunk201Response) GetSipHostOk() (*string, bool) {
	if o == nil || IsNil(o.SipHost) {
		return nil, false
	}
	return o.SipHost, true
}

// HasSipHost returns a boolean if a field has been set.
func (o *CreateSipTrunk201Response) HasSipHost() bool {
	if o != nil && !IsNil(o.SipHost) {
		return true
	}

	return false
}

// SetSipHost gets a reference to the given string and assigns it to the SipHost field.
func (o *CreateSipTrunk201Response) SetSipHost(v string) {
	o.SipHost = &v
}

// GetSipPort returns the SipPort field value if set, zero value otherwise.
func (o *CreateSipTrunk201Response) GetSipPort() int32 {
	if o == nil || IsNil(o.SipPort) {
		var ret int32
		return ret
	}
	return *o.SipPort
}

// GetSipPortOk returns a tuple with the SipPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSipTrunk201Response) GetSipPortOk() (*int32, bool) {
	if o == nil || IsNil(o.SipPort) {
		return nil, false
	}
	return o.SipPort, true
}

// HasSipPort returns a boolean if a field has been set.
func (o *CreateSipTrunk201Response) HasSipPort() bool {
	if o != nil && !IsNil(o.SipPort) {
		return true
	}

	return false
}

// SetSipPort gets a reference to the given int32 and assigns it to the SipPort field.
func (o *CreateSipTrunk201Response) SetSipPort(v int32) {
	o.SipPort = &v
}

// GetTransport returns the Transport field value if set, zero value otherwise.
func (o *CreateSipTrunk201Response) GetTransport() string {
	if o == nil || IsNil(o.Transport) {
		var ret string
		return ret
	}
	return *o.Transport
}

// GetTransportOk returns a tuple with the Transport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSipTrunk201Response) GetTransportOk() (*string, bool) {
	if o == nil || IsNil(o.Transport) {
		return nil, false
	}
	return o.Transport, true
}

// HasTransport returns a boolean if a field has been set.
func (o *CreateSipTrunk201Response) HasTransport() bool {
	if o != nil && !IsNil(o.Transport) {
		return true
	}

	return false
}

// SetTransport gets a reference to the given string and assigns it to the Transport field.
func (o *CreateSipTrunk201Response) SetTransport(v string) {
	o.Transport = &v
}

// GetTermination returns the Termination field value if set, zero value otherwise.
func (o *CreateSipTrunk201Response) GetTermination() ListSipTrunks200ResponseTrunksInnerTermination {
	if o == nil || IsNil(o.Termination) {
		var ret ListSipTrunks200ResponseTrunksInnerTermination
		return ret
	}
	return *o.Termination
}

// GetTerminationOk returns a tuple with the Termination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSipTrunk201Response) GetTerminationOk() (*ListSipTrunks200ResponseTrunksInnerTermination, bool) {
	if o == nil || IsNil(o.Termination) {
		return nil, false
	}
	return o.Termination, true
}

// HasTermination returns a boolean if a field has been set.
func (o *CreateSipTrunk201Response) HasTermination() bool {
	if o != nil && !IsNil(o.Termination) {
		return true
	}

	return false
}

// SetTermination gets a reference to the given ListSipTrunks200ResponseTrunksInnerTermination and assigns it to the Termination field.
func (o *CreateSipTrunk201Response) SetTermination(v ListSipTrunks200ResponseTrunksInnerTermination) {
	o.Termination = &v
}

// GetNumbersAttached returns the NumbersAttached field value if set, zero value otherwise.
func (o *CreateSipTrunk201Response) GetNumbersAttached() int32 {
	if o == nil || IsNil(o.NumbersAttached) {
		var ret int32
		return ret
	}
	return *o.NumbersAttached
}

// GetNumbersAttachedOk returns a tuple with the NumbersAttached field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSipTrunk201Response) GetNumbersAttachedOk() (*int32, bool) {
	if o == nil || IsNil(o.NumbersAttached) {
		return nil, false
	}
	return o.NumbersAttached, true
}

// HasNumbersAttached returns a boolean if a field has been set.
func (o *CreateSipTrunk201Response) HasNumbersAttached() bool {
	if o != nil && !IsNil(o.NumbersAttached) {
		return true
	}

	return false
}

// SetNumbersAttached gets a reference to the given int32 and assigns it to the NumbersAttached field.
func (o *CreateSipTrunk201Response) SetNumbersAttached(v int32) {
	o.NumbersAttached = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateSipTrunk201Response) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateSipTrunk201Response) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CreateSipTrunk201Response) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *CreateSipTrunk201Response) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *CreateSipTrunk201Response) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *CreateSipTrunk201Response) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetDigestPassword returns the DigestPassword field value if set, zero value otherwise.
func (o *CreateSipTrunk201Response) GetDigestPassword() string {
	if o == nil || IsNil(o.DigestPassword) {
		var ret string
		return ret
	}
	return *o.DigestPassword
}

// GetDigestPasswordOk returns a tuple with the DigestPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSipTrunk201Response) GetDigestPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.DigestPassword) {
		return nil, false
	}
	return o.DigestPassword, true
}

// HasDigestPassword returns a boolean if a field has been set.
func (o *CreateSipTrunk201Response) HasDigestPassword() bool {
	if o != nil && !IsNil(o.DigestPassword) {
		return true
	}

	return false
}

// SetDigestPassword gets a reference to the given string and assigns it to the DigestPassword field.
func (o *CreateSipTrunk201Response) SetDigestPassword(v string) {
	o.DigestPassword = &v
}

func (o CreateSipTrunk201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSipTrunk201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.SipHost) {
		toSerialize["sipHost"] = o.SipHost
	}
	if !IsNil(o.SipPort) {
		toSerialize["sipPort"] = o.SipPort
	}
	if !IsNil(o.Transport) {
		toSerialize["transport"] = o.Transport
	}
	if !IsNil(o.Termination) {
		toSerialize["termination"] = o.Termination
	}
	if !IsNil(o.NumbersAttached) {
		toSerialize["numbersAttached"] = o.NumbersAttached
	}
	if o.CreatedAt.IsSet() {
		toSerialize["createdAt"] = o.CreatedAt.Get()
	}
	if !IsNil(o.DigestPassword) {
		toSerialize["digestPassword"] = o.DigestPassword
	}
	return toSerialize, nil
}

type NullableCreateSipTrunk201Response struct {
	value *CreateSipTrunk201Response
	isSet bool
}

func (v NullableCreateSipTrunk201Response) Get() *CreateSipTrunk201Response {
	return v.value
}

func (v *NullableCreateSipTrunk201Response) Set(val *CreateSipTrunk201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSipTrunk201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSipTrunk201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSipTrunk201Response(val *CreateSipTrunk201Response) *NullableCreateSipTrunk201Response {
	return &NullableCreateSipTrunk201Response{value: val, isSet: true}
}

func (v NullableCreateSipTrunk201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSipTrunk201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
