/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the CreatePost409ResponseDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePost409ResponseDetails{}

// CreatePost409ResponseDetails struct for CreatePost409ResponseDetails
type CreatePost409ResponseDetails struct {
	AccountId      *string `json:"accountId,omitempty"`
	Platform       *string `json:"platform,omitempty"`
	ExistingPostId *string `json:"existingPostId,omitempty"`
}

// NewCreatePost409ResponseDetails instantiates a new CreatePost409ResponseDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePost409ResponseDetails() *CreatePost409ResponseDetails {
	this := CreatePost409ResponseDetails{}
	return &this
}

// NewCreatePost409ResponseDetailsWithDefaults instantiates a new CreatePost409ResponseDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePost409ResponseDetailsWithDefaults() *CreatePost409ResponseDetails {
	this := CreatePost409ResponseDetails{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *CreatePost409ResponseDetails) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePost409ResponseDetails) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *CreatePost409ResponseDetails) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *CreatePost409ResponseDetails) SetAccountId(v string) {
	o.AccountId = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *CreatePost409ResponseDetails) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePost409ResponseDetails) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *CreatePost409ResponseDetails) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *CreatePost409ResponseDetails) SetPlatform(v string) {
	o.Platform = &v
}

// GetExistingPostId returns the ExistingPostId field value if set, zero value otherwise.
func (o *CreatePost409ResponseDetails) GetExistingPostId() string {
	if o == nil || IsNil(o.ExistingPostId) {
		var ret string
		return ret
	}
	return *o.ExistingPostId
}

// GetExistingPostIdOk returns a tuple with the ExistingPostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePost409ResponseDetails) GetExistingPostIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExistingPostId) {
		return nil, false
	}
	return o.ExistingPostId, true
}

// HasExistingPostId returns a boolean if a field has been set.
func (o *CreatePost409ResponseDetails) HasExistingPostId() bool {
	if o != nil && !IsNil(o.ExistingPostId) {
		return true
	}

	return false
}

// SetExistingPostId gets a reference to the given string and assigns it to the ExistingPostId field.
func (o *CreatePost409ResponseDetails) SetExistingPostId(v string) {
	o.ExistingPostId = &v
}

func (o CreatePost409ResponseDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePost409ResponseDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.ExistingPostId) {
		toSerialize["existingPostId"] = o.ExistingPostId
	}
	return toSerialize, nil
}

type NullableCreatePost409ResponseDetails struct {
	value *CreatePost409ResponseDetails
	isSet bool
}

func (v NullableCreatePost409ResponseDetails) Get() *CreatePost409ResponseDetails {
	return v.value
}

func (v *NullableCreatePost409ResponseDetails) Set(val *CreatePost409ResponseDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePost409ResponseDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePost409ResponseDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePost409ResponseDetails(val *CreatePost409ResponseDetails) *NullableCreatePost409ResponseDetails {
	return &NullableCreatePost409ResponseDetails{value: val, isSet: true}
}

func (v NullableCreatePost409ResponseDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePost409ResponseDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
