/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.20.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BulkCreateContactsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkCreateContactsRequest{}

// BulkCreateContactsRequest struct for BulkCreateContactsRequest
type BulkCreateContactsRequest struct {
	ProfileId string `json:"profileId"`
	// Required when contacts carry channel data (platformIdentifier or a row-level accountId). Omit for a plain CRM import with no channels.
	AccountId *string `json:"accountId,omitempty"`
	// Ignored when accountId is set: the platform is derived from the resolved account. Only relevant to disambiguate accountId lookup; a mismatch 404s.
	Platform *string                                  `json:"platform,omitempty"`
	Contacts []BulkCreateContactsRequestContactsInner `json:"contacts"`
}

type _BulkCreateContactsRequest BulkCreateContactsRequest

// NewBulkCreateContactsRequest instantiates a new BulkCreateContactsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkCreateContactsRequest(profileId string, contacts []BulkCreateContactsRequestContactsInner) *BulkCreateContactsRequest {
	this := BulkCreateContactsRequest{}
	this.ProfileId = profileId
	this.Contacts = contacts
	return &this
}

// NewBulkCreateContactsRequestWithDefaults instantiates a new BulkCreateContactsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkCreateContactsRequestWithDefaults() *BulkCreateContactsRequest {
	this := BulkCreateContactsRequest{}
	return &this
}

// GetProfileId returns the ProfileId field value
func (o *BulkCreateContactsRequest) GetProfileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value
// and a boolean to check if the value has been set.
func (o *BulkCreateContactsRequest) GetProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfileId, true
}

// SetProfileId sets field value
func (o *BulkCreateContactsRequest) SetProfileId(v string) {
	o.ProfileId = v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *BulkCreateContactsRequest) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreateContactsRequest) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *BulkCreateContactsRequest) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *BulkCreateContactsRequest) SetAccountId(v string) {
	o.AccountId = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *BulkCreateContactsRequest) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreateContactsRequest) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *BulkCreateContactsRequest) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *BulkCreateContactsRequest) SetPlatform(v string) {
	o.Platform = &v
}

// GetContacts returns the Contacts field value
func (o *BulkCreateContactsRequest) GetContacts() []BulkCreateContactsRequestContactsInner {
	if o == nil {
		var ret []BulkCreateContactsRequestContactsInner
		return ret
	}

	return o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value
// and a boolean to check if the value has been set.
func (o *BulkCreateContactsRequest) GetContactsOk() ([]BulkCreateContactsRequestContactsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contacts, true
}

// SetContacts sets field value
func (o *BulkCreateContactsRequest) SetContacts(v []BulkCreateContactsRequestContactsInner) {
	o.Contacts = v
}

func (o BulkCreateContactsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkCreateContactsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["profileId"] = o.ProfileId
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	toSerialize["contacts"] = o.Contacts
	return toSerialize, nil
}

func (o *BulkCreateContactsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"profileId",
		"contacts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkCreateContactsRequest := _BulkCreateContactsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkCreateContactsRequest)

	if err != nil {
		return err
	}

	*o = BulkCreateContactsRequest(varBulkCreateContactsRequest)

	return err
}

type NullableBulkCreateContactsRequest struct {
	value *BulkCreateContactsRequest
	isSet bool
}

func (v NullableBulkCreateContactsRequest) Get() *BulkCreateContactsRequest {
	return v.value
}

func (v *NullableBulkCreateContactsRequest) Set(val *BulkCreateContactsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCreateContactsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCreateContactsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCreateContactsRequest(val *BulkCreateContactsRequest) *NullableBulkCreateContactsRequest {
	return &NullableBulkCreateContactsRequest{value: val, isSet: true}
}

func (v NullableBulkCreateContactsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCreateContactsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
