/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
	"time"
)

// checks if the Post type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Post{}

// Post struct for Post
type Post struct {
	Id     *string     `json:"_id,omitempty"`
	UserId *PostUserId `json:"userId,omitempty"`
	// YouTube: title must be ≤ 100 characters.
	Title        *string          `json:"title,omitempty"`
	Content      *string          `json:"content,omitempty"`
	MediaItems   []MediaItem      `json:"mediaItems,omitempty"`
	Platforms    []PlatformTarget `json:"platforms,omitempty"`
	ScheduledFor *time.Time       `json:"scheduledFor,omitempty"`
	Timezone     *string          `json:"timezone,omitempty"`
	Status       *string          `json:"status,omitempty"`
	// YouTube constraints: each tag max 100 chars, combined max 500 chars, duplicates removed.
	Tags     []string `json:"tags,omitempty"`
	Hashtags []string `json:"hashtags,omitempty"`
	// Stored for reference only. This field does NOT automatically create @mentions when publishing. For LinkedIn @mentions, use the /v1/accounts/{accountId}/linkedin-mentions endpoint to resolve profile URLs to URNs, then embed the returned mentionFormat directly in the post content field.
	Mentions   []string               `json:"mentions,omitempty"`
	Visibility *string                `json:"visibility,omitempty"`
	Metadata   map[string]interface{} `json:"metadata,omitempty"`
	Recycling  *RecyclingState        `json:"recycling,omitempty"`
	// ID of the original post if this post was created via recycling
	RecycledFromPostId *string `json:"recycledFromPostId,omitempty"`
	// Profile ID if the post was scheduled via the queue
	QueuedFromProfile *string `json:"queuedFromProfile,omitempty"`
	// Queue ID if the post was scheduled via a specific queue
	QueueId   *string    `json:"queueId,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewPost instantiates a new Post object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPost() *Post {
	this := Post{}
	return &this
}

// NewPostWithDefaults instantiates a new Post object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostWithDefaults() *Post {
	this := Post{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Post) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Post) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Post) SetId(v string) {
	o.Id = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *Post) GetUserId() PostUserId {
	if o == nil || IsNil(o.UserId) {
		var ret PostUserId
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetUserIdOk() (*PostUserId, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *Post) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given PostUserId and assigns it to the UserId field.
func (o *Post) SetUserId(v PostUserId) {
	o.UserId = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Post) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Post) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Post) SetTitle(v string) {
	o.Title = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *Post) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *Post) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *Post) SetContent(v string) {
	o.Content = &v
}

// GetMediaItems returns the MediaItems field value if set, zero value otherwise.
func (o *Post) GetMediaItems() []MediaItem {
	if o == nil || IsNil(o.MediaItems) {
		var ret []MediaItem
		return ret
	}
	return o.MediaItems
}

// GetMediaItemsOk returns a tuple with the MediaItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetMediaItemsOk() ([]MediaItem, bool) {
	if o == nil || IsNil(o.MediaItems) {
		return nil, false
	}
	return o.MediaItems, true
}

// HasMediaItems returns a boolean if a field has been set.
func (o *Post) HasMediaItems() bool {
	if o != nil && !IsNil(o.MediaItems) {
		return true
	}

	return false
}

// SetMediaItems gets a reference to the given []MediaItem and assigns it to the MediaItems field.
func (o *Post) SetMediaItems(v []MediaItem) {
	o.MediaItems = v
}

// GetPlatforms returns the Platforms field value if set, zero value otherwise.
func (o *Post) GetPlatforms() []PlatformTarget {
	if o == nil || IsNil(o.Platforms) {
		var ret []PlatformTarget
		return ret
	}
	return o.Platforms
}

// GetPlatformsOk returns a tuple with the Platforms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetPlatformsOk() ([]PlatformTarget, bool) {
	if o == nil || IsNil(o.Platforms) {
		return nil, false
	}
	return o.Platforms, true
}

// HasPlatforms returns a boolean if a field has been set.
func (o *Post) HasPlatforms() bool {
	if o != nil && !IsNil(o.Platforms) {
		return true
	}

	return false
}

// SetPlatforms gets a reference to the given []PlatformTarget and assigns it to the Platforms field.
func (o *Post) SetPlatforms(v []PlatformTarget) {
	o.Platforms = v
}

// GetScheduledFor returns the ScheduledFor field value if set, zero value otherwise.
func (o *Post) GetScheduledFor() time.Time {
	if o == nil || IsNil(o.ScheduledFor) {
		var ret time.Time
		return ret
	}
	return *o.ScheduledFor
}

// GetScheduledForOk returns a tuple with the ScheduledFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetScheduledForOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ScheduledFor) {
		return nil, false
	}
	return o.ScheduledFor, true
}

// HasScheduledFor returns a boolean if a field has been set.
func (o *Post) HasScheduledFor() bool {
	if o != nil && !IsNil(o.ScheduledFor) {
		return true
	}

	return false
}

// SetScheduledFor gets a reference to the given time.Time and assigns it to the ScheduledFor field.
func (o *Post) SetScheduledFor(v time.Time) {
	o.ScheduledFor = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *Post) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *Post) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *Post) SetTimezone(v string) {
	o.Timezone = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Post) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Post) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Post) SetStatus(v string) {
	o.Status = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Post) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Post) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Post) SetTags(v []string) {
	o.Tags = v
}

// GetHashtags returns the Hashtags field value if set, zero value otherwise.
func (o *Post) GetHashtags() []string {
	if o == nil || IsNil(o.Hashtags) {
		var ret []string
		return ret
	}
	return o.Hashtags
}

// GetHashtagsOk returns a tuple with the Hashtags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetHashtagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Hashtags) {
		return nil, false
	}
	return o.Hashtags, true
}

// HasHashtags returns a boolean if a field has been set.
func (o *Post) HasHashtags() bool {
	if o != nil && !IsNil(o.Hashtags) {
		return true
	}

	return false
}

// SetHashtags gets a reference to the given []string and assigns it to the Hashtags field.
func (o *Post) SetHashtags(v []string) {
	o.Hashtags = v
}

// GetMentions returns the Mentions field value if set, zero value otherwise.
func (o *Post) GetMentions() []string {
	if o == nil || IsNil(o.Mentions) {
		var ret []string
		return ret
	}
	return o.Mentions
}

// GetMentionsOk returns a tuple with the Mentions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetMentionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Mentions) {
		return nil, false
	}
	return o.Mentions, true
}

// HasMentions returns a boolean if a field has been set.
func (o *Post) HasMentions() bool {
	if o != nil && !IsNil(o.Mentions) {
		return true
	}

	return false
}

// SetMentions gets a reference to the given []string and assigns it to the Mentions field.
func (o *Post) SetMentions(v []string) {
	o.Mentions = v
}

// GetVisibility returns the Visibility field value if set, zero value otherwise.
func (o *Post) GetVisibility() string {
	if o == nil || IsNil(o.Visibility) {
		var ret string
		return ret
	}
	return *o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetVisibilityOk() (*string, bool) {
	if o == nil || IsNil(o.Visibility) {
		return nil, false
	}
	return o.Visibility, true
}

// HasVisibility returns a boolean if a field has been set.
func (o *Post) HasVisibility() bool {
	if o != nil && !IsNil(o.Visibility) {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given string and assigns it to the Visibility field.
func (o *Post) SetVisibility(v string) {
	o.Visibility = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Post) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Post) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *Post) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetRecycling returns the Recycling field value if set, zero value otherwise.
func (o *Post) GetRecycling() RecyclingState {
	if o == nil || IsNil(o.Recycling) {
		var ret RecyclingState
		return ret
	}
	return *o.Recycling
}

// GetRecyclingOk returns a tuple with the Recycling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetRecyclingOk() (*RecyclingState, bool) {
	if o == nil || IsNil(o.Recycling) {
		return nil, false
	}
	return o.Recycling, true
}

// HasRecycling returns a boolean if a field has been set.
func (o *Post) HasRecycling() bool {
	if o != nil && !IsNil(o.Recycling) {
		return true
	}

	return false
}

// SetRecycling gets a reference to the given RecyclingState and assigns it to the Recycling field.
func (o *Post) SetRecycling(v RecyclingState) {
	o.Recycling = &v
}

// GetRecycledFromPostId returns the RecycledFromPostId field value if set, zero value otherwise.
func (o *Post) GetRecycledFromPostId() string {
	if o == nil || IsNil(o.RecycledFromPostId) {
		var ret string
		return ret
	}
	return *o.RecycledFromPostId
}

// GetRecycledFromPostIdOk returns a tuple with the RecycledFromPostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetRecycledFromPostIdOk() (*string, bool) {
	if o == nil || IsNil(o.RecycledFromPostId) {
		return nil, false
	}
	return o.RecycledFromPostId, true
}

// HasRecycledFromPostId returns a boolean if a field has been set.
func (o *Post) HasRecycledFromPostId() bool {
	if o != nil && !IsNil(o.RecycledFromPostId) {
		return true
	}

	return false
}

// SetRecycledFromPostId gets a reference to the given string and assigns it to the RecycledFromPostId field.
func (o *Post) SetRecycledFromPostId(v string) {
	o.RecycledFromPostId = &v
}

// GetQueuedFromProfile returns the QueuedFromProfile field value if set, zero value otherwise.
func (o *Post) GetQueuedFromProfile() string {
	if o == nil || IsNil(o.QueuedFromProfile) {
		var ret string
		return ret
	}
	return *o.QueuedFromProfile
}

// GetQueuedFromProfileOk returns a tuple with the QueuedFromProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetQueuedFromProfileOk() (*string, bool) {
	if o == nil || IsNil(o.QueuedFromProfile) {
		return nil, false
	}
	return o.QueuedFromProfile, true
}

// HasQueuedFromProfile returns a boolean if a field has been set.
func (o *Post) HasQueuedFromProfile() bool {
	if o != nil && !IsNil(o.QueuedFromProfile) {
		return true
	}

	return false
}

// SetQueuedFromProfile gets a reference to the given string and assigns it to the QueuedFromProfile field.
func (o *Post) SetQueuedFromProfile(v string) {
	o.QueuedFromProfile = &v
}

// GetQueueId returns the QueueId field value if set, zero value otherwise.
func (o *Post) GetQueueId() string {
	if o == nil || IsNil(o.QueueId) {
		var ret string
		return ret
	}
	return *o.QueueId
}

// GetQueueIdOk returns a tuple with the QueueId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetQueueIdOk() (*string, bool) {
	if o == nil || IsNil(o.QueueId) {
		return nil, false
	}
	return o.QueueId, true
}

// HasQueueId returns a boolean if a field has been set.
func (o *Post) HasQueueId() bool {
	if o != nil && !IsNil(o.QueueId) {
		return true
	}

	return false
}

// SetQueueId gets a reference to the given string and assigns it to the QueueId field.
func (o *Post) SetQueueId(v string) {
	o.QueueId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Post) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Post) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Post) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Post) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Post) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Post) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Post) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o Post) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Post) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["_id"] = o.Id
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.MediaItems) {
		toSerialize["mediaItems"] = o.MediaItems
	}
	if !IsNil(o.Platforms) {
		toSerialize["platforms"] = o.Platforms
	}
	if !IsNil(o.ScheduledFor) {
		toSerialize["scheduledFor"] = o.ScheduledFor
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Hashtags) {
		toSerialize["hashtags"] = o.Hashtags
	}
	if !IsNil(o.Mentions) {
		toSerialize["mentions"] = o.Mentions
	}
	if !IsNil(o.Visibility) {
		toSerialize["visibility"] = o.Visibility
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Recycling) {
		toSerialize["recycling"] = o.Recycling
	}
	if !IsNil(o.RecycledFromPostId) {
		toSerialize["recycledFromPostId"] = o.RecycledFromPostId
	}
	if !IsNil(o.QueuedFromProfile) {
		toSerialize["queuedFromProfile"] = o.QueuedFromProfile
	}
	if !IsNil(o.QueueId) {
		toSerialize["queueId"] = o.QueueId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullablePost struct {
	value *Post
	isSet bool
}

func (v NullablePost) Get() *Post {
	return v.value
}

func (v *NullablePost) Set(val *Post) {
	v.value = val
	v.isSet = true
}

func (v NullablePost) IsSet() bool {
	return v.isSet
}

func (v *NullablePost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePost(val *Post) *NullablePost {
	return &NullablePost{value: val, isSet: true}
}

func (v NullablePost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
