/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.85.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the ErrorResponseDetailsCreatedObjectsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorResponseDetailsCreatedObjectsInner{}

// ErrorResponseDetailsCreatedObjectsInner struct for ErrorResponseDetailsCreatedObjectsInner
type ErrorResponseDetailsCreatedObjectsInner struct {
	Type *string `json:"type,omitempty"`
	// Meta object id; for `image` the image hash.
	Id *string `json:"id,omitempty"`
	// `deleted`: Zernio deleted it. `left_behind`: Meta refused the delete, so it still exists. `kept`: deliberately not deleted (image hashes are shared by every upload of the same file).
	Cleanup *string `json:"cleanup,omitempty"`
}

// NewErrorResponseDetailsCreatedObjectsInner instantiates a new ErrorResponseDetailsCreatedObjectsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorResponseDetailsCreatedObjectsInner() *ErrorResponseDetailsCreatedObjectsInner {
	this := ErrorResponseDetailsCreatedObjectsInner{}
	return &this
}

// NewErrorResponseDetailsCreatedObjectsInnerWithDefaults instantiates a new ErrorResponseDetailsCreatedObjectsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorResponseDetailsCreatedObjectsInnerWithDefaults() *ErrorResponseDetailsCreatedObjectsInner {
	this := ErrorResponseDetailsCreatedObjectsInner{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ErrorResponseDetailsCreatedObjectsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorResponseDetailsCreatedObjectsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ErrorResponseDetailsCreatedObjectsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ErrorResponseDetailsCreatedObjectsInner) SetType(v string) {
	o.Type = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ErrorResponseDetailsCreatedObjectsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorResponseDetailsCreatedObjectsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ErrorResponseDetailsCreatedObjectsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ErrorResponseDetailsCreatedObjectsInner) SetId(v string) {
	o.Id = &v
}

// GetCleanup returns the Cleanup field value if set, zero value otherwise.
func (o *ErrorResponseDetailsCreatedObjectsInner) GetCleanup() string {
	if o == nil || IsNil(o.Cleanup) {
		var ret string
		return ret
	}
	return *o.Cleanup
}

// GetCleanupOk returns a tuple with the Cleanup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorResponseDetailsCreatedObjectsInner) GetCleanupOk() (*string, bool) {
	if o == nil || IsNil(o.Cleanup) {
		return nil, false
	}
	return o.Cleanup, true
}

// HasCleanup returns a boolean if a field has been set.
func (o *ErrorResponseDetailsCreatedObjectsInner) HasCleanup() bool {
	if o != nil && !IsNil(o.Cleanup) {
		return true
	}

	return false
}

// SetCleanup gets a reference to the given string and assigns it to the Cleanup field.
func (o *ErrorResponseDetailsCreatedObjectsInner) SetCleanup(v string) {
	o.Cleanup = &v
}

func (o ErrorResponseDetailsCreatedObjectsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorResponseDetailsCreatedObjectsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Cleanup) {
		toSerialize["cleanup"] = o.Cleanup
	}
	return toSerialize, nil
}

type NullableErrorResponseDetailsCreatedObjectsInner struct {
	value *ErrorResponseDetailsCreatedObjectsInner
	isSet bool
}

func (v NullableErrorResponseDetailsCreatedObjectsInner) Get() *ErrorResponseDetailsCreatedObjectsInner {
	return v.value
}

func (v *NullableErrorResponseDetailsCreatedObjectsInner) Set(val *ErrorResponseDetailsCreatedObjectsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorResponseDetailsCreatedObjectsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorResponseDetailsCreatedObjectsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorResponseDetailsCreatedObjectsInner(val *ErrorResponseDetailsCreatedObjectsInner) *NullableErrorResponseDetailsCreatedObjectsInner {
	return &NullableErrorResponseDetailsCreatedObjectsInner{value: val, isSet: true}
}

func (v NullableErrorResponseDetailsCreatedObjectsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorResponseDetailsCreatedObjectsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
