/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the GetPhoneNumberKycForm200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPhoneNumberKycForm200Response{}

// GetPhoneNumberKycForm200Response struct for GetPhoneNumberKycForm200Response
type GetPhoneNumberKycForm200Response struct {
	Country    *string                                       `json:"country,omitempty"`
	NumberType *string                                       `json:"numberType,omitempty"`
	Fields     []GetPhoneNumberKycForm200ResponseFieldsInner `json:"fields,omitempty"`
	Reusable   *GetPhoneNumberKycForm200ResponseReusable     `json:"reusable,omitempty"`
}

// NewGetPhoneNumberKycForm200Response instantiates a new GetPhoneNumberKycForm200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPhoneNumberKycForm200Response() *GetPhoneNumberKycForm200Response {
	this := GetPhoneNumberKycForm200Response{}
	return &this
}

// NewGetPhoneNumberKycForm200ResponseWithDefaults instantiates a new GetPhoneNumberKycForm200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPhoneNumberKycForm200ResponseWithDefaults() *GetPhoneNumberKycForm200Response {
	this := GetPhoneNumberKycForm200Response{}
	return &this
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *GetPhoneNumberKycForm200Response) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPhoneNumberKycForm200Response) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *GetPhoneNumberKycForm200Response) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *GetPhoneNumberKycForm200Response) SetCountry(v string) {
	o.Country = &v
}

// GetNumberType returns the NumberType field value if set, zero value otherwise.
func (o *GetPhoneNumberKycForm200Response) GetNumberType() string {
	if o == nil || IsNil(o.NumberType) {
		var ret string
		return ret
	}
	return *o.NumberType
}

// GetNumberTypeOk returns a tuple with the NumberType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPhoneNumberKycForm200Response) GetNumberTypeOk() (*string, bool) {
	if o == nil || IsNil(o.NumberType) {
		return nil, false
	}
	return o.NumberType, true
}

// HasNumberType returns a boolean if a field has been set.
func (o *GetPhoneNumberKycForm200Response) HasNumberType() bool {
	if o != nil && !IsNil(o.NumberType) {
		return true
	}

	return false
}

// SetNumberType gets a reference to the given string and assigns it to the NumberType field.
func (o *GetPhoneNumberKycForm200Response) SetNumberType(v string) {
	o.NumberType = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *GetPhoneNumberKycForm200Response) GetFields() []GetPhoneNumberKycForm200ResponseFieldsInner {
	if o == nil || IsNil(o.Fields) {
		var ret []GetPhoneNumberKycForm200ResponseFieldsInner
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPhoneNumberKycForm200Response) GetFieldsOk() ([]GetPhoneNumberKycForm200ResponseFieldsInner, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *GetPhoneNumberKycForm200Response) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []GetPhoneNumberKycForm200ResponseFieldsInner and assigns it to the Fields field.
func (o *GetPhoneNumberKycForm200Response) SetFields(v []GetPhoneNumberKycForm200ResponseFieldsInner) {
	o.Fields = v
}

// GetReusable returns the Reusable field value if set, zero value otherwise.
func (o *GetPhoneNumberKycForm200Response) GetReusable() GetPhoneNumberKycForm200ResponseReusable {
	if o == nil || IsNil(o.Reusable) {
		var ret GetPhoneNumberKycForm200ResponseReusable
		return ret
	}
	return *o.Reusable
}

// GetReusableOk returns a tuple with the Reusable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPhoneNumberKycForm200Response) GetReusableOk() (*GetPhoneNumberKycForm200ResponseReusable, bool) {
	if o == nil || IsNil(o.Reusable) {
		return nil, false
	}
	return o.Reusable, true
}

// HasReusable returns a boolean if a field has been set.
func (o *GetPhoneNumberKycForm200Response) HasReusable() bool {
	if o != nil && !IsNil(o.Reusable) {
		return true
	}

	return false
}

// SetReusable gets a reference to the given GetPhoneNumberKycForm200ResponseReusable and assigns it to the Reusable field.
func (o *GetPhoneNumberKycForm200Response) SetReusable(v GetPhoneNumberKycForm200ResponseReusable) {
	o.Reusable = &v
}

func (o GetPhoneNumberKycForm200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPhoneNumberKycForm200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.NumberType) {
		toSerialize["numberType"] = o.NumberType
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Reusable) {
		toSerialize["reusable"] = o.Reusable
	}
	return toSerialize, nil
}

type NullableGetPhoneNumberKycForm200Response struct {
	value *GetPhoneNumberKycForm200Response
	isSet bool
}

func (v NullableGetPhoneNumberKycForm200Response) Get() *GetPhoneNumberKycForm200Response {
	return v.value
}

func (v *NullableGetPhoneNumberKycForm200Response) Set(val *GetPhoneNumberKycForm200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPhoneNumberKycForm200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPhoneNumberKycForm200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPhoneNumberKycForm200Response(val *GetPhoneNumberKycForm200Response) *NullableGetPhoneNumberKycForm200Response {
	return &NullableGetPhoneNumberKycForm200Response{value: val, isSet: true}
}

func (v NullableGetPhoneNumberKycForm200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPhoneNumberKycForm200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
