/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the GetInboxConversationAnalytics200ResponseBySourceInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInboxConversationAnalytics200ResponseBySourceInner{}

// GetInboxConversationAnalytics200ResponseBySourceInner struct for GetInboxConversationAnalytics200ResponseBySourceInner
type GetInboxConversationAnalytics200ResponseBySourceInner struct {
	// (unspecified) for legacy rows with no metadata.source
	Source *string `json:"source,omitempty"`
	Count  *int32  `json:"count,omitempty"`
}

// NewGetInboxConversationAnalytics200ResponseBySourceInner instantiates a new GetInboxConversationAnalytics200ResponseBySourceInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInboxConversationAnalytics200ResponseBySourceInner() *GetInboxConversationAnalytics200ResponseBySourceInner {
	this := GetInboxConversationAnalytics200ResponseBySourceInner{}
	return &this
}

// NewGetInboxConversationAnalytics200ResponseBySourceInnerWithDefaults instantiates a new GetInboxConversationAnalytics200ResponseBySourceInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInboxConversationAnalytics200ResponseBySourceInnerWithDefaults() *GetInboxConversationAnalytics200ResponseBySourceInner {
	this := GetInboxConversationAnalytics200ResponseBySourceInner{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *GetInboxConversationAnalytics200ResponseBySourceInner) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInboxConversationAnalytics200ResponseBySourceInner) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *GetInboxConversationAnalytics200ResponseBySourceInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *GetInboxConversationAnalytics200ResponseBySourceInner) SetSource(v string) {
	o.Source = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetInboxConversationAnalytics200ResponseBySourceInner) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInboxConversationAnalytics200ResponseBySourceInner) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetInboxConversationAnalytics200ResponseBySourceInner) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GetInboxConversationAnalytics200ResponseBySourceInner) SetCount(v int32) {
	o.Count = &v
}

func (o GetInboxConversationAnalytics200ResponseBySourceInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInboxConversationAnalytics200ResponseBySourceInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableGetInboxConversationAnalytics200ResponseBySourceInner struct {
	value *GetInboxConversationAnalytics200ResponseBySourceInner
	isSet bool
}

func (v NullableGetInboxConversationAnalytics200ResponseBySourceInner) Get() *GetInboxConversationAnalytics200ResponseBySourceInner {
	return v.value
}

func (v *NullableGetInboxConversationAnalytics200ResponseBySourceInner) Set(val *GetInboxConversationAnalytics200ResponseBySourceInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInboxConversationAnalytics200ResponseBySourceInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInboxConversationAnalytics200ResponseBySourceInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInboxConversationAnalytics200ResponseBySourceInner(val *GetInboxConversationAnalytics200ResponseBySourceInner) *NullableGetInboxConversationAnalytics200ResponseBySourceInner {
	return &NullableGetInboxConversationAnalytics200ResponseBySourceInner{value: val, isSet: true}
}

func (v NullableGetInboxConversationAnalytics200ResponseBySourceInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInboxConversationAnalytics200ResponseBySourceInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
