/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.32.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateStandaloneAdRequestSitelinksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateStandaloneAdRequestSitelinksInner{}

// CreateStandaloneAdRequestSitelinksInner struct for CreateStandaloneAdRequestSitelinksInner
type CreateStandaloneAdRequestSitelinksInner struct {
	// The clickable link text shown under the ad. 25-char cap comes from Google.
	Text string `json:"text"`
	// Final URL the sitelink navigates to.
	LinkUrl string `json:"linkUrl"`
	// First description line under the link text (optional). 35-char cap.
	Description1 *string `json:"description1,omitempty"`
	// Second description line (optional; usually paired with description1).
	Description2 *string `json:"description2,omitempty"`
}

type _CreateStandaloneAdRequestSitelinksInner CreateStandaloneAdRequestSitelinksInner

// NewCreateStandaloneAdRequestSitelinksInner instantiates a new CreateStandaloneAdRequestSitelinksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStandaloneAdRequestSitelinksInner(text string, linkUrl string) *CreateStandaloneAdRequestSitelinksInner {
	this := CreateStandaloneAdRequestSitelinksInner{}
	this.Text = text
	this.LinkUrl = linkUrl
	return &this
}

// NewCreateStandaloneAdRequestSitelinksInnerWithDefaults instantiates a new CreateStandaloneAdRequestSitelinksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStandaloneAdRequestSitelinksInnerWithDefaults() *CreateStandaloneAdRequestSitelinksInner {
	this := CreateStandaloneAdRequestSitelinksInner{}
	return &this
}

// GetText returns the Text field value
func (o *CreateStandaloneAdRequestSitelinksInner) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestSitelinksInner) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *CreateStandaloneAdRequestSitelinksInner) SetText(v string) {
	o.Text = v
}

// GetLinkUrl returns the LinkUrl field value
func (o *CreateStandaloneAdRequestSitelinksInner) GetLinkUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LinkUrl
}

// GetLinkUrlOk returns a tuple with the LinkUrl field value
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestSitelinksInner) GetLinkUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LinkUrl, true
}

// SetLinkUrl sets field value
func (o *CreateStandaloneAdRequestSitelinksInner) SetLinkUrl(v string) {
	o.LinkUrl = v
}

// GetDescription1 returns the Description1 field value if set, zero value otherwise.
func (o *CreateStandaloneAdRequestSitelinksInner) GetDescription1() string {
	if o == nil || IsNil(o.Description1) {
		var ret string
		return ret
	}
	return *o.Description1
}

// GetDescription1Ok returns a tuple with the Description1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestSitelinksInner) GetDescription1Ok() (*string, bool) {
	if o == nil || IsNil(o.Description1) {
		return nil, false
	}
	return o.Description1, true
}

// HasDescription1 returns a boolean if a field has been set.
func (o *CreateStandaloneAdRequestSitelinksInner) HasDescription1() bool {
	if o != nil && !IsNil(o.Description1) {
		return true
	}

	return false
}

// SetDescription1 gets a reference to the given string and assigns it to the Description1 field.
func (o *CreateStandaloneAdRequestSitelinksInner) SetDescription1(v string) {
	o.Description1 = &v
}

// GetDescription2 returns the Description2 field value if set, zero value otherwise.
func (o *CreateStandaloneAdRequestSitelinksInner) GetDescription2() string {
	if o == nil || IsNil(o.Description2) {
		var ret string
		return ret
	}
	return *o.Description2
}

// GetDescription2Ok returns a tuple with the Description2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStandaloneAdRequestSitelinksInner) GetDescription2Ok() (*string, bool) {
	if o == nil || IsNil(o.Description2) {
		return nil, false
	}
	return o.Description2, true
}

// HasDescription2 returns a boolean if a field has been set.
func (o *CreateStandaloneAdRequestSitelinksInner) HasDescription2() bool {
	if o != nil && !IsNil(o.Description2) {
		return true
	}

	return false
}

// SetDescription2 gets a reference to the given string and assigns it to the Description2 field.
func (o *CreateStandaloneAdRequestSitelinksInner) SetDescription2(v string) {
	o.Description2 = &v
}

func (o CreateStandaloneAdRequestSitelinksInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateStandaloneAdRequestSitelinksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["linkUrl"] = o.LinkUrl
	if !IsNil(o.Description1) {
		toSerialize["description1"] = o.Description1
	}
	if !IsNil(o.Description2) {
		toSerialize["description2"] = o.Description2
	}
	return toSerialize, nil
}

func (o *CreateStandaloneAdRequestSitelinksInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"linkUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateStandaloneAdRequestSitelinksInner := _CreateStandaloneAdRequestSitelinksInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateStandaloneAdRequestSitelinksInner)

	if err != nil {
		return err
	}

	*o = CreateStandaloneAdRequestSitelinksInner(varCreateStandaloneAdRequestSitelinksInner)

	return err
}

type NullableCreateStandaloneAdRequestSitelinksInner struct {
	value *CreateStandaloneAdRequestSitelinksInner
	isSet bool
}

func (v NullableCreateStandaloneAdRequestSitelinksInner) Get() *CreateStandaloneAdRequestSitelinksInner {
	return v.value
}

func (v *NullableCreateStandaloneAdRequestSitelinksInner) Set(val *CreateStandaloneAdRequestSitelinksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStandaloneAdRequestSitelinksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStandaloneAdRequestSitelinksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStandaloneAdRequestSitelinksInner(val *CreateStandaloneAdRequestSitelinksInner) *NullableCreateStandaloneAdRequestSitelinksInner {
	return &NullableCreateStandaloneAdRequestSitelinksInner{value: val, isSet: true}
}

func (v NullableCreateStandaloneAdRequestSitelinksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStandaloneAdRequestSitelinksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
