/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the GetGmbAttributeMetadata200ResponseAttributeMetadataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGmbAttributeMetadata200ResponseAttributeMetadataInner{}

// GetGmbAttributeMetadata200ResponseAttributeMetadataInner struct for GetGmbAttributeMetadata200ResponseAttributeMetadataInner
type GetGmbAttributeMetadata200ResponseAttributeMetadataInner struct {
	// Resource name of the attribute (e.g. \"attributes/has_delivery\").
	Parent *string `json:"parent,omitempty"`
	// Value type (e.g. BOOL, ENUM, URL, REPEATED_ENUM).
	ValueType *string `json:"valueType,omitempty"`
	// Localized human-readable attribute name.
	DisplayName *string `json:"displayName,omitempty"`
	// Display name of the attribute group.
	GroupDisplayName *string `json:"groupDisplayName,omitempty"`
	// True if multiple values can be set simultaneously.
	Repeatable *bool `json:"repeatable,omitempty"`
	// True if this attribute should no longer be used.
	Deprecated *bool `json:"deprecated,omitempty"`
	// Possible enum values (for ENUM / REPEATED_ENUM types).
	ValueMetadata []GetGmbAttributeMetadata200ResponseAttributeMetadataInnerValueMetadataInner `json:"valueMetadata,omitempty"`
}

// NewGetGmbAttributeMetadata200ResponseAttributeMetadataInner instantiates a new GetGmbAttributeMetadata200ResponseAttributeMetadataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGmbAttributeMetadata200ResponseAttributeMetadataInner() *GetGmbAttributeMetadata200ResponseAttributeMetadataInner {
	this := GetGmbAttributeMetadata200ResponseAttributeMetadataInner{}
	return &this
}

// NewGetGmbAttributeMetadata200ResponseAttributeMetadataInnerWithDefaults instantiates a new GetGmbAttributeMetadata200ResponseAttributeMetadataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGmbAttributeMetadata200ResponseAttributeMetadataInnerWithDefaults() *GetGmbAttributeMetadata200ResponseAttributeMetadataInner {
	this := GetGmbAttributeMetadata200ResponseAttributeMetadataInner{}
	return &this
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetParent() string {
	if o == nil || IsNil(o.Parent) {
		var ret string
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetParentOk() (*string, bool) {
	if o == nil || IsNil(o.Parent) {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) HasParent() bool {
	if o != nil && !IsNil(o.Parent) {
		return true
	}

	return false
}

// SetParent gets a reference to the given string and assigns it to the Parent field.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) SetParent(v string) {
	o.Parent = &v
}

// GetValueType returns the ValueType field value if set, zero value otherwise.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetValueType() string {
	if o == nil || IsNil(o.ValueType) {
		var ret string
		return ret
	}
	return *o.ValueType
}

// GetValueTypeOk returns a tuple with the ValueType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetValueTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ValueType) {
		return nil, false
	}
	return o.ValueType, true
}

// HasValueType returns a boolean if a field has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) HasValueType() bool {
	if o != nil && !IsNil(o.ValueType) {
		return true
	}

	return false
}

// SetValueType gets a reference to the given string and assigns it to the ValueType field.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) SetValueType(v string) {
	o.ValueType = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetGroupDisplayName returns the GroupDisplayName field value if set, zero value otherwise.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetGroupDisplayName() string {
	if o == nil || IsNil(o.GroupDisplayName) {
		var ret string
		return ret
	}
	return *o.GroupDisplayName
}

// GetGroupDisplayNameOk returns a tuple with the GroupDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetGroupDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.GroupDisplayName) {
		return nil, false
	}
	return o.GroupDisplayName, true
}

// HasGroupDisplayName returns a boolean if a field has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) HasGroupDisplayName() bool {
	if o != nil && !IsNil(o.GroupDisplayName) {
		return true
	}

	return false
}

// SetGroupDisplayName gets a reference to the given string and assigns it to the GroupDisplayName field.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) SetGroupDisplayName(v string) {
	o.GroupDisplayName = &v
}

// GetRepeatable returns the Repeatable field value if set, zero value otherwise.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetRepeatable() bool {
	if o == nil || IsNil(o.Repeatable) {
		var ret bool
		return ret
	}
	return *o.Repeatable
}

// GetRepeatableOk returns a tuple with the Repeatable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetRepeatableOk() (*bool, bool) {
	if o == nil || IsNil(o.Repeatable) {
		return nil, false
	}
	return o.Repeatable, true
}

// HasRepeatable returns a boolean if a field has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) HasRepeatable() bool {
	if o != nil && !IsNil(o.Repeatable) {
		return true
	}

	return false
}

// SetRepeatable gets a reference to the given bool and assigns it to the Repeatable field.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) SetRepeatable(v bool) {
	o.Repeatable = &v
}

// GetDeprecated returns the Deprecated field value if set, zero value otherwise.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetDeprecated() bool {
	if o == nil || IsNil(o.Deprecated) {
		var ret bool
		return ret
	}
	return *o.Deprecated
}

// GetDeprecatedOk returns a tuple with the Deprecated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetDeprecatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deprecated) {
		return nil, false
	}
	return o.Deprecated, true
}

// HasDeprecated returns a boolean if a field has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) HasDeprecated() bool {
	if o != nil && !IsNil(o.Deprecated) {
		return true
	}

	return false
}

// SetDeprecated gets a reference to the given bool and assigns it to the Deprecated field.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) SetDeprecated(v bool) {
	o.Deprecated = &v
}

// GetValueMetadata returns the ValueMetadata field value if set, zero value otherwise.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetValueMetadata() []GetGmbAttributeMetadata200ResponseAttributeMetadataInnerValueMetadataInner {
	if o == nil || IsNil(o.ValueMetadata) {
		var ret []GetGmbAttributeMetadata200ResponseAttributeMetadataInnerValueMetadataInner
		return ret
	}
	return o.ValueMetadata
}

// GetValueMetadataOk returns a tuple with the ValueMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) GetValueMetadataOk() ([]GetGmbAttributeMetadata200ResponseAttributeMetadataInnerValueMetadataInner, bool) {
	if o == nil || IsNil(o.ValueMetadata) {
		return nil, false
	}
	return o.ValueMetadata, true
}

// HasValueMetadata returns a boolean if a field has been set.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) HasValueMetadata() bool {
	if o != nil && !IsNil(o.ValueMetadata) {
		return true
	}

	return false
}

// SetValueMetadata gets a reference to the given []GetGmbAttributeMetadata200ResponseAttributeMetadataInnerValueMetadataInner and assigns it to the ValueMetadata field.
func (o *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) SetValueMetadata(v []GetGmbAttributeMetadata200ResponseAttributeMetadataInnerValueMetadataInner) {
	o.ValueMetadata = v
}

func (o GetGmbAttributeMetadata200ResponseAttributeMetadataInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGmbAttributeMetadata200ResponseAttributeMetadataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Parent) {
		toSerialize["parent"] = o.Parent
	}
	if !IsNil(o.ValueType) {
		toSerialize["valueType"] = o.ValueType
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.GroupDisplayName) {
		toSerialize["groupDisplayName"] = o.GroupDisplayName
	}
	if !IsNil(o.Repeatable) {
		toSerialize["repeatable"] = o.Repeatable
	}
	if !IsNil(o.Deprecated) {
		toSerialize["deprecated"] = o.Deprecated
	}
	if !IsNil(o.ValueMetadata) {
		toSerialize["valueMetadata"] = o.ValueMetadata
	}
	return toSerialize, nil
}

type NullableGetGmbAttributeMetadata200ResponseAttributeMetadataInner struct {
	value *GetGmbAttributeMetadata200ResponseAttributeMetadataInner
	isSet bool
}

func (v NullableGetGmbAttributeMetadata200ResponseAttributeMetadataInner) Get() *GetGmbAttributeMetadata200ResponseAttributeMetadataInner {
	return v.value
}

func (v *NullableGetGmbAttributeMetadata200ResponseAttributeMetadataInner) Set(val *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGmbAttributeMetadata200ResponseAttributeMetadataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGmbAttributeMetadata200ResponseAttributeMetadataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGmbAttributeMetadata200ResponseAttributeMetadataInner(val *GetGmbAttributeMetadata200ResponseAttributeMetadataInner) *NullableGetGmbAttributeMetadata200ResponseAttributeMetadataInner {
	return &NullableGetGmbAttributeMetadata200ResponseAttributeMetadataInner{value: val, isSet: true}
}

func (v NullableGetGmbAttributeMetadata200ResponseAttributeMetadataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGmbAttributeMetadata200ResponseAttributeMetadataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
