/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.89.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the XArticleEntityOneOf5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &XArticleEntityOneOf5{}

// XArticleEntityOneOf5 struct for XArticleEntityOneOf5
type XArticleEntityOneOf5 struct {
	Key   string                    `json:"key"`
	Value XArticleEntityOneOf5Value `json:"value"`
}

type _XArticleEntityOneOf5 XArticleEntityOneOf5

// NewXArticleEntityOneOf5 instantiates a new XArticleEntityOneOf5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewXArticleEntityOneOf5(key string, value XArticleEntityOneOf5Value) *XArticleEntityOneOf5 {
	this := XArticleEntityOneOf5{}
	this.Key = key
	this.Value = value
	return &this
}

// NewXArticleEntityOneOf5WithDefaults instantiates a new XArticleEntityOneOf5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewXArticleEntityOneOf5WithDefaults() *XArticleEntityOneOf5 {
	this := XArticleEntityOneOf5{}
	return &this
}

// GetKey returns the Key field value
func (o *XArticleEntityOneOf5) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *XArticleEntityOneOf5) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *XArticleEntityOneOf5) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *XArticleEntityOneOf5) GetValue() XArticleEntityOneOf5Value {
	if o == nil {
		var ret XArticleEntityOneOf5Value
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *XArticleEntityOneOf5) GetValueOk() (*XArticleEntityOneOf5Value, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *XArticleEntityOneOf5) SetValue(v XArticleEntityOneOf5Value) {
	o.Value = v
}

func (o XArticleEntityOneOf5) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o XArticleEntityOneOf5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *XArticleEntityOneOf5) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varXArticleEntityOneOf5 := _XArticleEntityOneOf5{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varXArticleEntityOneOf5)

	if err != nil {
		return err
	}

	*o = XArticleEntityOneOf5(varXArticleEntityOneOf5)

	return err
}

type NullableXArticleEntityOneOf5 struct {
	value *XArticleEntityOneOf5
	isSet bool
}

func (v NullableXArticleEntityOneOf5) Get() *XArticleEntityOneOf5 {
	return v.value
}

func (v *NullableXArticleEntityOneOf5) Set(val *XArticleEntityOneOf5) {
	v.value = val
	v.isSet = true
}

func (v NullableXArticleEntityOneOf5) IsSet() bool {
	return v.isSet
}

func (v *NullableXArticleEntityOneOf5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableXArticleEntityOneOf5(val *XArticleEntityOneOf5) *NullableXArticleEntityOneOf5 {
	return &NullableXArticleEntityOneOf5{value: val, isSet: true}
}

func (v NullableXArticleEntityOneOf5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableXArticleEntityOneOf5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
