/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.77.1
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the PreflightSmsRegistration200ResponseComposed type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreflightSmsRegistration200ResponseComposed{}

// PreflightSmsRegistration200ResponseComposed The exact payloads a submission would store (post-branding, disclosures appended, auto-replies generated).
type PreflightSmsRegistration200ResponseComposed struct {
	Brand    map[string]interface{} `json:"brand,omitempty"`
	Campaign map[string]interface{} `json:"campaign,omitempty"`
}

// NewPreflightSmsRegistration200ResponseComposed instantiates a new PreflightSmsRegistration200ResponseComposed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreflightSmsRegistration200ResponseComposed() *PreflightSmsRegistration200ResponseComposed {
	this := PreflightSmsRegistration200ResponseComposed{}
	return &this
}

// NewPreflightSmsRegistration200ResponseComposedWithDefaults instantiates a new PreflightSmsRegistration200ResponseComposed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreflightSmsRegistration200ResponseComposedWithDefaults() *PreflightSmsRegistration200ResponseComposed {
	this := PreflightSmsRegistration200ResponseComposed{}
	return &this
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *PreflightSmsRegistration200ResponseComposed) GetBrand() map[string]interface{} {
	if o == nil || IsNil(o.Brand) {
		var ret map[string]interface{}
		return ret
	}
	return o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreflightSmsRegistration200ResponseComposed) GetBrandOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Brand) {
		return map[string]interface{}{}, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *PreflightSmsRegistration200ResponseComposed) HasBrand() bool {
	if o != nil && !IsNil(o.Brand) {
		return true
	}

	return false
}

// SetBrand gets a reference to the given map[string]interface{} and assigns it to the Brand field.
func (o *PreflightSmsRegistration200ResponseComposed) SetBrand(v map[string]interface{}) {
	o.Brand = v
}

// GetCampaign returns the Campaign field value if set, zero value otherwise.
func (o *PreflightSmsRegistration200ResponseComposed) GetCampaign() map[string]interface{} {
	if o == nil || IsNil(o.Campaign) {
		var ret map[string]interface{}
		return ret
	}
	return o.Campaign
}

// GetCampaignOk returns a tuple with the Campaign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreflightSmsRegistration200ResponseComposed) GetCampaignOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Campaign) {
		return map[string]interface{}{}, false
	}
	return o.Campaign, true
}

// HasCampaign returns a boolean if a field has been set.
func (o *PreflightSmsRegistration200ResponseComposed) HasCampaign() bool {
	if o != nil && !IsNil(o.Campaign) {
		return true
	}

	return false
}

// SetCampaign gets a reference to the given map[string]interface{} and assigns it to the Campaign field.
func (o *PreflightSmsRegistration200ResponseComposed) SetCampaign(v map[string]interface{}) {
	o.Campaign = v
}

func (o PreflightSmsRegistration200ResponseComposed) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreflightSmsRegistration200ResponseComposed) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Brand) {
		toSerialize["brand"] = o.Brand
	}
	if !IsNil(o.Campaign) {
		toSerialize["campaign"] = o.Campaign
	}
	return toSerialize, nil
}

type NullablePreflightSmsRegistration200ResponseComposed struct {
	value *PreflightSmsRegistration200ResponseComposed
	isSet bool
}

func (v NullablePreflightSmsRegistration200ResponseComposed) Get() *PreflightSmsRegistration200ResponseComposed {
	return v.value
}

func (v *NullablePreflightSmsRegistration200ResponseComposed) Set(val *PreflightSmsRegistration200ResponseComposed) {
	v.value = val
	v.isSet = true
}

func (v NullablePreflightSmsRegistration200ResponseComposed) IsSet() bool {
	return v.isSet
}

func (v *NullablePreflightSmsRegistration200ResponseComposed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreflightSmsRegistration200ResponseComposed(val *PreflightSmsRegistration200ResponseComposed) *NullablePreflightSmsRegistration200ResponseComposed {
	return &NullablePreflightSmsRegistration200ResponseComposed{value: val, isSet: true}
}

func (v NullablePreflightSmsRegistration200ResponseComposed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreflightSmsRegistration200ResponseComposed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
