/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateInboxConversationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInboxConversationRequest{}

// CreateInboxConversationRequest struct for CreateInboxConversationRequest
type CreateInboxConversationRequest struct {
	// The account ID to send from
	AccountId string `json:"accountId"`
	// Recipient identifier. For X this is the numeric user ID; for WhatsApp and SMS, the recipient phone number in international format (digits, country code included); for Slack, the workspace member id (e.g. U01ABCDEF). Provide either this or participantUsername.
	ParticipantId *string `json:"participantId,omitempty"`
	// Recipient handle/username, an X or Bluesky handle (with or without @) or a Reddit username (with or without u/). Resolved via lookup. Provide either this or participantId.
	ParticipantUsername *string `json:"participantUsername,omitempty"`
	// Text content of the message. At least one of message, attachment, or (for WhatsApp) templateName is required. Required when category is set (a Direct Send utility message is a text message).
	Message *string `json:"message,omitempty"`
	// X only. Skip the receives_your_dm eligibility check before sending. Use if you have already verified the recipient accepts DMs.
	SkipDmCheck *bool `json:"skipDmCheck,omitempty"`
	// WhatsApp only. Name of the approved template to start the conversation with. Required for WhatsApp unless category is used instead (Direct Send). Cannot be combined with category.
	TemplateName *string `json:"templateName,omitempty"`
	// WhatsApp only (Meta Direct Send). Combined with message and without templateName, starts the conversation with a business-initiated UTILITY message and no pre-approved template; Meta matches or auto-creates a template asynchronously. The WhatsApp Business Account must be eligible for Direct Send, otherwise the send fails with an error telling you to use an approved message template instead. Cannot be combined with templateName (templates are already categorized at creation). Utility messages only; marketing content is not allowed under this category. Accepted on the JSON body only, not on multipart requests.
	Category *string `json:"category,omitempty"`
	// WhatsApp only. Set false to send the Direct Send (category: 'utility') text message without a link-preview thumbnail for the first URL in the text. Defaults to true, which is how every WhatsApp text has been sent to date. Does not apply to template sends. Accepted on the JSON body only, not on multipart requests.
	LinkPreview *bool `json:"linkPreview,omitempty"`
	// WhatsApp only. Template language code (e.g. en_US).
	TemplateLanguage *string `json:"templateLanguage,omitempty"`
	// WhatsApp only. Template variable values as one flat array, in the order the variables appear across the whole template: text-header variables first, then body variables, then one value per dynamic URL button (in button order). Works with positional placeholders ({{1}}, {{2}}, ...) and with named placeholders ({{name}}, {{company}} - how Meta Business Manager creates templates), where values fill the named slots in order of appearance. Example - a body with {{1}}, {{2}} plus a URL button https://example.com/{{1}} takes three values: [body1, body2, buttonSuffix]. For positional templates the list must cover every slot: supplying fewer values than the template's header + body + dynamic URL-button count is rejected with a 400 (code INVALID_TEMPLATE_PARAMS) naming the expected split, rather than delivering a template whose button URL was filled from the wrong value. A dynamic URL button covered by templateButtonParams needs no value here unless another uncovered dynamic URL button follows it, since the override applies after slot numbering. Media headers (image, video, document) are filled automatically from the approved template and take no value here (use headerMedia to override the header asset per send). Buttons that are not dynamic-URL buttons (copy-code, flow) take no value here either; use templateButtonParams.
	TemplateParams []string `json:"templateParams,omitempty"`
	// WhatsApp only. Values for template buttons that carry one at send time, each addressed by the button's position in the approved template. This is the only way to send a copy-code button's payload (a Pix payment code, a coupon) or a flow token, because templateParams is a flat array of text variables and covers dynamic URL buttons only. Supplying a button here overrides whatever templateParams would have derived for that same index, so the send never carries one button twice; repeating an index within this array is rejected with 400. Each index must name a button of the matching kind on the approved template, which is also checked before the send and returns 400 (INVALID_TEMPLATE_BUTTON_PARAM) rather than a Meta rejection.
	TemplateButtonParams []CreateInboxConversationRequestTemplateButtonParamsInner `json:"templateButtonParams,omitempty"`
	// WhatsApp only. Per-card overrides for a CAROUSEL template, each addressed by the card's card_index. Carousel card body variables restart at {{1}} per card, so they cannot be expressed in the flat templateParams slot order; use this instead. A cardIndex naming a card the approved template does not have, a duplicate cardIndex, or a params count that does not match the card body's token count is rejected with 400 (INVALID_TEMPLATE_CARD_PARAM).
	TemplateCards  []CreateInboxConversationRequestTemplateCardsInner `json:"templateCards,omitempty"`
	HeaderMedia    *CreateInboxConversationRequestHeaderMedia         `json:"headerMedia,omitempty"`
	HeaderLocation *CreateInboxConversationRequestHeaderLocation      `json:"headerLocation,omitempty"`
}

type _CreateInboxConversationRequest CreateInboxConversationRequest

// NewCreateInboxConversationRequest instantiates a new CreateInboxConversationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInboxConversationRequest(accountId string) *CreateInboxConversationRequest {
	this := CreateInboxConversationRequest{}
	this.AccountId = accountId
	var skipDmCheck bool = false
	this.SkipDmCheck = &skipDmCheck
	var linkPreview bool = true
	this.LinkPreview = &linkPreview
	return &this
}

// NewCreateInboxConversationRequestWithDefaults instantiates a new CreateInboxConversationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInboxConversationRequestWithDefaults() *CreateInboxConversationRequest {
	this := CreateInboxConversationRequest{}
	var skipDmCheck bool = false
	this.SkipDmCheck = &skipDmCheck
	var linkPreview bool = true
	this.LinkPreview = &linkPreview
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CreateInboxConversationRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CreateInboxConversationRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetParticipantId returns the ParticipantId field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetParticipantId() string {
	if o == nil || IsNil(o.ParticipantId) {
		var ret string
		return ret
	}
	return *o.ParticipantId
}

// GetParticipantIdOk returns a tuple with the ParticipantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetParticipantIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParticipantId) {
		return nil, false
	}
	return o.ParticipantId, true
}

// HasParticipantId returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasParticipantId() bool {
	if o != nil && !IsNil(o.ParticipantId) {
		return true
	}

	return false
}

// SetParticipantId gets a reference to the given string and assigns it to the ParticipantId field.
func (o *CreateInboxConversationRequest) SetParticipantId(v string) {
	o.ParticipantId = &v
}

// GetParticipantUsername returns the ParticipantUsername field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetParticipantUsername() string {
	if o == nil || IsNil(o.ParticipantUsername) {
		var ret string
		return ret
	}
	return *o.ParticipantUsername
}

// GetParticipantUsernameOk returns a tuple with the ParticipantUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetParticipantUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.ParticipantUsername) {
		return nil, false
	}
	return o.ParticipantUsername, true
}

// HasParticipantUsername returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasParticipantUsername() bool {
	if o != nil && !IsNil(o.ParticipantUsername) {
		return true
	}

	return false
}

// SetParticipantUsername gets a reference to the given string and assigns it to the ParticipantUsername field.
func (o *CreateInboxConversationRequest) SetParticipantUsername(v string) {
	o.ParticipantUsername = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateInboxConversationRequest) SetMessage(v string) {
	o.Message = &v
}

// GetSkipDmCheck returns the SkipDmCheck field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetSkipDmCheck() bool {
	if o == nil || IsNil(o.SkipDmCheck) {
		var ret bool
		return ret
	}
	return *o.SkipDmCheck
}

// GetSkipDmCheckOk returns a tuple with the SkipDmCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetSkipDmCheckOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipDmCheck) {
		return nil, false
	}
	return o.SkipDmCheck, true
}

// HasSkipDmCheck returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasSkipDmCheck() bool {
	if o != nil && !IsNil(o.SkipDmCheck) {
		return true
	}

	return false
}

// SetSkipDmCheck gets a reference to the given bool and assigns it to the SkipDmCheck field.
func (o *CreateInboxConversationRequest) SetSkipDmCheck(v bool) {
	o.SkipDmCheck = &v
}

// GetTemplateName returns the TemplateName field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetTemplateName() string {
	if o == nil || IsNil(o.TemplateName) {
		var ret string
		return ret
	}
	return *o.TemplateName
}

// GetTemplateNameOk returns a tuple with the TemplateName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetTemplateNameOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateName) {
		return nil, false
	}
	return o.TemplateName, true
}

// HasTemplateName returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasTemplateName() bool {
	if o != nil && !IsNil(o.TemplateName) {
		return true
	}

	return false
}

// SetTemplateName gets a reference to the given string and assigns it to the TemplateName field.
func (o *CreateInboxConversationRequest) SetTemplateName(v string) {
	o.TemplateName = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *CreateInboxConversationRequest) SetCategory(v string) {
	o.Category = &v
}

// GetLinkPreview returns the LinkPreview field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetLinkPreview() bool {
	if o == nil || IsNil(o.LinkPreview) {
		var ret bool
		return ret
	}
	return *o.LinkPreview
}

// GetLinkPreviewOk returns a tuple with the LinkPreview field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetLinkPreviewOk() (*bool, bool) {
	if o == nil || IsNil(o.LinkPreview) {
		return nil, false
	}
	return o.LinkPreview, true
}

// HasLinkPreview returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasLinkPreview() bool {
	if o != nil && !IsNil(o.LinkPreview) {
		return true
	}

	return false
}

// SetLinkPreview gets a reference to the given bool and assigns it to the LinkPreview field.
func (o *CreateInboxConversationRequest) SetLinkPreview(v bool) {
	o.LinkPreview = &v
}

// GetTemplateLanguage returns the TemplateLanguage field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetTemplateLanguage() string {
	if o == nil || IsNil(o.TemplateLanguage) {
		var ret string
		return ret
	}
	return *o.TemplateLanguage
}

// GetTemplateLanguageOk returns a tuple with the TemplateLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetTemplateLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateLanguage) {
		return nil, false
	}
	return o.TemplateLanguage, true
}

// HasTemplateLanguage returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasTemplateLanguage() bool {
	if o != nil && !IsNil(o.TemplateLanguage) {
		return true
	}

	return false
}

// SetTemplateLanguage gets a reference to the given string and assigns it to the TemplateLanguage field.
func (o *CreateInboxConversationRequest) SetTemplateLanguage(v string) {
	o.TemplateLanguage = &v
}

// GetTemplateParams returns the TemplateParams field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetTemplateParams() []string {
	if o == nil || IsNil(o.TemplateParams) {
		var ret []string
		return ret
	}
	return o.TemplateParams
}

// GetTemplateParamsOk returns a tuple with the TemplateParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetTemplateParamsOk() ([]string, bool) {
	if o == nil || IsNil(o.TemplateParams) {
		return nil, false
	}
	return o.TemplateParams, true
}

// HasTemplateParams returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasTemplateParams() bool {
	if o != nil && !IsNil(o.TemplateParams) {
		return true
	}

	return false
}

// SetTemplateParams gets a reference to the given []string and assigns it to the TemplateParams field.
func (o *CreateInboxConversationRequest) SetTemplateParams(v []string) {
	o.TemplateParams = v
}

// GetTemplateButtonParams returns the TemplateButtonParams field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetTemplateButtonParams() []CreateInboxConversationRequestTemplateButtonParamsInner {
	if o == nil || IsNil(o.TemplateButtonParams) {
		var ret []CreateInboxConversationRequestTemplateButtonParamsInner
		return ret
	}
	return o.TemplateButtonParams
}

// GetTemplateButtonParamsOk returns a tuple with the TemplateButtonParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetTemplateButtonParamsOk() ([]CreateInboxConversationRequestTemplateButtonParamsInner, bool) {
	if o == nil || IsNil(o.TemplateButtonParams) {
		return nil, false
	}
	return o.TemplateButtonParams, true
}

// HasTemplateButtonParams returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasTemplateButtonParams() bool {
	if o != nil && !IsNil(o.TemplateButtonParams) {
		return true
	}

	return false
}

// SetTemplateButtonParams gets a reference to the given []CreateInboxConversationRequestTemplateButtonParamsInner and assigns it to the TemplateButtonParams field.
func (o *CreateInboxConversationRequest) SetTemplateButtonParams(v []CreateInboxConversationRequestTemplateButtonParamsInner) {
	o.TemplateButtonParams = v
}

// GetTemplateCards returns the TemplateCards field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetTemplateCards() []CreateInboxConversationRequestTemplateCardsInner {
	if o == nil || IsNil(o.TemplateCards) {
		var ret []CreateInboxConversationRequestTemplateCardsInner
		return ret
	}
	return o.TemplateCards
}

// GetTemplateCardsOk returns a tuple with the TemplateCards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetTemplateCardsOk() ([]CreateInboxConversationRequestTemplateCardsInner, bool) {
	if o == nil || IsNil(o.TemplateCards) {
		return nil, false
	}
	return o.TemplateCards, true
}

// HasTemplateCards returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasTemplateCards() bool {
	if o != nil && !IsNil(o.TemplateCards) {
		return true
	}

	return false
}

// SetTemplateCards gets a reference to the given []CreateInboxConversationRequestTemplateCardsInner and assigns it to the TemplateCards field.
func (o *CreateInboxConversationRequest) SetTemplateCards(v []CreateInboxConversationRequestTemplateCardsInner) {
	o.TemplateCards = v
}

// GetHeaderMedia returns the HeaderMedia field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetHeaderMedia() CreateInboxConversationRequestHeaderMedia {
	if o == nil || IsNil(o.HeaderMedia) {
		var ret CreateInboxConversationRequestHeaderMedia
		return ret
	}
	return *o.HeaderMedia
}

// GetHeaderMediaOk returns a tuple with the HeaderMedia field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetHeaderMediaOk() (*CreateInboxConversationRequestHeaderMedia, bool) {
	if o == nil || IsNil(o.HeaderMedia) {
		return nil, false
	}
	return o.HeaderMedia, true
}

// HasHeaderMedia returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasHeaderMedia() bool {
	if o != nil && !IsNil(o.HeaderMedia) {
		return true
	}

	return false
}

// SetHeaderMedia gets a reference to the given CreateInboxConversationRequestHeaderMedia and assigns it to the HeaderMedia field.
func (o *CreateInboxConversationRequest) SetHeaderMedia(v CreateInboxConversationRequestHeaderMedia) {
	o.HeaderMedia = &v
}

// GetHeaderLocation returns the HeaderLocation field value if set, zero value otherwise.
func (o *CreateInboxConversationRequest) GetHeaderLocation() CreateInboxConversationRequestHeaderLocation {
	if o == nil || IsNil(o.HeaderLocation) {
		var ret CreateInboxConversationRequestHeaderLocation
		return ret
	}
	return *o.HeaderLocation
}

// GetHeaderLocationOk returns a tuple with the HeaderLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInboxConversationRequest) GetHeaderLocationOk() (*CreateInboxConversationRequestHeaderLocation, bool) {
	if o == nil || IsNil(o.HeaderLocation) {
		return nil, false
	}
	return o.HeaderLocation, true
}

// HasHeaderLocation returns a boolean if a field has been set.
func (o *CreateInboxConversationRequest) HasHeaderLocation() bool {
	if o != nil && !IsNil(o.HeaderLocation) {
		return true
	}

	return false
}

// SetHeaderLocation gets a reference to the given CreateInboxConversationRequestHeaderLocation and assigns it to the HeaderLocation field.
func (o *CreateInboxConversationRequest) SetHeaderLocation(v CreateInboxConversationRequestHeaderLocation) {
	o.HeaderLocation = &v
}

func (o CreateInboxConversationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInboxConversationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	if !IsNil(o.ParticipantId) {
		toSerialize["participantId"] = o.ParticipantId
	}
	if !IsNil(o.ParticipantUsername) {
		toSerialize["participantUsername"] = o.ParticipantUsername
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.SkipDmCheck) {
		toSerialize["skipDmCheck"] = o.SkipDmCheck
	}
	if !IsNil(o.TemplateName) {
		toSerialize["templateName"] = o.TemplateName
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.LinkPreview) {
		toSerialize["linkPreview"] = o.LinkPreview
	}
	if !IsNil(o.TemplateLanguage) {
		toSerialize["templateLanguage"] = o.TemplateLanguage
	}
	if !IsNil(o.TemplateParams) {
		toSerialize["templateParams"] = o.TemplateParams
	}
	if !IsNil(o.TemplateButtonParams) {
		toSerialize["templateButtonParams"] = o.TemplateButtonParams
	}
	if !IsNil(o.TemplateCards) {
		toSerialize["templateCards"] = o.TemplateCards
	}
	if !IsNil(o.HeaderMedia) {
		toSerialize["headerMedia"] = o.HeaderMedia
	}
	if !IsNil(o.HeaderLocation) {
		toSerialize["headerLocation"] = o.HeaderLocation
	}
	return toSerialize, nil
}

func (o *CreateInboxConversationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateInboxConversationRequest := _CreateInboxConversationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateInboxConversationRequest)

	if err != nil {
		return err
	}

	*o = CreateInboxConversationRequest(varCreateInboxConversationRequest)

	return err
}

type NullableCreateInboxConversationRequest struct {
	value *CreateInboxConversationRequest
	isSet bool
}

func (v NullableCreateInboxConversationRequest) Get() *CreateInboxConversationRequest {
	return v.value
}

func (v *NullableCreateInboxConversationRequest) Set(val *CreateInboxConversationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInboxConversationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInboxConversationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInboxConversationRequest(val *CreateInboxConversationRequest) *NullableCreateInboxConversationRequest {
	return &NullableCreateInboxConversationRequest{value: val, isSet: true}
}

func (v NullableCreateInboxConversationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInboxConversationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
