/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateTrackingTagRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTrackingTagRequest{}

// CreateTrackingTagRequest struct for CreateTrackingTagRequest
type CreateTrackingTagRequest struct {
	// Meta ad account id, e.g. `act_123456789`. Required by this endpoint but ignored for OpenAI Ads.
	AdAccountId string `json:"adAccountId"`
	Name        string `json:"name"`
	// OpenAI Ads only (ignored by Meta). When set, also provisions a standard conversion event setting wired to the new pixel, so `goal: conversions` ad creates on `POST /v1/ads/create` have an event to reference immediately.
	DefaultEventType *string `json:"defaultEventType,omitempty"`
}

type _CreateTrackingTagRequest CreateTrackingTagRequest

// NewCreateTrackingTagRequest instantiates a new CreateTrackingTagRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTrackingTagRequest(adAccountId string, name string) *CreateTrackingTagRequest {
	this := CreateTrackingTagRequest{}
	this.AdAccountId = adAccountId
	this.Name = name
	return &this
}

// NewCreateTrackingTagRequestWithDefaults instantiates a new CreateTrackingTagRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTrackingTagRequestWithDefaults() *CreateTrackingTagRequest {
	this := CreateTrackingTagRequest{}
	return &this
}

// GetAdAccountId returns the AdAccountId field value
func (o *CreateTrackingTagRequest) GetAdAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdAccountId
}

// GetAdAccountIdOk returns a tuple with the AdAccountId field value
// and a boolean to check if the value has been set.
func (o *CreateTrackingTagRequest) GetAdAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdAccountId, true
}

// SetAdAccountId sets field value
func (o *CreateTrackingTagRequest) SetAdAccountId(v string) {
	o.AdAccountId = v
}

// GetName returns the Name field value
func (o *CreateTrackingTagRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTrackingTagRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTrackingTagRequest) SetName(v string) {
	o.Name = v
}

// GetDefaultEventType returns the DefaultEventType field value if set, zero value otherwise.
func (o *CreateTrackingTagRequest) GetDefaultEventType() string {
	if o == nil || IsNil(o.DefaultEventType) {
		var ret string
		return ret
	}
	return *o.DefaultEventType
}

// GetDefaultEventTypeOk returns a tuple with the DefaultEventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTrackingTagRequest) GetDefaultEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultEventType) {
		return nil, false
	}
	return o.DefaultEventType, true
}

// HasDefaultEventType returns a boolean if a field has been set.
func (o *CreateTrackingTagRequest) HasDefaultEventType() bool {
	if o != nil && !IsNil(o.DefaultEventType) {
		return true
	}

	return false
}

// SetDefaultEventType gets a reference to the given string and assigns it to the DefaultEventType field.
func (o *CreateTrackingTagRequest) SetDefaultEventType(v string) {
	o.DefaultEventType = &v
}

func (o CreateTrackingTagRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTrackingTagRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["adAccountId"] = o.AdAccountId
	toSerialize["name"] = o.Name
	if !IsNil(o.DefaultEventType) {
		toSerialize["defaultEventType"] = o.DefaultEventType
	}
	return toSerialize, nil
}

func (o *CreateTrackingTagRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"adAccountId",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTrackingTagRequest := _CreateTrackingTagRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTrackingTagRequest)

	if err != nil {
		return err
	}

	*o = CreateTrackingTagRequest(varCreateTrackingTagRequest)

	return err
}

type NullableCreateTrackingTagRequest struct {
	value *CreateTrackingTagRequest
	isSet bool
}

func (v NullableCreateTrackingTagRequest) Get() *CreateTrackingTagRequest {
	return v.value
}

func (v *NullableCreateTrackingTagRequest) Set(val *CreateTrackingTagRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTrackingTagRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTrackingTagRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTrackingTagRequest(val *CreateTrackingTagRequest) *NullableCreateTrackingTagRequest {
	return &NullableCreateTrackingTagRequest{value: val, isSet: true}
}

func (v NullableCreateTrackingTagRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTrackingTagRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
