/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SendPrivateReplyToCommentRequestButtonsInnerOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendPrivateReplyToCommentRequestButtonsInnerOneOf2{}

// SendPrivateReplyToCommentRequestButtonsInnerOneOf2 struct for SendPrivateReplyToCommentRequestButtonsInnerOneOf2
type SendPrivateReplyToCommentRequestButtonsInnerOneOf2 struct {
	Type string `json:"type"`
	// Label shown on the button. Facebook only.
	Title string `json:"title"`
	// E.164 phone number dialed when tapped. Facebook only.
	Phone string `json:"phone"`
}

type _SendPrivateReplyToCommentRequestButtonsInnerOneOf2 SendPrivateReplyToCommentRequestButtonsInnerOneOf2

// NewSendPrivateReplyToCommentRequestButtonsInnerOneOf2 instantiates a new SendPrivateReplyToCommentRequestButtonsInnerOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendPrivateReplyToCommentRequestButtonsInnerOneOf2(type_ string, title string, phone string) *SendPrivateReplyToCommentRequestButtonsInnerOneOf2 {
	this := SendPrivateReplyToCommentRequestButtonsInnerOneOf2{}
	this.Type = type_
	this.Title = title
	this.Phone = phone
	return &this
}

// NewSendPrivateReplyToCommentRequestButtonsInnerOneOf2WithDefaults instantiates a new SendPrivateReplyToCommentRequestButtonsInnerOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendPrivateReplyToCommentRequestButtonsInnerOneOf2WithDefaults() *SendPrivateReplyToCommentRequestButtonsInnerOneOf2 {
	this := SendPrivateReplyToCommentRequestButtonsInnerOneOf2{}
	return &this
}

// GetType returns the Type field value
func (o *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) SetType(v string) {
	o.Type = v
}

// GetTitle returns the Title field value
func (o *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) SetTitle(v string) {
	o.Title = v
}

// GetPhone returns the Phone field value
func (o *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) SetPhone(v string) {
	o.Phone = v
}

func (o SendPrivateReplyToCommentRequestButtonsInnerOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendPrivateReplyToCommentRequestButtonsInnerOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["title"] = o.Title
	toSerialize["phone"] = o.Phone
	return toSerialize, nil
}

func (o *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendPrivateReplyToCommentRequestButtonsInnerOneOf2 := _SendPrivateReplyToCommentRequestButtonsInnerOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendPrivateReplyToCommentRequestButtonsInnerOneOf2)

	if err != nil {
		return err
	}

	*o = SendPrivateReplyToCommentRequestButtonsInnerOneOf2(varSendPrivateReplyToCommentRequestButtonsInnerOneOf2)

	return err
}

type NullableSendPrivateReplyToCommentRequestButtonsInnerOneOf2 struct {
	value *SendPrivateReplyToCommentRequestButtonsInnerOneOf2
	isSet bool
}

func (v NullableSendPrivateReplyToCommentRequestButtonsInnerOneOf2) Get() *SendPrivateReplyToCommentRequestButtonsInnerOneOf2 {
	return v.value
}

func (v *NullableSendPrivateReplyToCommentRequestButtonsInnerOneOf2) Set(val *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableSendPrivateReplyToCommentRequestButtonsInnerOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableSendPrivateReplyToCommentRequestButtonsInnerOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendPrivateReplyToCommentRequestButtonsInnerOneOf2(val *SendPrivateReplyToCommentRequestButtonsInnerOneOf2) *NullableSendPrivateReplyToCommentRequestButtonsInnerOneOf2 {
	return &NullableSendPrivateReplyToCommentRequestButtonsInnerOneOf2{value: val, isSet: true}
}

func (v NullableSendPrivateReplyToCommentRequestButtonsInnerOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendPrivateReplyToCommentRequestButtonsInnerOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
