/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.240.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SetMessengerIceBreakersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetMessengerIceBreakersRequest{}

// SetMessengerIceBreakersRequest struct for SetMessengerIceBreakersRequest
type SetMessengerIceBreakersRequest struct {
	// One entry per locale; one must use locale `default`.
	IceBreakers []MessengerIceBreakerLocale `json:"ice_breakers"`
}

type _SetMessengerIceBreakersRequest SetMessengerIceBreakersRequest

// NewSetMessengerIceBreakersRequest instantiates a new SetMessengerIceBreakersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetMessengerIceBreakersRequest(iceBreakers []MessengerIceBreakerLocale) *SetMessengerIceBreakersRequest {
	this := SetMessengerIceBreakersRequest{}
	this.IceBreakers = iceBreakers
	return &this
}

// NewSetMessengerIceBreakersRequestWithDefaults instantiates a new SetMessengerIceBreakersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetMessengerIceBreakersRequestWithDefaults() *SetMessengerIceBreakersRequest {
	this := SetMessengerIceBreakersRequest{}
	return &this
}

// GetIceBreakers returns the IceBreakers field value
func (o *SetMessengerIceBreakersRequest) GetIceBreakers() []MessengerIceBreakerLocale {
	if o == nil {
		var ret []MessengerIceBreakerLocale
		return ret
	}

	return o.IceBreakers
}

// GetIceBreakersOk returns a tuple with the IceBreakers field value
// and a boolean to check if the value has been set.
func (o *SetMessengerIceBreakersRequest) GetIceBreakersOk() ([]MessengerIceBreakerLocale, bool) {
	if o == nil {
		return nil, false
	}
	return o.IceBreakers, true
}

// SetIceBreakers sets field value
func (o *SetMessengerIceBreakersRequest) SetIceBreakers(v []MessengerIceBreakerLocale) {
	o.IceBreakers = v
}

func (o SetMessengerIceBreakersRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetMessengerIceBreakersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ice_breakers"] = o.IceBreakers
	return toSerialize, nil
}

func (o *SetMessengerIceBreakersRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ice_breakers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetMessengerIceBreakersRequest := _SetMessengerIceBreakersRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetMessengerIceBreakersRequest)

	if err != nil {
		return err
	}

	*o = SetMessengerIceBreakersRequest(varSetMessengerIceBreakersRequest)

	return err
}

type NullableSetMessengerIceBreakersRequest struct {
	value *SetMessengerIceBreakersRequest
	isSet bool
}

func (v NullableSetMessengerIceBreakersRequest) Get() *SetMessengerIceBreakersRequest {
	return v.value
}

func (v *NullableSetMessengerIceBreakersRequest) Set(val *SetMessengerIceBreakersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetMessengerIceBreakersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetMessengerIceBreakersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetMessengerIceBreakersRequest(val *SetMessengerIceBreakersRequest) *NullableSetMessengerIceBreakersRequest {
	return &NullableSetMessengerIceBreakersRequest{value: val, isSet: true}
}

func (v NullableSetMessengerIceBreakersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetMessengerIceBreakersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
