/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.154.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the WebhookPayloadAccountAdsSyncRecoveredSync type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookPayloadAccountAdsSyncRecoveredSync{}

// WebhookPayloadAccountAdsSyncRecoveredSync struct for WebhookPayloadAccountAdsSyncRecoveredSync
type WebhookPayloadAccountAdsSyncRecoveredSync struct {
	LastSuccessfulSyncAt time.Time `json:"lastSuccessfulSyncAt"`
	// The last successful sync before the failure started.
	FailingSince time.Time `json:"failingSince"`
}

type _WebhookPayloadAccountAdsSyncRecoveredSync WebhookPayloadAccountAdsSyncRecoveredSync

// NewWebhookPayloadAccountAdsSyncRecoveredSync instantiates a new WebhookPayloadAccountAdsSyncRecoveredSync object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookPayloadAccountAdsSyncRecoveredSync(lastSuccessfulSyncAt time.Time, failingSince time.Time) *WebhookPayloadAccountAdsSyncRecoveredSync {
	this := WebhookPayloadAccountAdsSyncRecoveredSync{}
	this.LastSuccessfulSyncAt = lastSuccessfulSyncAt
	this.FailingSince = failingSince
	return &this
}

// NewWebhookPayloadAccountAdsSyncRecoveredSyncWithDefaults instantiates a new WebhookPayloadAccountAdsSyncRecoveredSync object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookPayloadAccountAdsSyncRecoveredSyncWithDefaults() *WebhookPayloadAccountAdsSyncRecoveredSync {
	this := WebhookPayloadAccountAdsSyncRecoveredSync{}
	return &this
}

// GetLastSuccessfulSyncAt returns the LastSuccessfulSyncAt field value
func (o *WebhookPayloadAccountAdsSyncRecoveredSync) GetLastSuccessfulSyncAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastSuccessfulSyncAt
}

// GetLastSuccessfulSyncAtOk returns a tuple with the LastSuccessfulSyncAt field value
// and a boolean to check if the value has been set.
func (o *WebhookPayloadAccountAdsSyncRecoveredSync) GetLastSuccessfulSyncAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastSuccessfulSyncAt, true
}

// SetLastSuccessfulSyncAt sets field value
func (o *WebhookPayloadAccountAdsSyncRecoveredSync) SetLastSuccessfulSyncAt(v time.Time) {
	o.LastSuccessfulSyncAt = v
}

// GetFailingSince returns the FailingSince field value
func (o *WebhookPayloadAccountAdsSyncRecoveredSync) GetFailingSince() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.FailingSince
}

// GetFailingSinceOk returns a tuple with the FailingSince field value
// and a boolean to check if the value has been set.
func (o *WebhookPayloadAccountAdsSyncRecoveredSync) GetFailingSinceOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailingSince, true
}

// SetFailingSince sets field value
func (o *WebhookPayloadAccountAdsSyncRecoveredSync) SetFailingSince(v time.Time) {
	o.FailingSince = v
}

func (o WebhookPayloadAccountAdsSyncRecoveredSync) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookPayloadAccountAdsSyncRecoveredSync) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lastSuccessfulSyncAt"] = o.LastSuccessfulSyncAt
	toSerialize["failingSince"] = o.FailingSince
	return toSerialize, nil
}

func (o *WebhookPayloadAccountAdsSyncRecoveredSync) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lastSuccessfulSyncAt",
		"failingSince",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookPayloadAccountAdsSyncRecoveredSync := _WebhookPayloadAccountAdsSyncRecoveredSync{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookPayloadAccountAdsSyncRecoveredSync)

	if err != nil {
		return err
	}

	*o = WebhookPayloadAccountAdsSyncRecoveredSync(varWebhookPayloadAccountAdsSyncRecoveredSync)

	return err
}

type NullableWebhookPayloadAccountAdsSyncRecoveredSync struct {
	value *WebhookPayloadAccountAdsSyncRecoveredSync
	isSet bool
}

func (v NullableWebhookPayloadAccountAdsSyncRecoveredSync) Get() *WebhookPayloadAccountAdsSyncRecoveredSync {
	return v.value
}

func (v *NullableWebhookPayloadAccountAdsSyncRecoveredSync) Set(val *WebhookPayloadAccountAdsSyncRecoveredSync) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookPayloadAccountAdsSyncRecoveredSync) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookPayloadAccountAdsSyncRecoveredSync) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookPayloadAccountAdsSyncRecoveredSync(val *WebhookPayloadAccountAdsSyncRecoveredSync) *NullableWebhookPayloadAccountAdsSyncRecoveredSync {
	return &NullableWebhookPayloadAccountAdsSyncRecoveredSync{value: val, isSet: true}
}

func (v NullableWebhookPayloadAccountAdsSyncRecoveredSync) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookPayloadAccountAdsSyncRecoveredSync) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
