/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateFacebookPageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateFacebookPageRequest{}

// UpdateFacebookPageRequest struct for UpdateFacebookPageRequest
type UpdateFacebookPageRequest struct {
	SelectedPageId string `json:"selectedPageId"`
}

type _UpdateFacebookPageRequest UpdateFacebookPageRequest

// NewUpdateFacebookPageRequest instantiates a new UpdateFacebookPageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFacebookPageRequest(selectedPageId string) *UpdateFacebookPageRequest {
	this := UpdateFacebookPageRequest{}
	this.SelectedPageId = selectedPageId
	return &this
}

// NewUpdateFacebookPageRequestWithDefaults instantiates a new UpdateFacebookPageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFacebookPageRequestWithDefaults() *UpdateFacebookPageRequest {
	this := UpdateFacebookPageRequest{}
	return &this
}

// GetSelectedPageId returns the SelectedPageId field value
func (o *UpdateFacebookPageRequest) GetSelectedPageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SelectedPageId
}

// GetSelectedPageIdOk returns a tuple with the SelectedPageId field value
// and a boolean to check if the value has been set.
func (o *UpdateFacebookPageRequest) GetSelectedPageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SelectedPageId, true
}

// SetSelectedPageId sets field value
func (o *UpdateFacebookPageRequest) SetSelectedPageId(v string) {
	o.SelectedPageId = v
}

func (o UpdateFacebookPageRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateFacebookPageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["selectedPageId"] = o.SelectedPageId
	return toSerialize, nil
}

func (o *UpdateFacebookPageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"selectedPageId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateFacebookPageRequest := _UpdateFacebookPageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateFacebookPageRequest)

	if err != nil {
		return err
	}

	*o = UpdateFacebookPageRequest(varUpdateFacebookPageRequest)

	return err
}

type NullableUpdateFacebookPageRequest struct {
	value *UpdateFacebookPageRequest
	isSet bool
}

func (v NullableUpdateFacebookPageRequest) Get() *UpdateFacebookPageRequest {
	return v.value
}

func (v *NullableUpdateFacebookPageRequest) Set(val *UpdateFacebookPageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFacebookPageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFacebookPageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFacebookPageRequest(val *UpdateFacebookPageRequest) *NullableUpdateFacebookPageRequest {
	return &NullableUpdateFacebookPageRequest{value: val, isSet: true}
}

func (v NullableUpdateFacebookPageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFacebookPageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
