/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.21.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the GetMessageAttachment200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMessageAttachment200Response{}

// GetMessageAttachment200Response struct for GetMessageAttachment200Response
type GetMessageAttachment200Response struct {
	Status *string `json:"status,omitempty"`
	// Live media url. Short-lived; re-request this endpoint rather than storing it.
	Url *string `json:"url,omitempty"`
	// True when the stored url had expired and was re-minted from the platform.
	Refreshed *bool `json:"refreshed,omitempty"`
}

// NewGetMessageAttachment200Response instantiates a new GetMessageAttachment200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMessageAttachment200Response() *GetMessageAttachment200Response {
	this := GetMessageAttachment200Response{}
	return &this
}

// NewGetMessageAttachment200ResponseWithDefaults instantiates a new GetMessageAttachment200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMessageAttachment200ResponseWithDefaults() *GetMessageAttachment200Response {
	this := GetMessageAttachment200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetMessageAttachment200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMessageAttachment200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetMessageAttachment200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetMessageAttachment200Response) SetStatus(v string) {
	o.Status = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GetMessageAttachment200Response) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMessageAttachment200Response) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GetMessageAttachment200Response) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GetMessageAttachment200Response) SetUrl(v string) {
	o.Url = &v
}

// GetRefreshed returns the Refreshed field value if set, zero value otherwise.
func (o *GetMessageAttachment200Response) GetRefreshed() bool {
	if o == nil || IsNil(o.Refreshed) {
		var ret bool
		return ret
	}
	return *o.Refreshed
}

// GetRefreshedOk returns a tuple with the Refreshed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMessageAttachment200Response) GetRefreshedOk() (*bool, bool) {
	if o == nil || IsNil(o.Refreshed) {
		return nil, false
	}
	return o.Refreshed, true
}

// HasRefreshed returns a boolean if a field has been set.
func (o *GetMessageAttachment200Response) HasRefreshed() bool {
	if o != nil && !IsNil(o.Refreshed) {
		return true
	}

	return false
}

// SetRefreshed gets a reference to the given bool and assigns it to the Refreshed field.
func (o *GetMessageAttachment200Response) SetRefreshed(v bool) {
	o.Refreshed = &v
}

func (o GetMessageAttachment200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMessageAttachment200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Refreshed) {
		toSerialize["refreshed"] = o.Refreshed
	}
	return toSerialize, nil
}

type NullableGetMessageAttachment200Response struct {
	value *GetMessageAttachment200Response
	isSet bool
}

func (v NullableGetMessageAttachment200Response) Get() *GetMessageAttachment200Response {
	return v.value
}

func (v *NullableGetMessageAttachment200Response) Set(val *GetMessageAttachment200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMessageAttachment200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMessageAttachment200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMessageAttachment200Response(val *GetMessageAttachment200Response) *NullableGetMessageAttachment200Response {
	return &NullableGetMessageAttachment200Response{value: val, isSet: true}
}

func (v NullableGetMessageAttachment200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMessageAttachment200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
