/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the UsageStatsUsageXApiCalls type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageStatsUsageXApiCalls{}

// UsageStatsUsageXApiCalls **Deprecated.** Legacy 3-tier aggregate. Operations outside the three historical prices ($0.005/$0.010/$0.015) — notably the $0.200 \"Posts with URL\" tier added April 2026 — are silently excluded from this shape. Use `xApiCallsByOperation` instead; it captures every tier and is the source of truth for per-operation call counts.
type UsageStatsUsageXApiCalls struct {
	// Calls at $0.005 per call (reads, lists, bookmarks, content manage, etc.)
	XApi005 *int32 `json:"x_api_005,omitempty"`
	// Calls at $0.010 per call (user reads, DM reads, follow reads, trends, list create, privacy update)
	XApi010 *int32 `json:"x_api_010,omitempty"`
	// Calls at $0.015 per call (posts/replies, DM sends, user interactions)
	XApi015 *int32 `json:"x_api_015,omitempty"`
}

// NewUsageStatsUsageXApiCalls instantiates a new UsageStatsUsageXApiCalls object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageStatsUsageXApiCalls() *UsageStatsUsageXApiCalls {
	this := UsageStatsUsageXApiCalls{}
	return &this
}

// NewUsageStatsUsageXApiCallsWithDefaults instantiates a new UsageStatsUsageXApiCalls object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageStatsUsageXApiCallsWithDefaults() *UsageStatsUsageXApiCalls {
	this := UsageStatsUsageXApiCalls{}
	return &this
}

// GetXApi005 returns the XApi005 field value if set, zero value otherwise.
func (o *UsageStatsUsageXApiCalls) GetXApi005() int32 {
	if o == nil || IsNil(o.XApi005) {
		var ret int32
		return ret
	}
	return *o.XApi005
}

// GetXApi005Ok returns a tuple with the XApi005 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageStatsUsageXApiCalls) GetXApi005Ok() (*int32, bool) {
	if o == nil || IsNil(o.XApi005) {
		return nil, false
	}
	return o.XApi005, true
}

// HasXApi005 returns a boolean if a field has been set.
func (o *UsageStatsUsageXApiCalls) HasXApi005() bool {
	if o != nil && !IsNil(o.XApi005) {
		return true
	}

	return false
}

// SetXApi005 gets a reference to the given int32 and assigns it to the XApi005 field.
func (o *UsageStatsUsageXApiCalls) SetXApi005(v int32) {
	o.XApi005 = &v
}

// GetXApi010 returns the XApi010 field value if set, zero value otherwise.
func (o *UsageStatsUsageXApiCalls) GetXApi010() int32 {
	if o == nil || IsNil(o.XApi010) {
		var ret int32
		return ret
	}
	return *o.XApi010
}

// GetXApi010Ok returns a tuple with the XApi010 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageStatsUsageXApiCalls) GetXApi010Ok() (*int32, bool) {
	if o == nil || IsNil(o.XApi010) {
		return nil, false
	}
	return o.XApi010, true
}

// HasXApi010 returns a boolean if a field has been set.
func (o *UsageStatsUsageXApiCalls) HasXApi010() bool {
	if o != nil && !IsNil(o.XApi010) {
		return true
	}

	return false
}

// SetXApi010 gets a reference to the given int32 and assigns it to the XApi010 field.
func (o *UsageStatsUsageXApiCalls) SetXApi010(v int32) {
	o.XApi010 = &v
}

// GetXApi015 returns the XApi015 field value if set, zero value otherwise.
func (o *UsageStatsUsageXApiCalls) GetXApi015() int32 {
	if o == nil || IsNil(o.XApi015) {
		var ret int32
		return ret
	}
	return *o.XApi015
}

// GetXApi015Ok returns a tuple with the XApi015 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageStatsUsageXApiCalls) GetXApi015Ok() (*int32, bool) {
	if o == nil || IsNil(o.XApi015) {
		return nil, false
	}
	return o.XApi015, true
}

// HasXApi015 returns a boolean if a field has been set.
func (o *UsageStatsUsageXApiCalls) HasXApi015() bool {
	if o != nil && !IsNil(o.XApi015) {
		return true
	}

	return false
}

// SetXApi015 gets a reference to the given int32 and assigns it to the XApi015 field.
func (o *UsageStatsUsageXApiCalls) SetXApi015(v int32) {
	o.XApi015 = &v
}

func (o UsageStatsUsageXApiCalls) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageStatsUsageXApiCalls) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.XApi005) {
		toSerialize["x_api_005"] = o.XApi005
	}
	if !IsNil(o.XApi010) {
		toSerialize["x_api_010"] = o.XApi010
	}
	if !IsNil(o.XApi015) {
		toSerialize["x_api_015"] = o.XApi015
	}
	return toSerialize, nil
}

type NullableUsageStatsUsageXApiCalls struct {
	value *UsageStatsUsageXApiCalls
	isSet bool
}

func (v NullableUsageStatsUsageXApiCalls) Get() *UsageStatsUsageXApiCalls {
	return v.value
}

func (v *NullableUsageStatsUsageXApiCalls) Set(val *UsageStatsUsageXApiCalls) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageStatsUsageXApiCalls) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageStatsUsageXApiCalls) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageStatsUsageXApiCalls(val *UsageStatsUsageXApiCalls) *NullableUsageStatsUsageXApiCalls {
	return &NullableUsageStatsUsageXApiCalls{value: val, isSet: true}
}

func (v NullableUsageStatsUsageXApiCalls) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageStatsUsageXApiCalls) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
