/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the GetCampaignTargeting200ResponseLocationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCampaignTargeting200ResponseLocationsInner{}

// GetCampaignTargeting200ResponseLocationsInner struct for GetCampaignTargeting200ResponseLocationsInner
type GetCampaignTargeting200ResponseLocationsInner struct {
	// Numeric id from Google's geoTargetConstants/{id}.
	GeoTargetId *string `json:"geoTargetId,omitempty"`
	// true = excluded location.
	Negative *bool `json:"negative,omitempty"`
}

// NewGetCampaignTargeting200ResponseLocationsInner instantiates a new GetCampaignTargeting200ResponseLocationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCampaignTargeting200ResponseLocationsInner() *GetCampaignTargeting200ResponseLocationsInner {
	this := GetCampaignTargeting200ResponseLocationsInner{}
	return &this
}

// NewGetCampaignTargeting200ResponseLocationsInnerWithDefaults instantiates a new GetCampaignTargeting200ResponseLocationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCampaignTargeting200ResponseLocationsInnerWithDefaults() *GetCampaignTargeting200ResponseLocationsInner {
	this := GetCampaignTargeting200ResponseLocationsInner{}
	return &this
}

// GetGeoTargetId returns the GeoTargetId field value if set, zero value otherwise.
func (o *GetCampaignTargeting200ResponseLocationsInner) GetGeoTargetId() string {
	if o == nil || IsNil(o.GeoTargetId) {
		var ret string
		return ret
	}
	return *o.GeoTargetId
}

// GetGeoTargetIdOk returns a tuple with the GeoTargetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCampaignTargeting200ResponseLocationsInner) GetGeoTargetIdOk() (*string, bool) {
	if o == nil || IsNil(o.GeoTargetId) {
		return nil, false
	}
	return o.GeoTargetId, true
}

// HasGeoTargetId returns a boolean if a field has been set.
func (o *GetCampaignTargeting200ResponseLocationsInner) HasGeoTargetId() bool {
	if o != nil && !IsNil(o.GeoTargetId) {
		return true
	}

	return false
}

// SetGeoTargetId gets a reference to the given string and assigns it to the GeoTargetId field.
func (o *GetCampaignTargeting200ResponseLocationsInner) SetGeoTargetId(v string) {
	o.GeoTargetId = &v
}

// GetNegative returns the Negative field value if set, zero value otherwise.
func (o *GetCampaignTargeting200ResponseLocationsInner) GetNegative() bool {
	if o == nil || IsNil(o.Negative) {
		var ret bool
		return ret
	}
	return *o.Negative
}

// GetNegativeOk returns a tuple with the Negative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCampaignTargeting200ResponseLocationsInner) GetNegativeOk() (*bool, bool) {
	if o == nil || IsNil(o.Negative) {
		return nil, false
	}
	return o.Negative, true
}

// HasNegative returns a boolean if a field has been set.
func (o *GetCampaignTargeting200ResponseLocationsInner) HasNegative() bool {
	if o != nil && !IsNil(o.Negative) {
		return true
	}

	return false
}

// SetNegative gets a reference to the given bool and assigns it to the Negative field.
func (o *GetCampaignTargeting200ResponseLocationsInner) SetNegative(v bool) {
	o.Negative = &v
}

func (o GetCampaignTargeting200ResponseLocationsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCampaignTargeting200ResponseLocationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GeoTargetId) {
		toSerialize["geoTargetId"] = o.GeoTargetId
	}
	if !IsNil(o.Negative) {
		toSerialize["negative"] = o.Negative
	}
	return toSerialize, nil
}

type NullableGetCampaignTargeting200ResponseLocationsInner struct {
	value *GetCampaignTargeting200ResponseLocationsInner
	isSet bool
}

func (v NullableGetCampaignTargeting200ResponseLocationsInner) Get() *GetCampaignTargeting200ResponseLocationsInner {
	return v.value
}

func (v *NullableGetCampaignTargeting200ResponseLocationsInner) Set(val *GetCampaignTargeting200ResponseLocationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCampaignTargeting200ResponseLocationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCampaignTargeting200ResponseLocationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCampaignTargeting200ResponseLocationsInner(val *GetCampaignTargeting200ResponseLocationsInner) *NullableGetCampaignTargeting200ResponseLocationsInner {
	return &NullableGetCampaignTargeting200ResponseLocationsInner{value: val, isSet: true}
}

func (v NullableGetCampaignTargeting200ResponseLocationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCampaignTargeting200ResponseLocationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
