/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the GetGoogleBusinessServices200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGoogleBusinessServices200Response{}

// GetGoogleBusinessServices200Response struct for GetGoogleBusinessServices200Response
type GetGoogleBusinessServices200Response struct {
	Success    *bool                                               `json:"success,omitempty"`
	AccountId  *string                                             `json:"accountId,omitempty"`
	LocationId *string                                             `json:"locationId,omitempty"`
	Services   []GetGoogleBusinessServices200ResponseServicesInner `json:"services,omitempty"`
}

// NewGetGoogleBusinessServices200Response instantiates a new GetGoogleBusinessServices200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGoogleBusinessServices200Response() *GetGoogleBusinessServices200Response {
	this := GetGoogleBusinessServices200Response{}
	return &this
}

// NewGetGoogleBusinessServices200ResponseWithDefaults instantiates a new GetGoogleBusinessServices200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGoogleBusinessServices200ResponseWithDefaults() *GetGoogleBusinessServices200Response {
	this := GetGoogleBusinessServices200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetGoogleBusinessServices200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGoogleBusinessServices200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetGoogleBusinessServices200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetGoogleBusinessServices200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *GetGoogleBusinessServices200Response) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGoogleBusinessServices200Response) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *GetGoogleBusinessServices200Response) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *GetGoogleBusinessServices200Response) SetAccountId(v string) {
	o.AccountId = &v
}

// GetLocationId returns the LocationId field value if set, zero value otherwise.
func (o *GetGoogleBusinessServices200Response) GetLocationId() string {
	if o == nil || IsNil(o.LocationId) {
		var ret string
		return ret
	}
	return *o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGoogleBusinessServices200Response) GetLocationIdOk() (*string, bool) {
	if o == nil || IsNil(o.LocationId) {
		return nil, false
	}
	return o.LocationId, true
}

// HasLocationId returns a boolean if a field has been set.
func (o *GetGoogleBusinessServices200Response) HasLocationId() bool {
	if o != nil && !IsNil(o.LocationId) {
		return true
	}

	return false
}

// SetLocationId gets a reference to the given string and assigns it to the LocationId field.
func (o *GetGoogleBusinessServices200Response) SetLocationId(v string) {
	o.LocationId = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *GetGoogleBusinessServices200Response) GetServices() []GetGoogleBusinessServices200ResponseServicesInner {
	if o == nil || IsNil(o.Services) {
		var ret []GetGoogleBusinessServices200ResponseServicesInner
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGoogleBusinessServices200Response) GetServicesOk() ([]GetGoogleBusinessServices200ResponseServicesInner, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *GetGoogleBusinessServices200Response) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []GetGoogleBusinessServices200ResponseServicesInner and assigns it to the Services field.
func (o *GetGoogleBusinessServices200Response) SetServices(v []GetGoogleBusinessServices200ResponseServicesInner) {
	o.Services = v
}

func (o GetGoogleBusinessServices200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGoogleBusinessServices200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.LocationId) {
		toSerialize["locationId"] = o.LocationId
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	return toSerialize, nil
}

type NullableGetGoogleBusinessServices200Response struct {
	value *GetGoogleBusinessServices200Response
	isSet bool
}

func (v NullableGetGoogleBusinessServices200Response) Get() *GetGoogleBusinessServices200Response {
	return v.value
}

func (v *NullableGetGoogleBusinessServices200Response) Set(val *GetGoogleBusinessServices200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGoogleBusinessServices200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGoogleBusinessServices200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGoogleBusinessServices200Response(val *GetGoogleBusinessServices200Response) *NullableGetGoogleBusinessServices200Response {
	return &NullableGetGoogleBusinessServices200Response{value: val, isSet: true}
}

func (v NullableGetGoogleBusinessServices200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGoogleBusinessServices200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
