/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
	"time"
)

// checks if the PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber{}

// PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber struct for PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber
type PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber struct {
	Id                     *string    `json:"id,omitempty"`
	PhoneNumber            *string    `json:"phoneNumber,omitempty"`
	Status                 *string    `json:"status,omitempty"`
	Country                *string    `json:"country,omitempty"`
	ProvisionedAt          *time.Time `json:"provisionedAt,omitempty"`
	MetaPreverifiedId      *string    `json:"metaPreverifiedId,omitempty"`
	MetaVerificationStatus *string    `json:"metaVerificationStatus,omitempty"`
}

// NewPurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber instantiates a new PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber() *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber {
	this := PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber{}
	return &this
}

// NewPurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumberWithDefaults instantiates a new PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumberWithDefaults() *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber {
	this := PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) SetId(v string) {
	o.Id = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) SetStatus(v string) {
	o.Status = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) SetCountry(v string) {
	o.Country = &v
}

// GetProvisionedAt returns the ProvisionedAt field value if set, zero value otherwise.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetProvisionedAt() time.Time {
	if o == nil || IsNil(o.ProvisionedAt) {
		var ret time.Time
		return ret
	}
	return *o.ProvisionedAt
}

// GetProvisionedAtOk returns a tuple with the ProvisionedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetProvisionedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ProvisionedAt) {
		return nil, false
	}
	return o.ProvisionedAt, true
}

// HasProvisionedAt returns a boolean if a field has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) HasProvisionedAt() bool {
	if o != nil && !IsNil(o.ProvisionedAt) {
		return true
	}

	return false
}

// SetProvisionedAt gets a reference to the given time.Time and assigns it to the ProvisionedAt field.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) SetProvisionedAt(v time.Time) {
	o.ProvisionedAt = &v
}

// GetMetaPreverifiedId returns the MetaPreverifiedId field value if set, zero value otherwise.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetMetaPreverifiedId() string {
	if o == nil || IsNil(o.MetaPreverifiedId) {
		var ret string
		return ret
	}
	return *o.MetaPreverifiedId
}

// GetMetaPreverifiedIdOk returns a tuple with the MetaPreverifiedId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetMetaPreverifiedIdOk() (*string, bool) {
	if o == nil || IsNil(o.MetaPreverifiedId) {
		return nil, false
	}
	return o.MetaPreverifiedId, true
}

// HasMetaPreverifiedId returns a boolean if a field has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) HasMetaPreverifiedId() bool {
	if o != nil && !IsNil(o.MetaPreverifiedId) {
		return true
	}

	return false
}

// SetMetaPreverifiedId gets a reference to the given string and assigns it to the MetaPreverifiedId field.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) SetMetaPreverifiedId(v string) {
	o.MetaPreverifiedId = &v
}

// GetMetaVerificationStatus returns the MetaVerificationStatus field value if set, zero value otherwise.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetMetaVerificationStatus() string {
	if o == nil || IsNil(o.MetaVerificationStatus) {
		var ret string
		return ret
	}
	return *o.MetaVerificationStatus
}

// GetMetaVerificationStatusOk returns a tuple with the MetaVerificationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) GetMetaVerificationStatusOk() (*string, bool) {
	if o == nil || IsNil(o.MetaVerificationStatus) {
		return nil, false
	}
	return o.MetaVerificationStatus, true
}

// HasMetaVerificationStatus returns a boolean if a field has been set.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) HasMetaVerificationStatus() bool {
	if o != nil && !IsNil(o.MetaVerificationStatus) {
		return true
	}

	return false
}

// SetMetaVerificationStatus gets a reference to the given string and assigns it to the MetaVerificationStatus field.
func (o *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) SetMetaVerificationStatus(v string) {
	o.MetaVerificationStatus = &v
}

func (o PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.ProvisionedAt) {
		toSerialize["provisionedAt"] = o.ProvisionedAt
	}
	if !IsNil(o.MetaPreverifiedId) {
		toSerialize["metaPreverifiedId"] = o.MetaPreverifiedId
	}
	if !IsNil(o.MetaVerificationStatus) {
		toSerialize["metaVerificationStatus"] = o.MetaVerificationStatus
	}
	return toSerialize, nil
}

type NullablePurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber struct {
	value *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber
	isSet bool
}

func (v NullablePurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) Get() *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber {
	return v.value
}

func (v *NullablePurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) Set(val *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber(val *PurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) *NullablePurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber {
	return &NullablePurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber{value: val, isSet: true}
}

func (v NullablePurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseWhatsAppPhoneNumber200ResponseOneOf1PhoneNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
