/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CtwaAdRequestBodyVideo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CtwaAdRequestBodyVideo{}

// CtwaAdRequestBodyVideo Video creative for single-creative shape. Mutually exclusive with `imageUrl` and with `creatives[]`. Required on the single-creative shape if `imageUrl` is not supplied.
type CtwaAdRequestBodyVideo struct {
	Url string `json:"url"`
	// Required by Meta for every video creative. Used as the ad thumbnail.
	ThumbnailUrl string `json:"thumbnailUrl"`
}

type _CtwaAdRequestBodyVideo CtwaAdRequestBodyVideo

// NewCtwaAdRequestBodyVideo instantiates a new CtwaAdRequestBodyVideo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCtwaAdRequestBodyVideo(url string, thumbnailUrl string) *CtwaAdRequestBodyVideo {
	this := CtwaAdRequestBodyVideo{}
	this.Url = url
	this.ThumbnailUrl = thumbnailUrl
	return &this
}

// NewCtwaAdRequestBodyVideoWithDefaults instantiates a new CtwaAdRequestBodyVideo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCtwaAdRequestBodyVideoWithDefaults() *CtwaAdRequestBodyVideo {
	this := CtwaAdRequestBodyVideo{}
	return &this
}

// GetUrl returns the Url field value
func (o *CtwaAdRequestBodyVideo) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CtwaAdRequestBodyVideo) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CtwaAdRequestBodyVideo) SetUrl(v string) {
	o.Url = v
}

// GetThumbnailUrl returns the ThumbnailUrl field value
func (o *CtwaAdRequestBodyVideo) GetThumbnailUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThumbnailUrl
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value
// and a boolean to check if the value has been set.
func (o *CtwaAdRequestBodyVideo) GetThumbnailUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThumbnailUrl, true
}

// SetThumbnailUrl sets field value
func (o *CtwaAdRequestBodyVideo) SetThumbnailUrl(v string) {
	o.ThumbnailUrl = v
}

func (o CtwaAdRequestBodyVideo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CtwaAdRequestBodyVideo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["thumbnailUrl"] = o.ThumbnailUrl
	return toSerialize, nil
}

func (o *CtwaAdRequestBodyVideo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"thumbnailUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCtwaAdRequestBodyVideo := _CtwaAdRequestBodyVideo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCtwaAdRequestBodyVideo)

	if err != nil {
		return err
	}

	*o = CtwaAdRequestBodyVideo(varCtwaAdRequestBodyVideo)

	return err
}

type NullableCtwaAdRequestBodyVideo struct {
	value *CtwaAdRequestBodyVideo
	isSet bool
}

func (v NullableCtwaAdRequestBodyVideo) Get() *CtwaAdRequestBodyVideo {
	return v.value
}

func (v *NullableCtwaAdRequestBodyVideo) Set(val *CtwaAdRequestBodyVideo) {
	v.value = val
	v.isSet = true
}

func (v NullableCtwaAdRequestBodyVideo) IsSet() bool {
	return v.isSet
}

func (v *NullableCtwaAdRequestBodyVideo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCtwaAdRequestBodyVideo(val *CtwaAdRequestBodyVideo) *NullableCtwaAdRequestBodyVideo {
	return &NullableCtwaAdRequestBodyVideo{value: val, isSet: true}
}

func (v NullableCtwaAdRequestBodyVideo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCtwaAdRequestBodyVideo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
