/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EditInboxMessageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditInboxMessageRequest{}

// EditInboxMessageRequest struct for EditInboxMessageRequest
type EditInboxMessageRequest struct {
	// Social account ID
	AccountId string `json:"accountId"`
	// New message text
	Text        *string                             `json:"text,omitempty"`
	ReplyMarkup *EditInboxMessageRequestReplyMarkup `json:"replyMarkup,omitempty"`
}

type _EditInboxMessageRequest EditInboxMessageRequest

// NewEditInboxMessageRequest instantiates a new EditInboxMessageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditInboxMessageRequest(accountId string) *EditInboxMessageRequest {
	this := EditInboxMessageRequest{}
	this.AccountId = accountId
	return &this
}

// NewEditInboxMessageRequestWithDefaults instantiates a new EditInboxMessageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditInboxMessageRequestWithDefaults() *EditInboxMessageRequest {
	this := EditInboxMessageRequest{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *EditInboxMessageRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *EditInboxMessageRequest) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *EditInboxMessageRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *EditInboxMessageRequest) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditInboxMessageRequest) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *EditInboxMessageRequest) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *EditInboxMessageRequest) SetText(v string) {
	o.Text = &v
}

// GetReplyMarkup returns the ReplyMarkup field value if set, zero value otherwise.
func (o *EditInboxMessageRequest) GetReplyMarkup() EditInboxMessageRequestReplyMarkup {
	if o == nil || IsNil(o.ReplyMarkup) {
		var ret EditInboxMessageRequestReplyMarkup
		return ret
	}
	return *o.ReplyMarkup
}

// GetReplyMarkupOk returns a tuple with the ReplyMarkup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditInboxMessageRequest) GetReplyMarkupOk() (*EditInboxMessageRequestReplyMarkup, bool) {
	if o == nil || IsNil(o.ReplyMarkup) {
		return nil, false
	}
	return o.ReplyMarkup, true
}

// HasReplyMarkup returns a boolean if a field has been set.
func (o *EditInboxMessageRequest) HasReplyMarkup() bool {
	if o != nil && !IsNil(o.ReplyMarkup) {
		return true
	}

	return false
}

// SetReplyMarkup gets a reference to the given EditInboxMessageRequestReplyMarkup and assigns it to the ReplyMarkup field.
func (o *EditInboxMessageRequest) SetReplyMarkup(v EditInboxMessageRequestReplyMarkup) {
	o.ReplyMarkup = &v
}

func (o EditInboxMessageRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditInboxMessageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.ReplyMarkup) {
		toSerialize["replyMarkup"] = o.ReplyMarkup
	}
	return toSerialize, nil
}

func (o *EditInboxMessageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEditInboxMessageRequest := _EditInboxMessageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEditInboxMessageRequest)

	if err != nil {
		return err
	}

	*o = EditInboxMessageRequest(varEditInboxMessageRequest)

	return err
}

type NullableEditInboxMessageRequest struct {
	value *EditInboxMessageRequest
	isSet bool
}

func (v NullableEditInboxMessageRequest) Get() *EditInboxMessageRequest {
	return v.value
}

func (v *NullableEditInboxMessageRequest) Set(val *EditInboxMessageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEditInboxMessageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEditInboxMessageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditInboxMessageRequest(val *EditInboxMessageRequest) *NullableEditInboxMessageRequest {
	return &NullableEditInboxMessageRequest{value: val, isSet: true}
}

func (v NullableEditInboxMessageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditInboxMessageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
