/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.229.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
	"time"
)

// checks if the InstagramBusinessDiscoveryMediaInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstagramBusinessDiscoveryMediaInner{}

// InstagramBusinessDiscoveryMediaInner struct for InstagramBusinessDiscoveryMediaInner
type InstagramBusinessDiscoveryMediaInner struct {
	Id      *string        `json:"id,omitempty"`
	Caption NullableString `json:"caption,omitempty"`
	// IMAGE, VIDEO or CAROUSEL_ALBUM
	MediaType NullableString `json:"mediaType,omitempty"`
	// FEED or REELS
	MediaProductType NullableString `json:"mediaProductType,omitempty"`
	Timestamp        NullableTime   `json:"timestamp,omitempty"`
	Permalink        NullableString `json:"permalink,omitempty"`
	// Null when the owner hides like counts
	LikeCount     NullableInt32 `json:"likeCount,omitempty"`
	CommentsCount NullableInt32 `json:"commentsCount,omitempty"`
}

// NewInstagramBusinessDiscoveryMediaInner instantiates a new InstagramBusinessDiscoveryMediaInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstagramBusinessDiscoveryMediaInner() *InstagramBusinessDiscoveryMediaInner {
	this := InstagramBusinessDiscoveryMediaInner{}
	return &this
}

// NewInstagramBusinessDiscoveryMediaInnerWithDefaults instantiates a new InstagramBusinessDiscoveryMediaInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstagramBusinessDiscoveryMediaInnerWithDefaults() *InstagramBusinessDiscoveryMediaInner {
	this := InstagramBusinessDiscoveryMediaInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InstagramBusinessDiscoveryMediaInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstagramBusinessDiscoveryMediaInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InstagramBusinessDiscoveryMediaInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InstagramBusinessDiscoveryMediaInner) SetId(v string) {
	o.Id = &v
}

// GetCaption returns the Caption field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstagramBusinessDiscoveryMediaInner) GetCaption() string {
	if o == nil || IsNil(o.Caption.Get()) {
		var ret string
		return ret
	}
	return *o.Caption.Get()
}

// GetCaptionOk returns a tuple with the Caption field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstagramBusinessDiscoveryMediaInner) GetCaptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Caption.Get(), o.Caption.IsSet()
}

// HasCaption returns a boolean if a field has been set.
func (o *InstagramBusinessDiscoveryMediaInner) HasCaption() bool {
	if o != nil && o.Caption.IsSet() {
		return true
	}

	return false
}

// SetCaption gets a reference to the given NullableString and assigns it to the Caption field.
func (o *InstagramBusinessDiscoveryMediaInner) SetCaption(v string) {
	o.Caption.Set(&v)
}

// SetCaptionNil sets the value for Caption to be an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) SetCaptionNil() {
	o.Caption.Set(nil)
}

// UnsetCaption ensures that no value is present for Caption, not even an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) UnsetCaption() {
	o.Caption.Unset()
}

// GetMediaType returns the MediaType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstagramBusinessDiscoveryMediaInner) GetMediaType() string {
	if o == nil || IsNil(o.MediaType.Get()) {
		var ret string
		return ret
	}
	return *o.MediaType.Get()
}

// GetMediaTypeOk returns a tuple with the MediaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstagramBusinessDiscoveryMediaInner) GetMediaTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MediaType.Get(), o.MediaType.IsSet()
}

// HasMediaType returns a boolean if a field has been set.
func (o *InstagramBusinessDiscoveryMediaInner) HasMediaType() bool {
	if o != nil && o.MediaType.IsSet() {
		return true
	}

	return false
}

// SetMediaType gets a reference to the given NullableString and assigns it to the MediaType field.
func (o *InstagramBusinessDiscoveryMediaInner) SetMediaType(v string) {
	o.MediaType.Set(&v)
}

// SetMediaTypeNil sets the value for MediaType to be an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) SetMediaTypeNil() {
	o.MediaType.Set(nil)
}

// UnsetMediaType ensures that no value is present for MediaType, not even an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) UnsetMediaType() {
	o.MediaType.Unset()
}

// GetMediaProductType returns the MediaProductType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstagramBusinessDiscoveryMediaInner) GetMediaProductType() string {
	if o == nil || IsNil(o.MediaProductType.Get()) {
		var ret string
		return ret
	}
	return *o.MediaProductType.Get()
}

// GetMediaProductTypeOk returns a tuple with the MediaProductType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstagramBusinessDiscoveryMediaInner) GetMediaProductTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MediaProductType.Get(), o.MediaProductType.IsSet()
}

// HasMediaProductType returns a boolean if a field has been set.
func (o *InstagramBusinessDiscoveryMediaInner) HasMediaProductType() bool {
	if o != nil && o.MediaProductType.IsSet() {
		return true
	}

	return false
}

// SetMediaProductType gets a reference to the given NullableString and assigns it to the MediaProductType field.
func (o *InstagramBusinessDiscoveryMediaInner) SetMediaProductType(v string) {
	o.MediaProductType.Set(&v)
}

// SetMediaProductTypeNil sets the value for MediaProductType to be an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) SetMediaProductTypeNil() {
	o.MediaProductType.Set(nil)
}

// UnsetMediaProductType ensures that no value is present for MediaProductType, not even an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) UnsetMediaProductType() {
	o.MediaProductType.Unset()
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstagramBusinessDiscoveryMediaInner) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstagramBusinessDiscoveryMediaInner) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *InstagramBusinessDiscoveryMediaInner) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableTime and assigns it to the Timestamp field.
func (o *InstagramBusinessDiscoveryMediaInner) SetTimestamp(v time.Time) {
	o.Timestamp.Set(&v)
}

// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetPermalink returns the Permalink field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstagramBusinessDiscoveryMediaInner) GetPermalink() string {
	if o == nil || IsNil(o.Permalink.Get()) {
		var ret string
		return ret
	}
	return *o.Permalink.Get()
}

// GetPermalinkOk returns a tuple with the Permalink field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstagramBusinessDiscoveryMediaInner) GetPermalinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Permalink.Get(), o.Permalink.IsSet()
}

// HasPermalink returns a boolean if a field has been set.
func (o *InstagramBusinessDiscoveryMediaInner) HasPermalink() bool {
	if o != nil && o.Permalink.IsSet() {
		return true
	}

	return false
}

// SetPermalink gets a reference to the given NullableString and assigns it to the Permalink field.
func (o *InstagramBusinessDiscoveryMediaInner) SetPermalink(v string) {
	o.Permalink.Set(&v)
}

// SetPermalinkNil sets the value for Permalink to be an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) SetPermalinkNil() {
	o.Permalink.Set(nil)
}

// UnsetPermalink ensures that no value is present for Permalink, not even an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) UnsetPermalink() {
	o.Permalink.Unset()
}

// GetLikeCount returns the LikeCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstagramBusinessDiscoveryMediaInner) GetLikeCount() int32 {
	if o == nil || IsNil(o.LikeCount.Get()) {
		var ret int32
		return ret
	}
	return *o.LikeCount.Get()
}

// GetLikeCountOk returns a tuple with the LikeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstagramBusinessDiscoveryMediaInner) GetLikeCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LikeCount.Get(), o.LikeCount.IsSet()
}

// HasLikeCount returns a boolean if a field has been set.
func (o *InstagramBusinessDiscoveryMediaInner) HasLikeCount() bool {
	if o != nil && o.LikeCount.IsSet() {
		return true
	}

	return false
}

// SetLikeCount gets a reference to the given NullableInt32 and assigns it to the LikeCount field.
func (o *InstagramBusinessDiscoveryMediaInner) SetLikeCount(v int32) {
	o.LikeCount.Set(&v)
}

// SetLikeCountNil sets the value for LikeCount to be an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) SetLikeCountNil() {
	o.LikeCount.Set(nil)
}

// UnsetLikeCount ensures that no value is present for LikeCount, not even an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) UnsetLikeCount() {
	o.LikeCount.Unset()
}

// GetCommentsCount returns the CommentsCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstagramBusinessDiscoveryMediaInner) GetCommentsCount() int32 {
	if o == nil || IsNil(o.CommentsCount.Get()) {
		var ret int32
		return ret
	}
	return *o.CommentsCount.Get()
}

// GetCommentsCountOk returns a tuple with the CommentsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstagramBusinessDiscoveryMediaInner) GetCommentsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CommentsCount.Get(), o.CommentsCount.IsSet()
}

// HasCommentsCount returns a boolean if a field has been set.
func (o *InstagramBusinessDiscoveryMediaInner) HasCommentsCount() bool {
	if o != nil && o.CommentsCount.IsSet() {
		return true
	}

	return false
}

// SetCommentsCount gets a reference to the given NullableInt32 and assigns it to the CommentsCount field.
func (o *InstagramBusinessDiscoveryMediaInner) SetCommentsCount(v int32) {
	o.CommentsCount.Set(&v)
}

// SetCommentsCountNil sets the value for CommentsCount to be an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) SetCommentsCountNil() {
	o.CommentsCount.Set(nil)
}

// UnsetCommentsCount ensures that no value is present for CommentsCount, not even an explicit nil
func (o *InstagramBusinessDiscoveryMediaInner) UnsetCommentsCount() {
	o.CommentsCount.Unset()
}

func (o InstagramBusinessDiscoveryMediaInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstagramBusinessDiscoveryMediaInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Caption.IsSet() {
		toSerialize["caption"] = o.Caption.Get()
	}
	if o.MediaType.IsSet() {
		toSerialize["mediaType"] = o.MediaType.Get()
	}
	if o.MediaProductType.IsSet() {
		toSerialize["mediaProductType"] = o.MediaProductType.Get()
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.Permalink.IsSet() {
		toSerialize["permalink"] = o.Permalink.Get()
	}
	if o.LikeCount.IsSet() {
		toSerialize["likeCount"] = o.LikeCount.Get()
	}
	if o.CommentsCount.IsSet() {
		toSerialize["commentsCount"] = o.CommentsCount.Get()
	}
	return toSerialize, nil
}

type NullableInstagramBusinessDiscoveryMediaInner struct {
	value *InstagramBusinessDiscoveryMediaInner
	isSet bool
}

func (v NullableInstagramBusinessDiscoveryMediaInner) Get() *InstagramBusinessDiscoveryMediaInner {
	return v.value
}

func (v *NullableInstagramBusinessDiscoveryMediaInner) Set(val *InstagramBusinessDiscoveryMediaInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInstagramBusinessDiscoveryMediaInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInstagramBusinessDiscoveryMediaInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstagramBusinessDiscoveryMediaInner(val *InstagramBusinessDiscoveryMediaInner) *NullableInstagramBusinessDiscoveryMediaInner {
	return &NullableInstagramBusinessDiscoveryMediaInner{value: val, isSet: true}
}

func (v NullableInstagramBusinessDiscoveryMediaInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstagramBusinessDiscoveryMediaInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
