/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateBidStrategyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateBidStrategyRequest{}

// UpdateBidStrategyRequest struct for UpdateBidStrategyRequest
type UpdateBidStrategyRequest struct {
	// Google ads SocialAccount id.
	AccountId string `json:"accountId"`
	// Numeric Google Ads customer id (no dashes). Defaults to the account's connected customer.
	CustomerId *string  `json:"customerId,omitempty"`
	Name       *string  `json:"name,omitempty"`
	Type       *string  `json:"type,omitempty"`
	TargetCpa  *float32 `json:"targetCpa,omitempty"`
	TargetRoas *float32 `json:"targetRoas,omitempty"`
}

type _UpdateBidStrategyRequest UpdateBidStrategyRequest

// NewUpdateBidStrategyRequest instantiates a new UpdateBidStrategyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBidStrategyRequest(accountId string) *UpdateBidStrategyRequest {
	this := UpdateBidStrategyRequest{}
	this.AccountId = accountId
	return &this
}

// NewUpdateBidStrategyRequestWithDefaults instantiates a new UpdateBidStrategyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBidStrategyRequestWithDefaults() *UpdateBidStrategyRequest {
	this := UpdateBidStrategyRequest{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *UpdateBidStrategyRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *UpdateBidStrategyRequest) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *UpdateBidStrategyRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *UpdateBidStrategyRequest) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBidStrategyRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *UpdateBidStrategyRequest) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *UpdateBidStrategyRequest) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateBidStrategyRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBidStrategyRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateBidStrategyRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateBidStrategyRequest) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UpdateBidStrategyRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBidStrategyRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UpdateBidStrategyRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *UpdateBidStrategyRequest) SetType(v string) {
	o.Type = &v
}

// GetTargetCpa returns the TargetCpa field value if set, zero value otherwise.
func (o *UpdateBidStrategyRequest) GetTargetCpa() float32 {
	if o == nil || IsNil(o.TargetCpa) {
		var ret float32
		return ret
	}
	return *o.TargetCpa
}

// GetTargetCpaOk returns a tuple with the TargetCpa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBidStrategyRequest) GetTargetCpaOk() (*float32, bool) {
	if o == nil || IsNil(o.TargetCpa) {
		return nil, false
	}
	return o.TargetCpa, true
}

// HasTargetCpa returns a boolean if a field has been set.
func (o *UpdateBidStrategyRequest) HasTargetCpa() bool {
	if o != nil && !IsNil(o.TargetCpa) {
		return true
	}

	return false
}

// SetTargetCpa gets a reference to the given float32 and assigns it to the TargetCpa field.
func (o *UpdateBidStrategyRequest) SetTargetCpa(v float32) {
	o.TargetCpa = &v
}

// GetTargetRoas returns the TargetRoas field value if set, zero value otherwise.
func (o *UpdateBidStrategyRequest) GetTargetRoas() float32 {
	if o == nil || IsNil(o.TargetRoas) {
		var ret float32
		return ret
	}
	return *o.TargetRoas
}

// GetTargetRoasOk returns a tuple with the TargetRoas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBidStrategyRequest) GetTargetRoasOk() (*float32, bool) {
	if o == nil || IsNil(o.TargetRoas) {
		return nil, false
	}
	return o.TargetRoas, true
}

// HasTargetRoas returns a boolean if a field has been set.
func (o *UpdateBidStrategyRequest) HasTargetRoas() bool {
	if o != nil && !IsNil(o.TargetRoas) {
		return true
	}

	return false
}

// SetTargetRoas gets a reference to the given float32 and assigns it to the TargetRoas field.
func (o *UpdateBidStrategyRequest) SetTargetRoas(v float32) {
	o.TargetRoas = &v
}

func (o UpdateBidStrategyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateBidStrategyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.TargetCpa) {
		toSerialize["targetCpa"] = o.TargetCpa
	}
	if !IsNil(o.TargetRoas) {
		toSerialize["targetRoas"] = o.TargetRoas
	}
	return toSerialize, nil
}

func (o *UpdateBidStrategyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateBidStrategyRequest := _UpdateBidStrategyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateBidStrategyRequest)

	if err != nil {
		return err
	}

	*o = UpdateBidStrategyRequest(varUpdateBidStrategyRequest)

	return err
}

type NullableUpdateBidStrategyRequest struct {
	value *UpdateBidStrategyRequest
	isSet bool
}

func (v NullableUpdateBidStrategyRequest) Get() *UpdateBidStrategyRequest {
	return v.value
}

func (v *NullableUpdateBidStrategyRequest) Set(val *UpdateBidStrategyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBidStrategyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBidStrategyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBidStrategyRequest(val *UpdateBidStrategyRequest) *NullableUpdateBidStrategyRequest {
	return &NullableUpdateBidStrategyRequest{value: val, isSet: true}
}

func (v NullableUpdateBidStrategyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBidStrategyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
