/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the QueryAdInsights200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryAdInsights200Response{}

// QueryAdInsights200Response struct for QueryAdInsights200Response
type QueryAdInsights200Response struct {
	ObjectId *string                           `json:"objectId,omitempty"`
	Data     []map[string]interface{}          `json:"data,omitempty"`
	Paging   *QueryAdInsights200ResponsePaging `json:"paging,omitempty"`
}

// NewQueryAdInsights200Response instantiates a new QueryAdInsights200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryAdInsights200Response() *QueryAdInsights200Response {
	this := QueryAdInsights200Response{}
	return &this
}

// NewQueryAdInsights200ResponseWithDefaults instantiates a new QueryAdInsights200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryAdInsights200ResponseWithDefaults() *QueryAdInsights200Response {
	this := QueryAdInsights200Response{}
	return &this
}

// GetObjectId returns the ObjectId field value if set, zero value otherwise.
func (o *QueryAdInsights200Response) GetObjectId() string {
	if o == nil || IsNil(o.ObjectId) {
		var ret string
		return ret
	}
	return *o.ObjectId
}

// GetObjectIdOk returns a tuple with the ObjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAdInsights200Response) GetObjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectId) {
		return nil, false
	}
	return o.ObjectId, true
}

// HasObjectId returns a boolean if a field has been set.
func (o *QueryAdInsights200Response) HasObjectId() bool {
	if o != nil && !IsNil(o.ObjectId) {
		return true
	}

	return false
}

// SetObjectId gets a reference to the given string and assigns it to the ObjectId field.
func (o *QueryAdInsights200Response) SetObjectId(v string) {
	o.ObjectId = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *QueryAdInsights200Response) GetData() []map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAdInsights200Response) GetDataOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *QueryAdInsights200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []map[string]interface{} and assigns it to the Data field.
func (o *QueryAdInsights200Response) SetData(v []map[string]interface{}) {
	o.Data = v
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *QueryAdInsights200Response) GetPaging() QueryAdInsights200ResponsePaging {
	if o == nil || IsNil(o.Paging) {
		var ret QueryAdInsights200ResponsePaging
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAdInsights200Response) GetPagingOk() (*QueryAdInsights200ResponsePaging, bool) {
	if o == nil || IsNil(o.Paging) {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *QueryAdInsights200Response) HasPaging() bool {
	if o != nil && !IsNil(o.Paging) {
		return true
	}

	return false
}

// SetPaging gets a reference to the given QueryAdInsights200ResponsePaging and assigns it to the Paging field.
func (o *QueryAdInsights200Response) SetPaging(v QueryAdInsights200ResponsePaging) {
	o.Paging = &v
}

func (o QueryAdInsights200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryAdInsights200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObjectId) {
		toSerialize["objectId"] = o.ObjectId
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Paging) {
		toSerialize["paging"] = o.Paging
	}
	return toSerialize, nil
}

type NullableQueryAdInsights200Response struct {
	value *QueryAdInsights200Response
	isSet bool
}

func (v NullableQueryAdInsights200Response) Get() *QueryAdInsights200Response {
	return v.value
}

func (v *NullableQueryAdInsights200Response) Set(val *QueryAdInsights200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryAdInsights200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryAdInsights200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryAdInsights200Response(val *QueryAdInsights200Response) *NullableQueryAdInsights200Response {
	return &NullableQueryAdInsights200Response{value: val, isSet: true}
}

func (v NullableQueryAdInsights200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryAdInsights200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
