/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.249.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the GoogleNetworkSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoogleNetworkSettings{}

// GoogleNetworkSettings Google Search campaigns only. Which networks the campaign serves on besides Google Search. When omitted at creation, search partners are ON and the Display Network is OFF (the defaults Zernio has always used); on an update only the fields sent change.
type GoogleNetworkSettings struct {
	// campaign.network_settings.target_search_network
	SearchPartners *bool `json:"searchPartners,omitempty"`
	// campaign.network_settings.target_content_network (Search with Display expansion)
	DisplayNetwork *bool `json:"displayNetwork,omitempty"`
}

// NewGoogleNetworkSettings instantiates a new GoogleNetworkSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleNetworkSettings() *GoogleNetworkSettings {
	this := GoogleNetworkSettings{}
	return &this
}

// NewGoogleNetworkSettingsWithDefaults instantiates a new GoogleNetworkSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleNetworkSettingsWithDefaults() *GoogleNetworkSettings {
	this := GoogleNetworkSettings{}
	return &this
}

// GetSearchPartners returns the SearchPartners field value if set, zero value otherwise.
func (o *GoogleNetworkSettings) GetSearchPartners() bool {
	if o == nil || IsNil(o.SearchPartners) {
		var ret bool
		return ret
	}
	return *o.SearchPartners
}

// GetSearchPartnersOk returns a tuple with the SearchPartners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleNetworkSettings) GetSearchPartnersOk() (*bool, bool) {
	if o == nil || IsNil(o.SearchPartners) {
		return nil, false
	}
	return o.SearchPartners, true
}

// HasSearchPartners returns a boolean if a field has been set.
func (o *GoogleNetworkSettings) HasSearchPartners() bool {
	if o != nil && !IsNil(o.SearchPartners) {
		return true
	}

	return false
}

// SetSearchPartners gets a reference to the given bool and assigns it to the SearchPartners field.
func (o *GoogleNetworkSettings) SetSearchPartners(v bool) {
	o.SearchPartners = &v
}

// GetDisplayNetwork returns the DisplayNetwork field value if set, zero value otherwise.
func (o *GoogleNetworkSettings) GetDisplayNetwork() bool {
	if o == nil || IsNil(o.DisplayNetwork) {
		var ret bool
		return ret
	}
	return *o.DisplayNetwork
}

// GetDisplayNetworkOk returns a tuple with the DisplayNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleNetworkSettings) GetDisplayNetworkOk() (*bool, bool) {
	if o == nil || IsNil(o.DisplayNetwork) {
		return nil, false
	}
	return o.DisplayNetwork, true
}

// HasDisplayNetwork returns a boolean if a field has been set.
func (o *GoogleNetworkSettings) HasDisplayNetwork() bool {
	if o != nil && !IsNil(o.DisplayNetwork) {
		return true
	}

	return false
}

// SetDisplayNetwork gets a reference to the given bool and assigns it to the DisplayNetwork field.
func (o *GoogleNetworkSettings) SetDisplayNetwork(v bool) {
	o.DisplayNetwork = &v
}

func (o GoogleNetworkSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoogleNetworkSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SearchPartners) {
		toSerialize["searchPartners"] = o.SearchPartners
	}
	if !IsNil(o.DisplayNetwork) {
		toSerialize["displayNetwork"] = o.DisplayNetwork
	}
	return toSerialize, nil
}

type NullableGoogleNetworkSettings struct {
	value *GoogleNetworkSettings
	isSet bool
}

func (v NullableGoogleNetworkSettings) Get() *GoogleNetworkSettings {
	return v.value
}

func (v *NullableGoogleNetworkSettings) Set(val *GoogleNetworkSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleNetworkSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleNetworkSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleNetworkSettings(val *GoogleNetworkSettings) *NullableGoogleNetworkSettings {
	return &NullableGoogleNetworkSettings{value: val, isSet: true}
}

func (v NullableGoogleNetworkSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleNetworkSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
