/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
	"time"
)

// checks if the GetWhatsAppPhoneNumbers200ResponseConnectedInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWhatsAppPhoneNumbers200ResponseConnectedInner{}

// GetWhatsAppPhoneNumbers200ResponseConnectedInner struct for GetWhatsAppPhoneNumbers200ResponseConnectedInner
type GetWhatsAppPhoneNumbers200ResponseConnectedInner struct {
	AccountId   *string        `json:"accountId,omitempty"`
	PhoneNumber NullableString `json:"phoneNumber,omitempty"`
	DisplayName NullableString `json:"displayName,omitempty"`
	ProfileId   NullableString `json:"profileId,omitempty"`
	ConnectedAt NullableTime   `json:"connectedAt,omitempty"`
}

// NewGetWhatsAppPhoneNumbers200ResponseConnectedInner instantiates a new GetWhatsAppPhoneNumbers200ResponseConnectedInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWhatsAppPhoneNumbers200ResponseConnectedInner() *GetWhatsAppPhoneNumbers200ResponseConnectedInner {
	this := GetWhatsAppPhoneNumbers200ResponseConnectedInner{}
	return &this
}

// NewGetWhatsAppPhoneNumbers200ResponseConnectedInnerWithDefaults instantiates a new GetWhatsAppPhoneNumbers200ResponseConnectedInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWhatsAppPhoneNumbers200ResponseConnectedInnerWithDefaults() *GetWhatsAppPhoneNumbers200ResponseConnectedInner {
	this := GetWhatsAppPhoneNumbers200ResponseConnectedInner{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) SetAccountId(v string) {
	o.AccountId = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneNumber.Get()
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumber.Get(), o.PhoneNumber.IsSet()
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber.IsSet() {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given NullableString and assigns it to the PhoneNumber field.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) SetPhoneNumber(v string) {
	o.PhoneNumber.Set(&v)
}

// SetPhoneNumberNil sets the value for PhoneNumber to be an explicit nil
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) SetPhoneNumberNil() {
	o.PhoneNumber.Set(nil)
}

// UnsetPhoneNumber ensures that no value is present for PhoneNumber, not even an explicit nil
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) UnsetPhoneNumber() {
	o.PhoneNumber.Unset()
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetProfileId returns the ProfileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) GetProfileId() string {
	if o == nil || IsNil(o.ProfileId.Get()) {
		var ret string
		return ret
	}
	return *o.ProfileId.Get()
}

// GetProfileIdOk returns a tuple with the ProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) GetProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProfileId.Get(), o.ProfileId.IsSet()
}

// HasProfileId returns a boolean if a field has been set.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) HasProfileId() bool {
	if o != nil && o.ProfileId.IsSet() {
		return true
	}

	return false
}

// SetProfileId gets a reference to the given NullableString and assigns it to the ProfileId field.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) SetProfileId(v string) {
	o.ProfileId.Set(&v)
}

// SetProfileIdNil sets the value for ProfileId to be an explicit nil
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) SetProfileIdNil() {
	o.ProfileId.Set(nil)
}

// UnsetProfileId ensures that no value is present for ProfileId, not even an explicit nil
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) UnsetProfileId() {
	o.ProfileId.Unset()
}

// GetConnectedAt returns the ConnectedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) GetConnectedAt() time.Time {
	if o == nil || IsNil(o.ConnectedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ConnectedAt.Get()
}

// GetConnectedAtOk returns a tuple with the ConnectedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) GetConnectedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConnectedAt.Get(), o.ConnectedAt.IsSet()
}

// HasConnectedAt returns a boolean if a field has been set.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) HasConnectedAt() bool {
	if o != nil && o.ConnectedAt.IsSet() {
		return true
	}

	return false
}

// SetConnectedAt gets a reference to the given NullableTime and assigns it to the ConnectedAt field.
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) SetConnectedAt(v time.Time) {
	o.ConnectedAt.Set(&v)
}

// SetConnectedAtNil sets the value for ConnectedAt to be an explicit nil
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) SetConnectedAtNil() {
	o.ConnectedAt.Set(nil)
}

// UnsetConnectedAt ensures that no value is present for ConnectedAt, not even an explicit nil
func (o *GetWhatsAppPhoneNumbers200ResponseConnectedInner) UnsetConnectedAt() {
	o.ConnectedAt.Unset()
}

func (o GetWhatsAppPhoneNumbers200ResponseConnectedInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWhatsAppPhoneNumbers200ResponseConnectedInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if o.PhoneNumber.IsSet() {
		toSerialize["phoneNumber"] = o.PhoneNumber.Get()
	}
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	if o.ProfileId.IsSet() {
		toSerialize["profileId"] = o.ProfileId.Get()
	}
	if o.ConnectedAt.IsSet() {
		toSerialize["connectedAt"] = o.ConnectedAt.Get()
	}
	return toSerialize, nil
}

type NullableGetWhatsAppPhoneNumbers200ResponseConnectedInner struct {
	value *GetWhatsAppPhoneNumbers200ResponseConnectedInner
	isSet bool
}

func (v NullableGetWhatsAppPhoneNumbers200ResponseConnectedInner) Get() *GetWhatsAppPhoneNumbers200ResponseConnectedInner {
	return v.value
}

func (v *NullableGetWhatsAppPhoneNumbers200ResponseConnectedInner) Set(val *GetWhatsAppPhoneNumbers200ResponseConnectedInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWhatsAppPhoneNumbers200ResponseConnectedInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWhatsAppPhoneNumbers200ResponseConnectedInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWhatsAppPhoneNumbers200ResponseConnectedInner(val *GetWhatsAppPhoneNumbers200ResponseConnectedInner) *NullableGetWhatsAppPhoneNumbers200ResponseConnectedInner {
	return &NullableGetWhatsAppPhoneNumbers200ResponseConnectedInner{value: val, isSet: true}
}

func (v NullableGetWhatsAppPhoneNumbers200ResponseConnectedInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWhatsAppPhoneNumbers200ResponseConnectedInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
