/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.13.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WhatsAppTemplateLookupError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhatsAppTemplateLookupError{}

// WhatsAppTemplateLookupError struct for WhatsAppTemplateLookupError
type WhatsAppTemplateLookupError struct {
	Error         string                                    `json:"error"`
	Type          string                                    `json:"type"`
	Code          string                                    `json:"code"`
	Platform      string                                    `json:"platform"`
	PlatformError *WhatsAppTemplateLookupErrorPlatformError `json:"platformError,omitempty"`
	Details       WhatsAppTemplateLookupErrorDetails        `json:"details"`
}

type _WhatsAppTemplateLookupError WhatsAppTemplateLookupError

// NewWhatsAppTemplateLookupError instantiates a new WhatsAppTemplateLookupError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppTemplateLookupError(error_ string, type_ string, code string, platform string, details WhatsAppTemplateLookupErrorDetails) *WhatsAppTemplateLookupError {
	this := WhatsAppTemplateLookupError{}
	this.Error = error_
	this.Type = type_
	this.Code = code
	this.Platform = platform
	this.Details = details
	return &this
}

// NewWhatsAppTemplateLookupErrorWithDefaults instantiates a new WhatsAppTemplateLookupError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppTemplateLookupErrorWithDefaults() *WhatsAppTemplateLookupError {
	this := WhatsAppTemplateLookupError{}
	return &this
}

// GetError returns the Error field value
func (o *WhatsAppTemplateLookupError) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateLookupError) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *WhatsAppTemplateLookupError) SetError(v string) {
	o.Error = v
}

// GetType returns the Type field value
func (o *WhatsAppTemplateLookupError) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateLookupError) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WhatsAppTemplateLookupError) SetType(v string) {
	o.Type = v
}

// GetCode returns the Code field value
func (o *WhatsAppTemplateLookupError) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateLookupError) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *WhatsAppTemplateLookupError) SetCode(v string) {
	o.Code = v
}

// GetPlatform returns the Platform field value
func (o *WhatsAppTemplateLookupError) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateLookupError) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *WhatsAppTemplateLookupError) SetPlatform(v string) {
	o.Platform = v
}

// GetPlatformError returns the PlatformError field value if set, zero value otherwise.
func (o *WhatsAppTemplateLookupError) GetPlatformError() WhatsAppTemplateLookupErrorPlatformError {
	if o == nil || IsNil(o.PlatformError) {
		var ret WhatsAppTemplateLookupErrorPlatformError
		return ret
	}
	return *o.PlatformError
}

// GetPlatformErrorOk returns a tuple with the PlatformError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateLookupError) GetPlatformErrorOk() (*WhatsAppTemplateLookupErrorPlatformError, bool) {
	if o == nil || IsNil(o.PlatformError) {
		return nil, false
	}
	return o.PlatformError, true
}

// HasPlatformError returns a boolean if a field has been set.
func (o *WhatsAppTemplateLookupError) HasPlatformError() bool {
	if o != nil && !IsNil(o.PlatformError) {
		return true
	}

	return false
}

// SetPlatformError gets a reference to the given WhatsAppTemplateLookupErrorPlatformError and assigns it to the PlatformError field.
func (o *WhatsAppTemplateLookupError) SetPlatformError(v WhatsAppTemplateLookupErrorPlatformError) {
	o.PlatformError = &v
}

// GetDetails returns the Details field value
func (o *WhatsAppTemplateLookupError) GetDetails() WhatsAppTemplateLookupErrorDetails {
	if o == nil {
		var ret WhatsAppTemplateLookupErrorDetails
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateLookupError) GetDetailsOk() (*WhatsAppTemplateLookupErrorDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *WhatsAppTemplateLookupError) SetDetails(v WhatsAppTemplateLookupErrorDetails) {
	o.Details = v
}

func (o WhatsAppTemplateLookupError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhatsAppTemplateLookupError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["type"] = o.Type
	toSerialize["code"] = o.Code
	toSerialize["platform"] = o.Platform
	if !IsNil(o.PlatformError) {
		toSerialize["platformError"] = o.PlatformError
	}
	toSerialize["details"] = o.Details
	return toSerialize, nil
}

func (o *WhatsAppTemplateLookupError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"type",
		"code",
		"platform",
		"details",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWhatsAppTemplateLookupError := _WhatsAppTemplateLookupError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWhatsAppTemplateLookupError)

	if err != nil {
		return err
	}

	*o = WhatsAppTemplateLookupError(varWhatsAppTemplateLookupError)

	return err
}

type NullableWhatsAppTemplateLookupError struct {
	value *WhatsAppTemplateLookupError
	isSet bool
}

func (v NullableWhatsAppTemplateLookupError) Get() *WhatsAppTemplateLookupError {
	return v.value
}

func (v *NullableWhatsAppTemplateLookupError) Set(val *WhatsAppTemplateLookupError) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppTemplateLookupError) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppTemplateLookupError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppTemplateLookupError(val *WhatsAppTemplateLookupError) *NullableWhatsAppTemplateLookupError {
	return &NullableWhatsAppTemplateLookupError{value: val, isSet: true}
}

func (v NullableWhatsAppTemplateLookupError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppTemplateLookupError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
