/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.188.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the ListCommercePriceLists200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCommercePriceLists200Response{}

// ListCommercePriceLists200Response struct for ListCommercePriceLists200Response
type ListCommercePriceLists200Response struct {
	PriceLists []CommercePriceList `json:"priceLists,omitempty"`
}

// NewListCommercePriceLists200Response instantiates a new ListCommercePriceLists200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCommercePriceLists200Response() *ListCommercePriceLists200Response {
	this := ListCommercePriceLists200Response{}
	return &this
}

// NewListCommercePriceLists200ResponseWithDefaults instantiates a new ListCommercePriceLists200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCommercePriceLists200ResponseWithDefaults() *ListCommercePriceLists200Response {
	this := ListCommercePriceLists200Response{}
	return &this
}

// GetPriceLists returns the PriceLists field value if set, zero value otherwise.
func (o *ListCommercePriceLists200Response) GetPriceLists() []CommercePriceList {
	if o == nil || IsNil(o.PriceLists) {
		var ret []CommercePriceList
		return ret
	}
	return o.PriceLists
}

// GetPriceListsOk returns a tuple with the PriceLists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommercePriceLists200Response) GetPriceListsOk() ([]CommercePriceList, bool) {
	if o == nil || IsNil(o.PriceLists) {
		return nil, false
	}
	return o.PriceLists, true
}

// HasPriceLists returns a boolean if a field has been set.
func (o *ListCommercePriceLists200Response) HasPriceLists() bool {
	if o != nil && !IsNil(o.PriceLists) {
		return true
	}

	return false
}

// SetPriceLists gets a reference to the given []CommercePriceList and assigns it to the PriceLists field.
func (o *ListCommercePriceLists200Response) SetPriceLists(v []CommercePriceList) {
	o.PriceLists = v
}

func (o ListCommercePriceLists200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCommercePriceLists200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PriceLists) {
		toSerialize["priceLists"] = o.PriceLists
	}
	return toSerialize, nil
}

type NullableListCommercePriceLists200Response struct {
	value *ListCommercePriceLists200Response
	isSet bool
}

func (v NullableListCommercePriceLists200Response) Get() *ListCommercePriceLists200Response {
	return v.value
}

func (v *NullableListCommercePriceLists200Response) Set(val *ListCommercePriceLists200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListCommercePriceLists200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListCommercePriceLists200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCommercePriceLists200Response(val *ListCommercePriceLists200Response) *NullableListCommercePriceLists200Response {
	return &NullableListCommercePriceLists200Response{value: val, isSet: true}
}

func (v NullableListCommercePriceLists200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCommercePriceLists200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
