/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the WebhookPayloadAccountConnected type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookPayloadAccountConnected{}

// WebhookPayloadAccountConnected Webhook payload for account connected events
type WebhookPayloadAccountConnected struct {
	// Stable webhook event ID
	Id        string                                `json:"id"`
	Event     string                                `json:"event"`
	Account   WebhookPayloadAccountConnectedAccount `json:"account"`
	Timestamp time.Time                             `json:"timestamp"`
}

type _WebhookPayloadAccountConnected WebhookPayloadAccountConnected

// NewWebhookPayloadAccountConnected instantiates a new WebhookPayloadAccountConnected object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookPayloadAccountConnected(id string, event string, account WebhookPayloadAccountConnectedAccount, timestamp time.Time) *WebhookPayloadAccountConnected {
	this := WebhookPayloadAccountConnected{}
	this.Id = id
	this.Event = event
	this.Account = account
	this.Timestamp = timestamp
	return &this
}

// NewWebhookPayloadAccountConnectedWithDefaults instantiates a new WebhookPayloadAccountConnected object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookPayloadAccountConnectedWithDefaults() *WebhookPayloadAccountConnected {
	this := WebhookPayloadAccountConnected{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookPayloadAccountConnected) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookPayloadAccountConnected) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookPayloadAccountConnected) SetId(v string) {
	o.Id = v
}

// GetEvent returns the Event field value
func (o *WebhookPayloadAccountConnected) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *WebhookPayloadAccountConnected) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *WebhookPayloadAccountConnected) SetEvent(v string) {
	o.Event = v
}

// GetAccount returns the Account field value
func (o *WebhookPayloadAccountConnected) GetAccount() WebhookPayloadAccountConnectedAccount {
	if o == nil {
		var ret WebhookPayloadAccountConnectedAccount
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *WebhookPayloadAccountConnected) GetAccountOk() (*WebhookPayloadAccountConnectedAccount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *WebhookPayloadAccountConnected) SetAccount(v WebhookPayloadAccountConnectedAccount) {
	o.Account = v
}

// GetTimestamp returns the Timestamp field value
func (o *WebhookPayloadAccountConnected) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *WebhookPayloadAccountConnected) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *WebhookPayloadAccountConnected) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

func (o WebhookPayloadAccountConnected) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookPayloadAccountConnected) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["event"] = o.Event
	toSerialize["account"] = o.Account
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *WebhookPayloadAccountConnected) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"event",
		"account",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookPayloadAccountConnected := _WebhookPayloadAccountConnected{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookPayloadAccountConnected)

	if err != nil {
		return err
	}

	*o = WebhookPayloadAccountConnected(varWebhookPayloadAccountConnected)

	return err
}

type NullableWebhookPayloadAccountConnected struct {
	value *WebhookPayloadAccountConnected
	isSet bool
}

func (v NullableWebhookPayloadAccountConnected) Get() *WebhookPayloadAccountConnected {
	return v.value
}

func (v *NullableWebhookPayloadAccountConnected) Set(val *WebhookPayloadAccountConnected) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookPayloadAccountConnected) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookPayloadAccountConnected) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookPayloadAccountConnected(val *WebhookPayloadAccountConnected) *NullableWebhookPayloadAccountConnected {
	return &NullableWebhookPayloadAccountConnected{value: val, isSet: true}
}

func (v NullableWebhookPayloadAccountConnected) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookPayloadAccountConnected) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
