/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.220.1
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GoogleDemandGenInputCarouselCardsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoogleDemandGenInputCarouselCardsInner{}

// GoogleDemandGenInputCarouselCardsInner struct for GoogleDemandGenInputCarouselCardsInner
type GoogleDemandGenInputCarouselCardsInner struct {
	Headline string `json:"headline"`
	// Defaults to demandGen.finalUrl.
	FinalUrl     *string                                      `json:"finalUrl,omitempty"`
	CallToAction *string                                      `json:"callToAction,omitempty"`
	Images       GoogleDemandGenInputCarouselCardsInnerImages `json:"images"`
}

type _GoogleDemandGenInputCarouselCardsInner GoogleDemandGenInputCarouselCardsInner

// NewGoogleDemandGenInputCarouselCardsInner instantiates a new GoogleDemandGenInputCarouselCardsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleDemandGenInputCarouselCardsInner(headline string, images GoogleDemandGenInputCarouselCardsInnerImages) *GoogleDemandGenInputCarouselCardsInner {
	this := GoogleDemandGenInputCarouselCardsInner{}
	this.Headline = headline
	this.Images = images
	return &this
}

// NewGoogleDemandGenInputCarouselCardsInnerWithDefaults instantiates a new GoogleDemandGenInputCarouselCardsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleDemandGenInputCarouselCardsInnerWithDefaults() *GoogleDemandGenInputCarouselCardsInner {
	this := GoogleDemandGenInputCarouselCardsInner{}
	return &this
}

// GetHeadline returns the Headline field value
func (o *GoogleDemandGenInputCarouselCardsInner) GetHeadline() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Headline
}

// GetHeadlineOk returns a tuple with the Headline field value
// and a boolean to check if the value has been set.
func (o *GoogleDemandGenInputCarouselCardsInner) GetHeadlineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Headline, true
}

// SetHeadline sets field value
func (o *GoogleDemandGenInputCarouselCardsInner) SetHeadline(v string) {
	o.Headline = v
}

// GetFinalUrl returns the FinalUrl field value if set, zero value otherwise.
func (o *GoogleDemandGenInputCarouselCardsInner) GetFinalUrl() string {
	if o == nil || IsNil(o.FinalUrl) {
		var ret string
		return ret
	}
	return *o.FinalUrl
}

// GetFinalUrlOk returns a tuple with the FinalUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleDemandGenInputCarouselCardsInner) GetFinalUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FinalUrl) {
		return nil, false
	}
	return o.FinalUrl, true
}

// HasFinalUrl returns a boolean if a field has been set.
func (o *GoogleDemandGenInputCarouselCardsInner) HasFinalUrl() bool {
	if o != nil && !IsNil(o.FinalUrl) {
		return true
	}

	return false
}

// SetFinalUrl gets a reference to the given string and assigns it to the FinalUrl field.
func (o *GoogleDemandGenInputCarouselCardsInner) SetFinalUrl(v string) {
	o.FinalUrl = &v
}

// GetCallToAction returns the CallToAction field value if set, zero value otherwise.
func (o *GoogleDemandGenInputCarouselCardsInner) GetCallToAction() string {
	if o == nil || IsNil(o.CallToAction) {
		var ret string
		return ret
	}
	return *o.CallToAction
}

// GetCallToActionOk returns a tuple with the CallToAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleDemandGenInputCarouselCardsInner) GetCallToActionOk() (*string, bool) {
	if o == nil || IsNil(o.CallToAction) {
		return nil, false
	}
	return o.CallToAction, true
}

// HasCallToAction returns a boolean if a field has been set.
func (o *GoogleDemandGenInputCarouselCardsInner) HasCallToAction() bool {
	if o != nil && !IsNil(o.CallToAction) {
		return true
	}

	return false
}

// SetCallToAction gets a reference to the given string and assigns it to the CallToAction field.
func (o *GoogleDemandGenInputCarouselCardsInner) SetCallToAction(v string) {
	o.CallToAction = &v
}

// GetImages returns the Images field value
func (o *GoogleDemandGenInputCarouselCardsInner) GetImages() GoogleDemandGenInputCarouselCardsInnerImages {
	if o == nil {
		var ret GoogleDemandGenInputCarouselCardsInnerImages
		return ret
	}

	return o.Images
}

// GetImagesOk returns a tuple with the Images field value
// and a boolean to check if the value has been set.
func (o *GoogleDemandGenInputCarouselCardsInner) GetImagesOk() (*GoogleDemandGenInputCarouselCardsInnerImages, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Images, true
}

// SetImages sets field value
func (o *GoogleDemandGenInputCarouselCardsInner) SetImages(v GoogleDemandGenInputCarouselCardsInnerImages) {
	o.Images = v
}

func (o GoogleDemandGenInputCarouselCardsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoogleDemandGenInputCarouselCardsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["headline"] = o.Headline
	if !IsNil(o.FinalUrl) {
		toSerialize["finalUrl"] = o.FinalUrl
	}
	if !IsNil(o.CallToAction) {
		toSerialize["callToAction"] = o.CallToAction
	}
	toSerialize["images"] = o.Images
	return toSerialize, nil
}

func (o *GoogleDemandGenInputCarouselCardsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"headline",
		"images",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGoogleDemandGenInputCarouselCardsInner := _GoogleDemandGenInputCarouselCardsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGoogleDemandGenInputCarouselCardsInner)

	if err != nil {
		return err
	}

	*o = GoogleDemandGenInputCarouselCardsInner(varGoogleDemandGenInputCarouselCardsInner)

	return err
}

type NullableGoogleDemandGenInputCarouselCardsInner struct {
	value *GoogleDemandGenInputCarouselCardsInner
	isSet bool
}

func (v NullableGoogleDemandGenInputCarouselCardsInner) Get() *GoogleDemandGenInputCarouselCardsInner {
	return v.value
}

func (v *NullableGoogleDemandGenInputCarouselCardsInner) Set(val *GoogleDemandGenInputCarouselCardsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleDemandGenInputCarouselCardsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleDemandGenInputCarouselCardsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleDemandGenInputCarouselCardsInner(val *GoogleDemandGenInputCarouselCardsInner) *NullableGoogleDemandGenInputCarouselCardsInner {
	return &NullableGoogleDemandGenInputCarouselCardsInner{value: val, isSet: true}
}

func (v NullableGoogleDemandGenInputCarouselCardsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleDemandGenInputCarouselCardsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
