/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the UpdateInboxConversation200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateInboxConversation200Response{}

// UpdateInboxConversation200Response struct for UpdateInboxConversation200Response
type UpdateInboxConversation200Response struct {
	Success *bool                                   `json:"success,omitempty"`
	Data    *UpdateInboxConversation200ResponseData `json:"data,omitempty"`
}

// NewUpdateInboxConversation200Response instantiates a new UpdateInboxConversation200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateInboxConversation200Response() *UpdateInboxConversation200Response {
	this := UpdateInboxConversation200Response{}
	return &this
}

// NewUpdateInboxConversation200ResponseWithDefaults instantiates a new UpdateInboxConversation200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateInboxConversation200ResponseWithDefaults() *UpdateInboxConversation200Response {
	this := UpdateInboxConversation200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UpdateInboxConversation200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateInboxConversation200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UpdateInboxConversation200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UpdateInboxConversation200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateInboxConversation200Response) GetData() UpdateInboxConversation200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret UpdateInboxConversation200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateInboxConversation200Response) GetDataOk() (*UpdateInboxConversation200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateInboxConversation200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given UpdateInboxConversation200ResponseData and assigns it to the Data field.
func (o *UpdateInboxConversation200Response) SetData(v UpdateInboxConversation200ResponseData) {
	o.Data = &v
}

func (o UpdateInboxConversation200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateInboxConversation200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableUpdateInboxConversation200Response struct {
	value *UpdateInboxConversation200Response
	isSet bool
}

func (v NullableUpdateInboxConversation200Response) Get() *UpdateInboxConversation200Response {
	return v.value
}

func (v *NullableUpdateInboxConversation200Response) Set(val *UpdateInboxConversation200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateInboxConversation200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateInboxConversation200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateInboxConversation200Response(val *UpdateInboxConversation200Response) *NullableUpdateInboxConversation200Response {
	return &NullableUpdateInboxConversation200Response{value: val, isSet: true}
}

func (v NullableUpdateInboxConversation200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateInboxConversation200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
