/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.1.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LinkedInLeadFormPlatformDataConsentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkedInLeadFormPlatformDataConsentsInner{}

// LinkedInLeadFormPlatformDataConsentsInner struct for LinkedInLeadFormPlatformDataConsentsInner
type LinkedInLeadFormPlatformDataConsentsInner struct {
	Description string `json:"description"`
	// Whether the viewer must tick this consent to submit. Defaults to false.
	Required *bool `json:"required,omitempty"`
}

type _LinkedInLeadFormPlatformDataConsentsInner LinkedInLeadFormPlatformDataConsentsInner

// NewLinkedInLeadFormPlatformDataConsentsInner instantiates a new LinkedInLeadFormPlatformDataConsentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkedInLeadFormPlatformDataConsentsInner(description string) *LinkedInLeadFormPlatformDataConsentsInner {
	this := LinkedInLeadFormPlatformDataConsentsInner{}
	this.Description = description
	var required bool = false
	this.Required = &required
	return &this
}

// NewLinkedInLeadFormPlatformDataConsentsInnerWithDefaults instantiates a new LinkedInLeadFormPlatformDataConsentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkedInLeadFormPlatformDataConsentsInnerWithDefaults() *LinkedInLeadFormPlatformDataConsentsInner {
	this := LinkedInLeadFormPlatformDataConsentsInner{}
	var required bool = false
	this.Required = &required
	return &this
}

// GetDescription returns the Description field value
func (o *LinkedInLeadFormPlatformDataConsentsInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *LinkedInLeadFormPlatformDataConsentsInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *LinkedInLeadFormPlatformDataConsentsInner) SetDescription(v string) {
	o.Description = v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *LinkedInLeadFormPlatformDataConsentsInner) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkedInLeadFormPlatformDataConsentsInner) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *LinkedInLeadFormPlatformDataConsentsInner) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *LinkedInLeadFormPlatformDataConsentsInner) SetRequired(v bool) {
	o.Required = &v
}

func (o LinkedInLeadFormPlatformDataConsentsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkedInLeadFormPlatformDataConsentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	return toSerialize, nil
}

func (o *LinkedInLeadFormPlatformDataConsentsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinkedInLeadFormPlatformDataConsentsInner := _LinkedInLeadFormPlatformDataConsentsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLinkedInLeadFormPlatformDataConsentsInner)

	if err != nil {
		return err
	}

	*o = LinkedInLeadFormPlatformDataConsentsInner(varLinkedInLeadFormPlatformDataConsentsInner)

	return err
}

type NullableLinkedInLeadFormPlatformDataConsentsInner struct {
	value *LinkedInLeadFormPlatformDataConsentsInner
	isSet bool
}

func (v NullableLinkedInLeadFormPlatformDataConsentsInner) Get() *LinkedInLeadFormPlatformDataConsentsInner {
	return v.value
}

func (v *NullableLinkedInLeadFormPlatformDataConsentsInner) Set(val *LinkedInLeadFormPlatformDataConsentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkedInLeadFormPlatformDataConsentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkedInLeadFormPlatformDataConsentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkedInLeadFormPlatformDataConsentsInner(val *LinkedInLeadFormPlatformDataConsentsInner) *NullableLinkedInLeadFormPlatformDataConsentsInner {
	return &NullableLinkedInLeadFormPlatformDataConsentsInner{value: val, isSet: true}
}

func (v NullableLinkedInLeadFormPlatformDataConsentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkedInLeadFormPlatformDataConsentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
