/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the GetWhatsAppCallEstimate200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWhatsAppCallEstimate200Response{}

// GetWhatsAppCallEstimate200Response struct for GetWhatsAppCallEstimate200Response
type GetWhatsAppCallEstimate200Response struct {
	DestinationCountry NullableString                               `json:"destinationCountry,omitempty"`
	PerMinuteUsd       *float32                                     `json:"perMinuteUsd,omitempty"`
	Breakdown          *GetWhatsAppCallEstimate200ResponseBreakdown `json:"breakdown,omitempty"`
}

// NewGetWhatsAppCallEstimate200Response instantiates a new GetWhatsAppCallEstimate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWhatsAppCallEstimate200Response() *GetWhatsAppCallEstimate200Response {
	this := GetWhatsAppCallEstimate200Response{}
	return &this
}

// NewGetWhatsAppCallEstimate200ResponseWithDefaults instantiates a new GetWhatsAppCallEstimate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWhatsAppCallEstimate200ResponseWithDefaults() *GetWhatsAppCallEstimate200Response {
	this := GetWhatsAppCallEstimate200Response{}
	return &this
}

// GetDestinationCountry returns the DestinationCountry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetWhatsAppCallEstimate200Response) GetDestinationCountry() string {
	if o == nil || IsNil(o.DestinationCountry.Get()) {
		var ret string
		return ret
	}
	return *o.DestinationCountry.Get()
}

// GetDestinationCountryOk returns a tuple with the DestinationCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetWhatsAppCallEstimate200Response) GetDestinationCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DestinationCountry.Get(), o.DestinationCountry.IsSet()
}

// HasDestinationCountry returns a boolean if a field has been set.
func (o *GetWhatsAppCallEstimate200Response) HasDestinationCountry() bool {
	if o != nil && o.DestinationCountry.IsSet() {
		return true
	}

	return false
}

// SetDestinationCountry gets a reference to the given NullableString and assigns it to the DestinationCountry field.
func (o *GetWhatsAppCallEstimate200Response) SetDestinationCountry(v string) {
	o.DestinationCountry.Set(&v)
}

// SetDestinationCountryNil sets the value for DestinationCountry to be an explicit nil
func (o *GetWhatsAppCallEstimate200Response) SetDestinationCountryNil() {
	o.DestinationCountry.Set(nil)
}

// UnsetDestinationCountry ensures that no value is present for DestinationCountry, not even an explicit nil
func (o *GetWhatsAppCallEstimate200Response) UnsetDestinationCountry() {
	o.DestinationCountry.Unset()
}

// GetPerMinuteUsd returns the PerMinuteUsd field value if set, zero value otherwise.
func (o *GetWhatsAppCallEstimate200Response) GetPerMinuteUsd() float32 {
	if o == nil || IsNil(o.PerMinuteUsd) {
		var ret float32
		return ret
	}
	return *o.PerMinuteUsd
}

// GetPerMinuteUsdOk returns a tuple with the PerMinuteUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWhatsAppCallEstimate200Response) GetPerMinuteUsdOk() (*float32, bool) {
	if o == nil || IsNil(o.PerMinuteUsd) {
		return nil, false
	}
	return o.PerMinuteUsd, true
}

// HasPerMinuteUsd returns a boolean if a field has been set.
func (o *GetWhatsAppCallEstimate200Response) HasPerMinuteUsd() bool {
	if o != nil && !IsNil(o.PerMinuteUsd) {
		return true
	}

	return false
}

// SetPerMinuteUsd gets a reference to the given float32 and assigns it to the PerMinuteUsd field.
func (o *GetWhatsAppCallEstimate200Response) SetPerMinuteUsd(v float32) {
	o.PerMinuteUsd = &v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *GetWhatsAppCallEstimate200Response) GetBreakdown() GetWhatsAppCallEstimate200ResponseBreakdown {
	if o == nil || IsNil(o.Breakdown) {
		var ret GetWhatsAppCallEstimate200ResponseBreakdown
		return ret
	}
	return *o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWhatsAppCallEstimate200Response) GetBreakdownOk() (*GetWhatsAppCallEstimate200ResponseBreakdown, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *GetWhatsAppCallEstimate200Response) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given GetWhatsAppCallEstimate200ResponseBreakdown and assigns it to the Breakdown field.
func (o *GetWhatsAppCallEstimate200Response) SetBreakdown(v GetWhatsAppCallEstimate200ResponseBreakdown) {
	o.Breakdown = &v
}

func (o GetWhatsAppCallEstimate200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWhatsAppCallEstimate200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DestinationCountry.IsSet() {
		toSerialize["destinationCountry"] = o.DestinationCountry.Get()
	}
	if !IsNil(o.PerMinuteUsd) {
		toSerialize["perMinuteUsd"] = o.PerMinuteUsd
	}
	if !IsNil(o.Breakdown) {
		toSerialize["breakdown"] = o.Breakdown
	}
	return toSerialize, nil
}

type NullableGetWhatsAppCallEstimate200Response struct {
	value *GetWhatsAppCallEstimate200Response
	isSet bool
}

func (v NullableGetWhatsAppCallEstimate200Response) Get() *GetWhatsAppCallEstimate200Response {
	return v.value
}

func (v *NullableGetWhatsAppCallEstimate200Response) Set(val *GetWhatsAppCallEstimate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWhatsAppCallEstimate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWhatsAppCallEstimate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWhatsAppCallEstimate200Response(val *GetWhatsAppCallEstimate200Response) *NullableGetWhatsAppCallEstimate200Response {
	return &NullableGetWhatsAppCallEstimate200Response{value: val, isSet: true}
}

func (v NullableGetWhatsAppCallEstimate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWhatsAppCallEstimate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
