/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the SetConversationThreadControl200ResponseControl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetConversationThreadControl200ResponseControl{}

// SetConversationThreadControl200ResponseControl struct for SetConversationThreadControl200ResponseControl
type SetConversationThreadControl200ResponseControl struct {
	Owner *string `json:"owner,omitempty"`
}

// NewSetConversationThreadControl200ResponseControl instantiates a new SetConversationThreadControl200ResponseControl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetConversationThreadControl200ResponseControl() *SetConversationThreadControl200ResponseControl {
	this := SetConversationThreadControl200ResponseControl{}
	return &this
}

// NewSetConversationThreadControl200ResponseControlWithDefaults instantiates a new SetConversationThreadControl200ResponseControl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetConversationThreadControl200ResponseControlWithDefaults() *SetConversationThreadControl200ResponseControl {
	this := SetConversationThreadControl200ResponseControl{}
	return &this
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *SetConversationThreadControl200ResponseControl) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetConversationThreadControl200ResponseControl) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *SetConversationThreadControl200ResponseControl) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *SetConversationThreadControl200ResponseControl) SetOwner(v string) {
	o.Owner = &v
}

func (o SetConversationThreadControl200ResponseControl) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetConversationThreadControl200ResponseControl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	return toSerialize, nil
}

type NullableSetConversationThreadControl200ResponseControl struct {
	value *SetConversationThreadControl200ResponseControl
	isSet bool
}

func (v NullableSetConversationThreadControl200ResponseControl) Get() *SetConversationThreadControl200ResponseControl {
	return v.value
}

func (v *NullableSetConversationThreadControl200ResponseControl) Set(val *SetConversationThreadControl200ResponseControl) {
	v.value = val
	v.isSet = true
}

func (v NullableSetConversationThreadControl200ResponseControl) IsSet() bool {
	return v.isSet
}

func (v *NullableSetConversationThreadControl200ResponseControl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetConversationThreadControl200ResponseControl(val *SetConversationThreadControl200ResponseControl) *NullableSetConversationThreadControl200ResponseControl {
	return &NullableSetConversationThreadControl200ResponseControl{value: val, isSet: true}
}

func (v NullableSetConversationThreadControl200ResponseControl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetConversationThreadControl200ResponseControl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
