/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).

API version: 1.0.4
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
	"fmt"
)

// checks if the GooglePmaxAssetGroupInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GooglePmaxAssetGroupInput{}

// GooglePmaxAssetGroupInput Google Performance Max creative assets. At least one description must be 60 characters or fewer. Texts within each list must be distinct.
type GooglePmaxAssetGroupInput struct {
	// Defaults to the request name.
	Name *string `json:"name,omitempty"`
	// Required destination URL.
	FinalUrl     string   `json:"finalUrl" validate:"regexp=^https?:\\/\\/"`
	Headlines    []string `json:"headlines"`
	LongHeadline string   `json:"longHeadline"`
	// At least one description must be 60 characters or fewer.
	Descriptions []string                        `json:"descriptions"`
	BusinessName string                          `json:"businessName"`
	Images       GooglePmaxAssetGroupInputImages `json:"images"`
	// Optional existing YouTube video id. Google can generate video when omitted. Video uploads and arbitrary video URLs are not supported.
	YoutubeVideoId       *string `json:"youtubeVideoId,omitempty" validate:"regexp=^[A-Za-z0-9_-]{11}$"`
	AdditionalProperties map[string]interface{}
}

type _GooglePmaxAssetGroupInput GooglePmaxAssetGroupInput

// NewGooglePmaxAssetGroupInput instantiates a new GooglePmaxAssetGroupInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGooglePmaxAssetGroupInput(finalUrl string, headlines []string, longHeadline string, descriptions []string, businessName string, images GooglePmaxAssetGroupInputImages) *GooglePmaxAssetGroupInput {
	this := GooglePmaxAssetGroupInput{}
	this.FinalUrl = finalUrl
	this.Headlines = headlines
	this.LongHeadline = longHeadline
	this.Descriptions = descriptions
	this.BusinessName = businessName
	this.Images = images
	return &this
}

// NewGooglePmaxAssetGroupInputWithDefaults instantiates a new GooglePmaxAssetGroupInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGooglePmaxAssetGroupInputWithDefaults() *GooglePmaxAssetGroupInput {
	this := GooglePmaxAssetGroupInput{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GooglePmaxAssetGroupInput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GooglePmaxAssetGroupInput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GooglePmaxAssetGroupInput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GooglePmaxAssetGroupInput) SetName(v string) {
	o.Name = &v
}

// GetFinalUrl returns the FinalUrl field value
func (o *GooglePmaxAssetGroupInput) GetFinalUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FinalUrl
}

// GetFinalUrlOk returns a tuple with the FinalUrl field value
// and a boolean to check if the value has been set.
func (o *GooglePmaxAssetGroupInput) GetFinalUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FinalUrl, true
}

// SetFinalUrl sets field value
func (o *GooglePmaxAssetGroupInput) SetFinalUrl(v string) {
	o.FinalUrl = v
}

// GetHeadlines returns the Headlines field value
func (o *GooglePmaxAssetGroupInput) GetHeadlines() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Headlines
}

// GetHeadlinesOk returns a tuple with the Headlines field value
// and a boolean to check if the value has been set.
func (o *GooglePmaxAssetGroupInput) GetHeadlinesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Headlines, true
}

// SetHeadlines sets field value
func (o *GooglePmaxAssetGroupInput) SetHeadlines(v []string) {
	o.Headlines = v
}

// GetLongHeadline returns the LongHeadline field value
func (o *GooglePmaxAssetGroupInput) GetLongHeadline() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LongHeadline
}

// GetLongHeadlineOk returns a tuple with the LongHeadline field value
// and a boolean to check if the value has been set.
func (o *GooglePmaxAssetGroupInput) GetLongHeadlineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LongHeadline, true
}

// SetLongHeadline sets field value
func (o *GooglePmaxAssetGroupInput) SetLongHeadline(v string) {
	o.LongHeadline = v
}

// GetDescriptions returns the Descriptions field value
func (o *GooglePmaxAssetGroupInput) GetDescriptions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Descriptions
}

// GetDescriptionsOk returns a tuple with the Descriptions field value
// and a boolean to check if the value has been set.
func (o *GooglePmaxAssetGroupInput) GetDescriptionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Descriptions, true
}

// SetDescriptions sets field value
func (o *GooglePmaxAssetGroupInput) SetDescriptions(v []string) {
	o.Descriptions = v
}

// GetBusinessName returns the BusinessName field value
func (o *GooglePmaxAssetGroupInput) GetBusinessName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessName
}

// GetBusinessNameOk returns a tuple with the BusinessName field value
// and a boolean to check if the value has been set.
func (o *GooglePmaxAssetGroupInput) GetBusinessNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessName, true
}

// SetBusinessName sets field value
func (o *GooglePmaxAssetGroupInput) SetBusinessName(v string) {
	o.BusinessName = v
}

// GetImages returns the Images field value
func (o *GooglePmaxAssetGroupInput) GetImages() GooglePmaxAssetGroupInputImages {
	if o == nil {
		var ret GooglePmaxAssetGroupInputImages
		return ret
	}

	return o.Images
}

// GetImagesOk returns a tuple with the Images field value
// and a boolean to check if the value has been set.
func (o *GooglePmaxAssetGroupInput) GetImagesOk() (*GooglePmaxAssetGroupInputImages, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Images, true
}

// SetImages sets field value
func (o *GooglePmaxAssetGroupInput) SetImages(v GooglePmaxAssetGroupInputImages) {
	o.Images = v
}

// GetYoutubeVideoId returns the YoutubeVideoId field value if set, zero value otherwise.
func (o *GooglePmaxAssetGroupInput) GetYoutubeVideoId() string {
	if o == nil || IsNil(o.YoutubeVideoId) {
		var ret string
		return ret
	}
	return *o.YoutubeVideoId
}

// GetYoutubeVideoIdOk returns a tuple with the YoutubeVideoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GooglePmaxAssetGroupInput) GetYoutubeVideoIdOk() (*string, bool) {
	if o == nil || IsNil(o.YoutubeVideoId) {
		return nil, false
	}
	return o.YoutubeVideoId, true
}

// HasYoutubeVideoId returns a boolean if a field has been set.
func (o *GooglePmaxAssetGroupInput) HasYoutubeVideoId() bool {
	if o != nil && !IsNil(o.YoutubeVideoId) {
		return true
	}

	return false
}

// SetYoutubeVideoId gets a reference to the given string and assigns it to the YoutubeVideoId field.
func (o *GooglePmaxAssetGroupInput) SetYoutubeVideoId(v string) {
	o.YoutubeVideoId = &v
}

func (o GooglePmaxAssetGroupInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GooglePmaxAssetGroupInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["finalUrl"] = o.FinalUrl
	toSerialize["headlines"] = o.Headlines
	toSerialize["longHeadline"] = o.LongHeadline
	toSerialize["descriptions"] = o.Descriptions
	toSerialize["businessName"] = o.BusinessName
	toSerialize["images"] = o.Images
	if !IsNil(o.YoutubeVideoId) {
		toSerialize["youtubeVideoId"] = o.YoutubeVideoId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GooglePmaxAssetGroupInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"finalUrl",
		"headlines",
		"longHeadline",
		"descriptions",
		"businessName",
		"images",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGooglePmaxAssetGroupInput := _GooglePmaxAssetGroupInput{}

	err = json.Unmarshal(data, &varGooglePmaxAssetGroupInput)

	if err != nil {
		return err
	}

	*o = GooglePmaxAssetGroupInput(varGooglePmaxAssetGroupInput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "finalUrl")
		delete(additionalProperties, "headlines")
		delete(additionalProperties, "longHeadline")
		delete(additionalProperties, "descriptions")
		delete(additionalProperties, "businessName")
		delete(additionalProperties, "images")
		delete(additionalProperties, "youtubeVideoId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGooglePmaxAssetGroupInput struct {
	value *GooglePmaxAssetGroupInput
	isSet bool
}

func (v NullableGooglePmaxAssetGroupInput) Get() *GooglePmaxAssetGroupInput {
	return v.value
}

func (v *NullableGooglePmaxAssetGroupInput) Set(val *GooglePmaxAssetGroupInput) {
	v.value = val
	v.isSet = true
}

func (v NullableGooglePmaxAssetGroupInput) IsSet() bool {
	return v.isSet
}

func (v *NullableGooglePmaxAssetGroupInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGooglePmaxAssetGroupInput(val *GooglePmaxAssetGroupInput) *NullableGooglePmaxAssetGroupInput {
	return &NullableGooglePmaxAssetGroupInput{value: val, isSet: true}
}

func (v NullableGooglePmaxAssetGroupInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGooglePmaxAssetGroupInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
