/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.179.1
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WhatsAppContactIdentity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhatsAppContactIdentity{}

// WhatsAppContactIdentity struct for WhatsAppContactIdentity
type WhatsAppContactIdentity struct {
	// The user's WhatsApp phone number (wa_id), null when Meta did not send it (a username adopter who hides it).
	PhoneNumber NullableString `json:"phoneNumber"`
	// Meta business-scoped user id (BSUID), for example `US.13491208655302741918`.
	BusinessScopedUserId NullableString `json:"businessScopedUserId"`
	// Parent BSUID, shared across the businesses of one portfolio when Meta sends it.
	ParentBusinessScopedUserId NullableString `json:"parentBusinessScopedUserId"`
	// The user's WhatsApp username, when Meta sent one with the change. Null on `previous`.
	WhatsappUsername NullableString `json:"whatsappUsername"`
}

type _WhatsAppContactIdentity WhatsAppContactIdentity

// NewWhatsAppContactIdentity instantiates a new WhatsAppContactIdentity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppContactIdentity(phoneNumber NullableString, businessScopedUserId NullableString, parentBusinessScopedUserId NullableString, whatsappUsername NullableString) *WhatsAppContactIdentity {
	this := WhatsAppContactIdentity{}
	this.PhoneNumber = phoneNumber
	this.BusinessScopedUserId = businessScopedUserId
	this.ParentBusinessScopedUserId = parentBusinessScopedUserId
	this.WhatsappUsername = whatsappUsername
	return &this
}

// NewWhatsAppContactIdentityWithDefaults instantiates a new WhatsAppContactIdentity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppContactIdentityWithDefaults() *WhatsAppContactIdentity {
	this := WhatsAppContactIdentity{}
	return &this
}

// GetPhoneNumber returns the PhoneNumber field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WhatsAppContactIdentity) GetPhoneNumber() string {
	if o == nil || o.PhoneNumber.Get() == nil {
		var ret string
		return ret
	}

	return *o.PhoneNumber.Get()
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WhatsAppContactIdentity) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumber.Get(), o.PhoneNumber.IsSet()
}

// SetPhoneNumber sets field value
func (o *WhatsAppContactIdentity) SetPhoneNumber(v string) {
	o.PhoneNumber.Set(&v)
}

// GetBusinessScopedUserId returns the BusinessScopedUserId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WhatsAppContactIdentity) GetBusinessScopedUserId() string {
	if o == nil || o.BusinessScopedUserId.Get() == nil {
		var ret string
		return ret
	}

	return *o.BusinessScopedUserId.Get()
}

// GetBusinessScopedUserIdOk returns a tuple with the BusinessScopedUserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WhatsAppContactIdentity) GetBusinessScopedUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BusinessScopedUserId.Get(), o.BusinessScopedUserId.IsSet()
}

// SetBusinessScopedUserId sets field value
func (o *WhatsAppContactIdentity) SetBusinessScopedUserId(v string) {
	o.BusinessScopedUserId.Set(&v)
}

// GetParentBusinessScopedUserId returns the ParentBusinessScopedUserId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WhatsAppContactIdentity) GetParentBusinessScopedUserId() string {
	if o == nil || o.ParentBusinessScopedUserId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ParentBusinessScopedUserId.Get()
}

// GetParentBusinessScopedUserIdOk returns a tuple with the ParentBusinessScopedUserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WhatsAppContactIdentity) GetParentBusinessScopedUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentBusinessScopedUserId.Get(), o.ParentBusinessScopedUserId.IsSet()
}

// SetParentBusinessScopedUserId sets field value
func (o *WhatsAppContactIdentity) SetParentBusinessScopedUserId(v string) {
	o.ParentBusinessScopedUserId.Set(&v)
}

// GetWhatsappUsername returns the WhatsappUsername field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WhatsAppContactIdentity) GetWhatsappUsername() string {
	if o == nil || o.WhatsappUsername.Get() == nil {
		var ret string
		return ret
	}

	return *o.WhatsappUsername.Get()
}

// GetWhatsappUsernameOk returns a tuple with the WhatsappUsername field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WhatsAppContactIdentity) GetWhatsappUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WhatsappUsername.Get(), o.WhatsappUsername.IsSet()
}

// SetWhatsappUsername sets field value
func (o *WhatsAppContactIdentity) SetWhatsappUsername(v string) {
	o.WhatsappUsername.Set(&v)
}

func (o WhatsAppContactIdentity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhatsAppContactIdentity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phoneNumber"] = o.PhoneNumber.Get()
	toSerialize["businessScopedUserId"] = o.BusinessScopedUserId.Get()
	toSerialize["parentBusinessScopedUserId"] = o.ParentBusinessScopedUserId.Get()
	toSerialize["whatsappUsername"] = o.WhatsappUsername.Get()
	return toSerialize, nil
}

func (o *WhatsAppContactIdentity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phoneNumber",
		"businessScopedUserId",
		"parentBusinessScopedUserId",
		"whatsappUsername",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWhatsAppContactIdentity := _WhatsAppContactIdentity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWhatsAppContactIdentity)

	if err != nil {
		return err
	}

	*o = WhatsAppContactIdentity(varWhatsAppContactIdentity)

	return err
}

type NullableWhatsAppContactIdentity struct {
	value *WhatsAppContactIdentity
	isSet bool
}

func (v NullableWhatsAppContactIdentity) Get() *WhatsAppContactIdentity {
	return v.value
}

func (v *NullableWhatsAppContactIdentity) Set(val *WhatsAppContactIdentity) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppContactIdentity) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppContactIdentity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppContactIdentity(val *WhatsAppContactIdentity) *NullableWhatsAppContactIdentity {
	return &NullableWhatsAppContactIdentity{value: val, isSet: true}
}

func (v NullableWhatsAppContactIdentity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppContactIdentity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
