/*
Zernio API

API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id.

API version: 1.212.0
Contact: support@zernio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zernio

import (
	"encoding/json"
)

// checks if the DeleteCommerceDiscount200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteCommerceDiscount200Response{}

// DeleteCommerceDiscount200Response struct for DeleteCommerceDiscount200Response
type DeleteCommerceDiscount200Response struct {
	Deleted    *bool   `json:"deleted,omitempty"`
	DiscountId *string `json:"discountId,omitempty"`
}

// NewDeleteCommerceDiscount200Response instantiates a new DeleteCommerceDiscount200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteCommerceDiscount200Response() *DeleteCommerceDiscount200Response {
	this := DeleteCommerceDiscount200Response{}
	return &this
}

// NewDeleteCommerceDiscount200ResponseWithDefaults instantiates a new DeleteCommerceDiscount200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteCommerceDiscount200ResponseWithDefaults() *DeleteCommerceDiscount200Response {
	this := DeleteCommerceDiscount200Response{}
	return &this
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *DeleteCommerceDiscount200Response) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteCommerceDiscount200Response) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *DeleteCommerceDiscount200Response) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *DeleteCommerceDiscount200Response) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetDiscountId returns the DiscountId field value if set, zero value otherwise.
func (o *DeleteCommerceDiscount200Response) GetDiscountId() string {
	if o == nil || IsNil(o.DiscountId) {
		var ret string
		return ret
	}
	return *o.DiscountId
}

// GetDiscountIdOk returns a tuple with the DiscountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteCommerceDiscount200Response) GetDiscountIdOk() (*string, bool) {
	if o == nil || IsNil(o.DiscountId) {
		return nil, false
	}
	return o.DiscountId, true
}

// HasDiscountId returns a boolean if a field has been set.
func (o *DeleteCommerceDiscount200Response) HasDiscountId() bool {
	if o != nil && !IsNil(o.DiscountId) {
		return true
	}

	return false
}

// SetDiscountId gets a reference to the given string and assigns it to the DiscountId field.
func (o *DeleteCommerceDiscount200Response) SetDiscountId(v string) {
	o.DiscountId = &v
}

func (o DeleteCommerceDiscount200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteCommerceDiscount200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	if !IsNil(o.DiscountId) {
		toSerialize["discountId"] = o.DiscountId
	}
	return toSerialize, nil
}

type NullableDeleteCommerceDiscount200Response struct {
	value *DeleteCommerceDiscount200Response
	isSet bool
}

func (v NullableDeleteCommerceDiscount200Response) Get() *DeleteCommerceDiscount200Response {
	return v.value
}

func (v *NullableDeleteCommerceDiscount200Response) Set(val *DeleteCommerceDiscount200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteCommerceDiscount200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteCommerceDiscount200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteCommerceDiscount200Response(val *DeleteCommerceDiscount200Response) *NullableDeleteCommerceDiscount200Response {
	return &NullableDeleteCommerceDiscount200Response{value: val, isSet: true}
}

func (v NullableDeleteCommerceDiscount200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteCommerceDiscount200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
